SuperElastix/elastix

Common/GTesting/itkImageMaskSpatialObject2GTest.cxx
Fixed copyright text of itkImageMaskSpatialObject2GTest.cxx, as discussed with @mstaring
=> DOC: Fixed copyright text

Common/ITK4Workaround/itkComputeImageExtremaFilter.h, Common/ITK4Workaround/itkComputeImageExtremaFilter.hxx, Common/itkAdvancedRayCastInterpolateImageFunction.h, Common/itkReducedDimensionBSplineInterpolateImageFunction.h, Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.hxx, Testing/CI/Azure/ci.yml
- Replaced `itk::VectorCastImageFilter` by `itk::CastImageFilter`.
- Added `GetRadius()` overrides to `AdvancedRayCastInterpolateImageFunction` and `ReducedDimensionBSplineInterpolateImageFunction`.
- Adjusted `ComputeImageExtremaFilter` to use `StreamedGenerateData`
- Built with ITK tag v5.0.0
=> COMP: Fixed remaining compile errors building elastix with ITK 5.0.0

CMakeLists.txt, Core/Main/GTesting/CMakeLists.txt, Core/Main/GTesting/ElastixLibGTest.cxx
Added a minimal test, using the code example from the elastix manual, paragraph "Running elastix".
=> ENH: Add GoogleTest for elastix library

Common/Transforms/itkAdvancedRigid2DTransform.hxx, Components/Resamplers/MyStandardResampler/elxMyStandardResampler.h
Please merge this to fix build errors with latest ITK release candidate.
=> Fix build error with ITK v5.1rc03

Core/Install/elxComponentDatabase.cxx, Core/Install/elxComponentDatabase.h
Three style improvements of the ComponentDatabase class
=> Coding style improvements of ComponentDatabase

Common/OpenCL/Filters/itkGPUCompositeTransformBase.hxx, Common/OpenCL/ITKimprovements/itkOpenCLLogger.cxx, Common/OpenCL/ITKimprovements/itkOpenCLLogger.h, Components/FixedImagePyramids/OpenCLFixedGenericPyramid/elxOpenCLFixedGenericPyramid.hxx, Components/MovingImagePyramids/OpenCLMovingGenericPyramid/elxOpenCLMovingGenericPyramid.hxx, Components/Resamplers/OpenCLResampler/elxOpenCLResampler.hxx
Subset of changes from Matt McCormick, "WIP: Work around missing TransformCategoryType definition"
https://github.com/thewtex/elastix/commit/0d5b789949a968d4b91cda58545890dcda5d5531
=> COMP: Fix ITK 5.1 compatibility for OpenCL based functionality

Common/CostFunctions/itkAdvancedImageToImageMetric.h, Common/CostFunctions/itkAdvancedImageToImageMetric.hxx, Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.h, Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx, Common/ImageSamplers/itkImageToVectorContainerFilter.h, Common/ImageSamplers/itkImageToVectorContainerFilter.hxx, Common/Transforms/itkAdvancedImageMomentsCalculator.h, Common/Transforms/itkAdvancedImageMomentsCalculator.hxx, Common/itkComputeDisplacementDistribution.h, Common/itkComputeDisplacementDistribution.hxx, Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.h, Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx, Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.h, Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx, Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.h, Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx, Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.h, Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx, Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.h, Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx, Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.h, Testing/itkAccumulateDerivativesParallellizationTest.cxx, Testing/itkAdvanceOneStepParallellizationTest.cxx
Fix for #215 
Signed-off-by: ax1oma <ax1oma@yandex.ru>
=> fix compilation on win32

Core/Main/GTesting/ElastixLibGTest.cxx
Also added five local helper functions: ExpectRoundedTransformParametersEqualOffset, ConvertStringsToArrayOfDouble, ConvertArrayOfDoubleToOffset, FillImageRegion, CreateParameterMap.
=> ENH: Add ElastixLib.Translation3D GoogleTest

.github/workflows/cmake.yml
Besides the Azure Pipeline workflow, the Github Actions workflow includes:
- caching of ITK by version number to speed up build time
- uploading the executables (elastix and transformix) per operating system as artifacts.
=> Github Actions to replace Azure Pipelines

NOTICE
Updated notices according to:
- https://github.com/InsightSoftwareConsortium/ITK/blob/v5.1.1/NOTICE
- https://github.com/SuperElastix/elastix/blob/5.0.1/Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/Copyright.txt
- https://github.com/SuperElastix/elastix/blob/5.0.1/Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/License.txt
=> DOC: Update copyright notices regarding ITK and ANN

Common/GTesting/elxTransformIOGTest.cxx
Checks the content of parameter map of a "default" transform object.
Checks the floating point precision of the string representation of a `double` value. The precision is currently 6 digits.
=> ENH: Add two CreateTransformParametersMap GoogleTest unit tests

.github/workflows/ElastixGitHubActions.yml
=> CI: ctest logs to cdash

Core/ComponentBaseClasses/elxTransformBase.h, Core/ComponentBaseClasses/elxTransformBase.hxx
Preparing to add extra functionality: the ability to read ITK .tfm files.
=> Clean up code of TransformBase ReadInitialTransform implementation 

.githooks/pre-commit, CONTRIBUTING.md
- A pre-commit hook for local git usage on both Windows and Unix systems.
- Pre-commit hook use update in CONTRIBUTING.md
=> STYLE:clangFormat pre-commit hook

Common/xout/xoutbase.h, Common/xout/xoutbase.hxx, Common/xout/xoutcell.hxx, Core/Install/elxBaseComponent.h
A few possible style improvements encountered while preparing to improve thread-safety of the output streams.
=> Style improvements xoutbase and xoutcell

Components/Metrics/GradientDifference/itkGradientDifferenceImageToImageMetric2.hxx, Components/Metrics/NormalizedGradientCorrelation/itkNormalizedGradientCorrelationImageToImageMetric.hxx, Components/Metrics/PCAMetric/elxPCAMetric.hxx, Components/Metrics/PatternIntensity/itkPatternIntensityImageToImageMetric.hxx, Components/Metrics/SumOfPairwiseCorrelationsMetric/elxSumOfPairwiseCorrelationCoefficientsMetric.hxx, Components/Metrics/VarianceOverLastDimension/elxVarianceOverLastDimensionMetric.hxx, Core/ComponentBaseClasses/elxResamplerBase.hxx, Core/Install/elxBaseComponent.h, Core/Install/elxBaseComponentSE.h, Core/Install/elxBaseComponentSE.hxx, Core/Install/elxInstallFunctions.h, Core/Install/elxMacro.h
Follow-up to pull request  #423 "Replace dynamic_cast from all GetAsITKBaseType() member functions by this->GetSelf()"
=> Replace seven more dynamic_casts from component base pointers to ITK pointers

Common/GTesting/elxConversionGTest.cxx, Core/Install/elxConversion.cxx, Core/Install/elxConversion.h
Including GoogleTest unit test.
=> ENH: Add Conversion::ToOptimizerParameters(const std::vector<double> &)

Common/GTesting/elxConversionGTest.cxx, Common/ParameterFileParser/itkParameterMapInterface.h
The `ReadParameter<T>` member functions of `ParameterMapInterface` should fail when a parameter string is not entirely processed, during the conversion from `std::string` to type `T`.
For example, when the parameter has string value "0.1", an attempt to read it into an integer will only process the string until (just before) the decimal point. This should trigger an exception.
Note that a string value like "123.000" should still be converted to an integer, by `ReadParameter<int>`, as it only has trailing zero's after the decimal point.
=> BUG: ReadParameter should fail if parameter string isn't fully processed

Core/Main/elastix.cxx
Addressed a comment by Amirhossein Jalalzadeh in "Corresponding Points", May 5, 2021, https://groups.google.com/g/elastix-imageregistration/c/WXsFyx5DTz0/m/qMCAzNWzBwAJ
=> ENH: Help should mention optional point set arguments

Core/Main/GTesting/ElastixLibGTest.cxx
Tests registering two 3-D images with mask of a single slice with true (value `1`) values .
Regarding issue #368 "Problems in 5.0.1 with masks w/ only 1 slice with true values", reported by Patrik Brynolfsson (@PatrikBrynolfsson).
=> ENH: Add ElastixLib.SingleSliceMaskedTranslation3D GTest (issue #368)

Common/GTesting/elxTransformIOGTest.cxx
Extended input test values for `Expect_elx_TransformPoint_yields_same_point_as_ITK`, also improving the unit test of other transforms.
=> ENH: Add Transform `TransformedPointSameAsITKBSpline` GTest unit tests

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
As explained by Marius (@mstaring) in a reply to "Set the Origin", May 17, 2021 at https://groups.google.com/g/elastix-imageregistration/c/1uQU7FaCOOs/m/7NmGT77cBAAJ
> By default the origin of the fixed image is chosen
=> ENH: Test the effect the origin points of the input images (GoogleTest)

Core/Main/GTesting/itkTransformixFilterGTest.cxx
Added three GoogleTest unit tests to itkTransformixFilter:
- CombineTranslationAndDefaultTransform
- CombineTranslationAndInverseTranslation
- CombineTranslationAndScale
=> ENH: Add itkTransformixFilter GTest unit tests, combining transforms

Common/Transforms/itkAdvancedBSplineDeformableTransform.h, Common/Transforms/itkBSplineInterpolationWeightFunctionBase.h, Common/Transforms/itkBSplineKernelFunction2.h, Common/Transforms/itkCyclicBSplineDeformableTransform.h, Common/Transforms/itkRecursiveBSplineTransform.h, Common/itkRecursiveBSplineInterpolationWeightFunction.h, Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.h
Which appears more like ITK style.
=> STYLE: Replace `Self::SplineOrder` by `VSplineOrder`

Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.hxx, Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.hxx, Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.hxx, Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.hxx
Specifically in `BeforeRegistration()` and `ReadFromFile()` member functions.
=> STYLE: Clean up grid related variables in BSpline Transform components

Testing/CI/Azure/ci.yml
Follow-up to pull request #557 "COMP: Upgrade Azure CI from macOS-10.14 to macOS-10.15"
=> Upgrade to Ubuntu 20.0.4 and Window-2019 at Azure pipelines CI

Common/ImageSamplers/itkImageSamplerBase.hxx, Common/ImageSamplers/itkMultiInputImageRandomCoordinateSampler.hxx, Common/itkMultiResolutionImageRegistrationMethod2.hxx, Common/itkReducedDimensionBSplineInterpolateImageFunction.h, Components/Metrics/DistancePreservingRigidityPenalty/itkDistancePreservingRigidityPenaltyTerm.hxx, Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx, Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx, Components/Metrics/PCAMetric2/itkPCAMetric2.hxx, Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx, Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx, Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx, Components/Registrations/MultiMetricMultiResolutionRegistration/itkMultiMetricMultiResolutionImageRegistrationMethod.hxx, Components/Registrations/MultiResolutionRegistrationWithFeatures/itkMultiInputMultiResolutionImageRegistrationMethodBase.hxx, Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx, Core/ComponentBaseClasses/elxTransformBase.hxx
Follow-up to ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2901 commit https://github.com/InsightSoftwareConsortium/ITK/commit/6a8569ef11cf4f788eeb659b532156479309d7a7 (merged on 27 November 2021).
=> PERF: Use the faster `TransformPhysicalPointToContinuousIndex` overload

Core/Main/itkElastixRegistrationMethod.h, Core/Main/itkElastixRegistrationMethod.hxx, Core/Main/itkTransformixFilter.h, Core/Main/itkTransformixFilter.hxx
Do in-class default member initialization, as introduced with C++11.
=> STYLE: In-class member init TransformixFilter, ElastixRegistrationMethod

Common/ParameterFileParser/CMakeLists.txt, Common/ParameterFileParser/itkParameterMapInterface.cxx, Common/ParameterFileParser/itkParameterMapInterface.h, Core/CMakeLists.txt, Core/Install/elxConversion.cxx, Core/Install/elxConversion.h, Testing/CMakeLists.txt
Made this overload set public.
=> ENH: Move ParameterMapInterface::StringCast to Conversion::StringToValue

Common/CostFunctions/itkMultiInputImageToImageMetricBase.h, Common/CostFunctions/itkMultiInputImageToImageMetricBase.hxx, Common/CostFunctions/itkSingleValuedPointSetToPointSetMetric.h, Common/CostFunctions/itkSingleValuedPointSetToPointSetMetric.hxx
Hoping to slightly speed-up compilations, and ease further maintenance.
=> STYLE: Default Metric default-constructors in "Common/CostFunctions"

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Based on suggestions by Konstantinos (@ntatsisk).
=> ENH: Test Euler transform registration on larger disc rotation angles

Common/OpenCL/ITKimprovements/itkOpenCLExport.h
=> ENH: Fix compilation of shared libraries with opencl on windows

Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx, Common/Transforms/itkAdvancedIdentityTransform.h, Common/Transforms/itkAdvancedTranslationTransform.hxx, Common/Transforms/itkRecursiveBSplineTransform.hxx, Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.hxx, Components/Transforms/SplineKernelTransform/itkKernelTransform2.hxx, Components/Transforms/WeightedCombinationTransform/itkWeightedCombinationTransform.hxx, Core/Kernel/elxTransformixMain.cxx, Core/Main/itkElastixRegistrationMethod.hxx
=> Range-based `for` for each inputName, improved ApplyTransform error message, `std::iota` for nonzero Jacobian indices

Components/elxGenericPyramidHelper.h
Pair-programmed w/ Konstantinos (@ntatsisk).
=> ENH: Add warnings on schedule adjustments in pyramids

.github/workflows/ElastixGitHubActions.yml
Rather than comparing with a very specific OS version.
Eases upgrading virtual machines
=> STYLE: Use `startsWith` for matrix.os comparisons GitHub Actions

Testing/CI/Azure/ci.yml
Based on https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines#trigger-batch-branches-paths-tags
=> COMP: Exclude files and directories from Azure pipelines build

Core/Kernel/elxlog.cxx, Core/Kernel/elxlog.h, Core/Main/elastix.cxx, Core/Main/elxMainExeUtilities.cxx, Core/Main/elxMainExeUtilities.h, Core/Main/transformix.cxx
@mstaring @stefanklein @ntatsisk Adding log level to the ITKElastix/library interface is still on my TODO list. But the command-line option is here already  😃
=> Add "-loglevel" command-line option to elastix and transformix exe

Common/itkGenericMultiResolutionPyramidImageFilter.hxx
Removed the anonymous namespace from itkGenericMultiResolutionPyramidImageFilter.hxx, following C++ Core Guidelines, September 23, 2022, "Don’t use an unnamed (anonymous) namespace in a header", http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf21-dont-use-an-unnamed-anonymous-namespace-in-a-header
Refactored the `UpdateAndGraft` function template from that namespace into a lambda, declared locally inside `GenericMultiResolutionPyramidImageFilter::GenerateData()`.
=> STYLE: Remove namespace itkGenericMultiResolutionPyramidImageFilter.hxx

Common/itkAdvancedRayCastInterpolateImageFunction.h, Common/itkAdvancedRayCastInterpolateImageFunction.hxx
Follow-up to ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3937 commit https://github.com/InsightSoftwareConsortium/ITK/commit/208902e16a9103d486c7078a747d04044b780441
=> COMP: Move RayCastHelper from unnamed namespace to private class section

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Improved code readability of GTest `itkElastixRegistrationMethod.SetInitialTransformParameterObject`
=> STYLE: Improve readability of `SetInitialTransformParameterObject` test

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx, Core/Main/itkElastixRegistrationMethod.hxx
When `ElastixRegistrationMethod` writes an external initial transform (as specified by `SetExternalInitialTransform`) to its output directory, it will now write the transform to a separate ITK transform file. By default, it will use ITK's TFM file format, but it can be set by the "ITKTransformOutputFileNameExtension" parameter.
=> ENH: Write external initial transforms to ITK transform file

Core/Main/GTesting/itkTransformixFilterGTest.cxx, Core/Main/itkTransformixFilter.h, Core/Main/itkTransformixFilter.hxx
Including GoogleTest unit test.
=> ENH: Add `SetExternalTransform` to TransformixFilter

Common/itkComputeJacobianTerms.hxx
Instead of doing `difHist.resize(0)`. (`resize(0)` does _not_ free the memory of a `std::vector<unsigned int>`!)
Following C++ Core Guidelines, April 13, 2023 "Keep scopes small" ("Don’t declare a name in an unnecessarily large scope."), https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es5-keep-scopes-small
---
When reviewing, it may be helpful to ignore whitespace changes: https://github.com/SuperElastix/elastix/pull/954/files?w=1
=> PERF: Let `difHist` in ComputeJacobianTerms go out of scope when used

Common/GTesting/itkImageRandomCoordinateSamplerGTest.cxx, Common/ImageSamplers/itkImageRandomCoordinateSampler.h, Common/ImageSamplers/itkImageRandomCoordinateSampler.hxx
Internally calling `multiThreader.SingleMethodExecute()`, instead of overriding `ThreadedGenerateData`.
When 10'000 random samples are retrieved, a significant performance improvement is observed by enabling `UseMultiThread`: from ~48 millisecond (single-threaded) to ~40 millisecond (multi-threaded). When 100'000 random samples are retrieved, even from ~123 to ~56 millisecond: Tested on a Windows 10 PC (6 cores, 12 logical processors), VS2019 Release build.
Follow-up to pull request https://github.com/SuperElastix/elastix/pull/973 commit ca9e9ecdf5a1bf7fca2df887feaf5c87365c5b81 "ENH: ImageRandomSampler `UseMultiThread` now using ITK's ThreadPool"
=> ENH: ImageRandomCoordinateSampler `UseMultiThread` use ITK's ThreadPool

Common/ImageSamplers/itkImageToVectorContainerFilter.h, Common/ImageSamplers/itkImageToVectorContainerFilter.hxx
Added `inputRegion` parameter. Removed debug-build-only `itkDebugMacro` statements.
=> STYLE: Rename `SplitRequestedRegion` to "SplitRegion", make it `static`

Common/ImageSamplers/itkImageGridSampler.h, Common/ImageSamplers/itkImageGridSampler.hxx
Added gridSpacing as parameter, instead of accessing m_SampleGridSpacing directly.
=> STYLE: Declare `ImageGridSampler::JumpToNextGridPosition` static

Common/GTesting/CMakeLists.txt, Common/GTesting/itkAdvancedImageToImageMetricGTest.cxx
A very basic first `AdvancedImageToImageMetric` unit test.
=> ENH: Add itkAdvancedImageToImageMetricGTest.cxx

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx, Common/Transforms/itkAdvancedImageMomentsCalculator.hxx, Common/itkComputeDisplacementDistribution.hxx, Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx, Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx, Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx, Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx, Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx, Components/Metrics/DisplacementMagnitudePenalty/itkDisplacementMagnitudePenaltyTerm.hxx, Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx, Components/Metrics/PCAMetric/itkPCAMetric.hxx, Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx, Components/Metrics/PCAMetric2/itkPCAMetric2.hxx, Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx, Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx, Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx
Reduced the amount of boilerplate code, and possibly gained some performance improvement.
=> Modernize iteration over samples in Metrics

Common/ImageSamplers/itkImageRandomCoordinateSampler.hxx, Common/ImageSamplers/itkImageRandomSampler.hxx, Common/ImageSamplers/itkMultiInputImageRandomCoordinateSampler.hxx
Accessed the samples directly by the `std::vector` interface instead of via the `VectorDataContainer` interface.
Reduced the amount of boilerplate code, and possibly gained some performance improvement, in Random Samplers.
=> STYLE: Use range-based `for` to iterate over samples in Samplers

Common/Transforms/itkTransformToDeterminantOfSpatialJacobianSource.hxx, Common/Transforms/itkTransformToSpatialJacobianSource.hxx, Common/itkComputePreconditionerUsingDisplacementDistribution.hxx
Following ITK:
-  pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4470
=> Use more `std::min` and `std::max` in "elastix/Common/*.hxx"

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx, Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx, Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx, Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx, Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx, Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx, Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx, Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx, Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx, Components/Transforms/SplineKernelTransform/itkKernelTransform2.hxx, Testing/itkAccumulateDerivativesParallellizationTest.cxx, Testing/itkAdvanceOneStepParallellizationTest.cxx
A few style improvements in multi-threaded member functions.
=> Add const to local `jmin` and `jmax` variable declarations, add local `metric` variables, etc.

Common/GTesting/itkAdvancedMeanSquaresImageToImageMetricGTest.cxx
Added AdvancedMeanSquaresImageToImageMetric tests:
- YieldsZeroWhenFixedAndMovingImageAreEqual
- MultiThreadResultEqualsSingleThreadResult
=> ENH: MeanSquaresImageToImageMetric test MultiThread equals SingleThread

Common/LineSearchOptimizers/itkMoreThuenteLineSearchOptimizer.cxx, Common/Transforms/itkAdvancedCombinationTransform.hxx, Common/itkGenericMultiResolutionPyramidImageFilter.hxx, Components/Metrics/StatisticalShapePenalty/itkStatisticalShapePointPenalty.hxx, Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx, Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx, Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx, Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx, Components/Transforms/SplineKernelTransform/itkKernelTransform2.hxx
Three style commits, following ITK.
=> Remove `== true`, use `std::clamp`, etc., following ITK 

.github/workflows/ElastixGitHubActions.yml, Testing/CI/Azure/ci.yml
Looks like the windows-2022 issue is fixed...
=> Restore windows-2022/Visual Studio 2022 at the CI

Components/Metrics/PCAMetric/itkPCAMetric.h, Components/Metrics/PCAMetric/itkPCAMetric.hxx
Mostly stylish changes to make it easier to compare the source files of "itkPCAMetric" and "PCAMetric_f_multithreaded".
=> Make "PCAMetric" more like "PCAMetric_f_multithreaded"

Components/Transforms/AffineLogStackTransform/elxAffineLogStackTransform.hxx, Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.hxx, Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx, Components/Transforms/TranslationStackTransform/elxTranslationStackTransform.hxx
=> Remove `this->` from elx stack transforms, add local `configuration` variables

Components/Metrics/PCAMetric/itkPCAMetric.hxx, Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx, Components/Metrics/PCAMetric2/itkPCAMetric2.hxx, Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx, Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx
Reduced some code duplication.
=> STYLE: Remove local `index = i % num` variables from itk*.hxx files

Components/Metrics/PCAMetric/elxPCAMetric.hxx, Components/Metrics/PCAMetric2/elxPCAMetric2.hxx, Components/Metrics/SumOfPairwiseCorrelationsMetric/elxSumOfPairwiseCorrelationCoefficientsMetric.hxx, Components/Metrics/VarianceOverLastDimension/elxVarianceOverLastDimensionMetric.hxx
And a few more stylish improvements
=> Move transform initializations within BeforeEachResolution() into `if` conditions

dox/doxygen/DoxygenHeader.html
-- As was discussed with Marius (@mstaring) and Michèle (@mwjhhuijberts)!
M + M, can you please check this pull request?
=> STYLE: Remove obsolete Google search bar from Doxygen

Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx, Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx, Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx, Components/Metrics/DisplacementMagnitudePenalty/itkDisplacementMagnitudePenaltyTerm.hxx, Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx, Components/Metrics/NormalizedGradientCorrelation/itkNormalizedGradientCorrelationImageToImageMetric.hxx, Components/Metrics/PCAMetric/itkPCAMetric.hxx, Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx, Components/Metrics/PCAMetric2/itkPCAMetric2.hxx, Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx, Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx, Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.hxx
`m_NumberOfPixelsCounted` is a protected member of ITK's `itk::ImageToImageMetric`, which is a common base class ("superclass") of elastix metric classes.
=> STYLE: Replace `this->` with `Superclass::` on m_NumberOfPixelsCounted

Common/itkParabolicErodeDilateImageFilter.h, Common/itkParabolicErodeDilateImageFilter.hxx, Common/itkParabolicMorphUtils.h
- Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITKParabolicMorphology/pull/46
- Also follows https://github.com/InsightSoftwareConsortium/ITKParabolicMorphology/commit/2869b78a354b5cc30cda43211eaf1f70a2740bb2
=> Remove `m_Extreme` and `m_MagnitudeSign` from `ParabolicErodeDilateImageFilter`

Common/OpenCL/ITKimprovements/itkOpenCLContext.cxx, Common/itkComputeDisplacementDistribution.hxx, Common/itkComputePreconditionerUsingDisplacementDistribution.hxx, Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx, Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx, Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx, Components/Metrics/PCAMetric/itkPCAMetric.hxx, Components/Metrics/PCAMetric2/itkPCAMetric2.hxx, Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx, Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx, Components/Optimizers/RSGDEachParameterApart/itkRSGDEachParameterApartBaseOptimizer.cxx, Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.hxx, Core/Main/elxParameterObject.cxx, Testing/itkAccumulateDerivativesParallellizationTest.cxx
=> Replace `T var = T(...)` with `T var(...)`, specify fill value with DerivativeType variable declarations 

Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.h, Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.hxx, Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.h, Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.hxx, Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.h, Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.hxx, Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.h, Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.hxx, Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx, Core/ComponentBaseClasses/elxResamplerBase.hxx, Core/ComponentBaseClasses/elxTransformBase.h, Core/Kernel/elxElastixTemplate.hxx
Triggered by the discussion "Elastix idiosyncracy?", started by Soren Christensen, July 11, 2024, at https://discourse.itk.org/t/elastix-idiosyncracy/7049
=> Add notes on the order of matrix elements of `Direction` and `GridDirection` parameters

Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/elxCorrespondingPointsEuclideanDistanceMetric.h, Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/elxCorrespondingPointsEuclideanDistanceMetric.hxx
Adjusted the private ReadLandmarks member function to return the point set.
=> STYLE: Declare local point sets in EuclideanDistanceMetric "const"

Testing/OpenCLImageTest.cl
- followup the pull request #1246
=> Itk OpenCLImage test fixes

Common/ImageSamplers/itkImageGridSampler.hxx, Common/Transforms/itkGridScheduleComputer.hxx, Common/itkParabolicErodeDilateImageFilter.hxx, Components/Metrics/DistancePreservingRigidityPenalty/itkDistancePreservingRigidityPenaltyTerm.hxx, Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx, Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.hxx, Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.hxx, Core/ComponentBaseClasses/elxMetricBase.hxx, Testing/elxTransformParametersCompare.cxx, Testing/itkAdvancedBSplineDeformableTransformTest.cxx, Testing/itkAdvancedRecursiveBSplineTransformTest.cxx, Testing/itkBSplineInterpolationWeightFunctionTest.cxx, Testing/itkBSplineJacobianGradientPerformanceTest.cxx, Testing/itkBSplineTransformPointPerformanceTest.cxx, Testing/itkOpenCLKernelToImageBridgeTest.cxx
Following the following ITK pull requests:
- https://github.com/InsightSoftwareConsortium/ITK/pull/4891
- https://github.com/InsightSoftwareConsortium/ITK/pull/4924
=> Replace `Fill` calls with `auto var = MakeFilled<T>`

Common/OpenCL/ITKimprovements/itkGPUInPlaceImageFilter.hxx, Common/OpenCL/ITKimprovements/itkOpenCLContext.cxx, Common/OpenCL/ITKimprovements/itkOpenCLEvent.cxx, Common/itkMultiOrderBSplineDecompositionImageFilter.hxx, Components/Metrics/GradientDifference/itkGradientDifferenceImageToImageMetric2.hxx, Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNFixedRadiusTreeSearch.hxx, Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNPriorityTreeSearch.hxx, Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNStandardTreeSearch.hxx, Components/Metrics/NormalizedGradientCorrelation/itkNormalizedGradientCorrelationImageToImageMetric.hxx, Components/Metrics/PCAMetric2/itkPCAMetric2.hxx, Components/Metrics/PatternIntensity/itkPatternIntensityImageToImageMetric.hxx, Components/Optimizers/SimultaneousPerturbation/elxSimultaneousPerturbation.hxx, Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.hxx, Components/Transforms/BSplineDeformableTransformWithDiffusion/itkVectorMeanDiffusionImageFilter.hxx, Testing/elxImageCompare.cxx
- Following ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4973
=> STYLE: Replace `T var; var = x` with `T var = x`

Components/Optimizers/AdaGrad/elxAdaGrad.hxx, Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx, Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx, Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx, Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx, Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.hxx, Core/Main/itkElastixRegistrationMethod.hxx, Testing/elxComputeOverlap.cxx, Testing/elxImageCompare.cxx, Testing/elxInvertTransform.cxx, Testing/elxTransformParametersCompare.cxx, Testing/itkGPUGenericMultiResolutionPyramidImageFilterTest.cxx, Testing/itkGPUResampleImageFilterTest.cxx, Testing/itkOpenCLContextTest.cxx, Testing/itkOpenCLKernelManagerTest.cxx
- Following ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4964 commit https://github.com/InsightSoftwareConsortium/ITK/commit/677b76192a6dcbf09375c7c1c19fa87ee8f59096
=> STYLE: Replace T::Pointer with auto when initializing variables by New()

README.md
- Following ITKElastix pull request https://github.com/InsightSoftwareConsortium/ITKElastix/pull/309 commit https://github.com/InsightSoftwareConsortium/ITKElastix/commit/3af580bdb1a648e34078fecc4477723f1da76935
---
The badge can be reviewed at https://github.com/SuperElastix/elastix/blob/eoss-badge/README.md
=> DOC: Add EOSS badge to README

Common/ParameterFileParser/itkParameterFileParser.cxx
Removed unnecessary std::deque of line indices.
=> STYLE: Simplify retrieval of line from TOML file

Testing/CMakeLists.txt
Eases debugging test failures.
=> ENH: Run tests both in Release _and_ in Debug mode

Common/GTesting/itkImageFileCastWriterGTest.cxx
Instead, now using `itk::ImageIOBase::MapPixelType` to find the type(s) that correspond with the enum value returned by `itk::ImageIOBase::GetComponentType()`.
`itk::ImageIO::GetComponentTypeInfo()` is deprecated, according to its documentation, as was committed to ITK on Feb 9, 2011: https://github.com/InsightSoftwareConsortium/ITK/commit/6ff5fc7f01148bd11070c5ecfe0d56f643f62565
=> STYLE: Avoid calling `itk::ImageIO::GetComponentTypeInfo()` in unit test

Common/CMakeLists.txt, Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx, Core/CMakeLists.txt, Core/ComponentBaseClasses/elxTransformBase.hxx, Core/Main/itkTransformixFilter.hxx
Follow up to comment by Niels Dekker in
https://github.com/SuperElastix/elastix/pull/1331#event-18415108159
=> COMP: Remove unused itkNumberToString.h include
