src/Core/Main/elastixlib.cxx
src/Core/Main/elastixlib.h

elastixlib supports user-supplied initial transform using additional input: RegisterImages( ..., ObjectPointer transform);
It was tested with AdvancedAffineTransformElastix as input:
error = _elastix->RegisterImages(
static_cast<typename itk::DataObject::Pointer> (_fixedImage),
static_cast<typename itk::DataObject::Pointer> (_movingImage),
_elastixPreAlignParametersVector, /*_elastixParameters*/
_outputPath,
_logToFile,
_logToConsole,
0,    // Optional, fixed image mask
0,    // Optional, floating image mask
static_cast<typename elastix::ElastixMain::ObjectPointer> (_initialTransform));  // Optional, initial transform

elastixlib supports user-supplied initial transform

---

appveyor.yml

Follow up on discussion in #6.
Numerous tests are failing on AppVeyor right now - see https://ci.appveyor.com/project/fedorov/elastix/build/1.0.8:
```
[00:50:41] 74% tests passed, 41 tests failed out of 157
[00:50:41] 
[00:50:41] Total Test time (real) = 626.55 sec
[00:50:41] 
[00:50:41] The following tests FAILED:
[00:50:41] 	 20 - elastix_run_example_COMPARE_IM (Failed)
[00:50:41] 	 23 - elastix_run_3DCT_lung.example_COMPARE_OVERLAP (Failed)
[00:50:41] 	 27 - elastix_run_3DCT_lung.NC.translation.ASGD.001_COMPARE_OVERLAP (Failed)
[00:50:41] 	 31 - elastix_run_3DCT_lung.NC.euler.ASGD.001_COMPARE_OVERLAP (Failed)
[00:50:41] 	 35 - elastix_run_3DCT_lung.NC.affine.ASGD.001_COMPARE_OVERLAP (Failed)
[00:50:41] 	 39 - elastix_run_3DCT_lung.NC.bspline_r.ASGD.001a_COMPARE_OVERLAP (Failed) …
```

ENH: add support of AppVeyor

---

Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxElastixBase.h
Core/Kernel/elxElastixMain.h
Core/Kernel/elxElastixTemplate.h
Core/Kernel/elxElastixTemplate.hxx
Core/Kernel/elxTransformixMain.cxx
Core/Main/elxTransformixFilter.h
Core/Main/elxTransformixFilter.hxx

Previously, when tranformix was asked to give deformation field it was written to disk directly (deformation.mhd), even when called from the library interface. Current pull request lets transformix pass its deformation field via memory.

ENH: TransformixFilter exposes deformation field object

---

Common/xout/xoutmain.cxx
Common/xout/xoutmain.h
Core/Kernel/elxElastixTemplate.hxx

Elastix did not call AfterRegistrationBase before throwing exception and consequently did not clean up xout. This resulted in undefined behaviour and more or less random segfaults if the ElastixFilter was called again after an exception was thrown. This would happen _even_ if the filter was completely destroyed and a new filter was instantiated because xout is a global static object. This possibly fixes SuperElastix/SimpleElastix#123 and an issue previously reported by @coertmetz.
The PR needs more testing and thorough review before merge. In addition, we should review exception handling elsewhere - e.g. for transformix. 
NOTE: This does not change the fact that elastix is not thread safe which might still be an issue (also reported by @coertmetz). The logger will most likely have to be …

BUG: Clean up xout before rethrow

---

Core/CMakeLists.txt

When installing elastix compiled as library I got this error:
CMake Error at src/Core/cmake_install.cmake:93 (file):
file INSTALL cannot find
".../src/ITKIOFactoryRegistration/itkImageIOFactoryRegisterManager.h".
Call Stack (most recent call first):
src/cmake_install.cmake:44 (include)
cmake_install.cmake:42 (include)
It is because ITKIOFactoryRegistration does not exits.
The actual folder name is ITKFactoryRegistration (without "IO").

Fix installing as library

---

Core/Main/elxTransformixFilter.h
Core/Main/elxTransformixFilter.hxx

needed to be overridden to use image properties from TransformParameterMap instead of MovingImage

BUG: TransformixFilter GenerateOuputInformation

---

Components/Optimizers/ConjugateGradient/itkGenericConjugateGradientOptimizer.cxx

Removed the `vcl_abs(0)` call that I accidentally added with
Revision: d975c0d070246fe3f5b3a91db0570cc4061ff9af
Date: 2019-01-08 4:44:57 PM
COMP: Replaced vcl (VXL) macro calls by direct calls to std functions

BUG: Removed accidentally added vcl_abs(0)

---

CMakeLists.txt
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Common/ImageSamplers/itkImageSamplerBase.hxx
Common/Transforms/itkAdvancedImageMomentsCalculator.hxx
Common/Transforms/itkCyclicGridScheduleComputer.hxx
Common/Transforms/itkGridScheduleComputer.hxx
Common/itkComputeDisplacementDistribution.hxx
Common/itkMultiOrderBSplineDecompositionImageFilter.hxx
Common/itkMultiResolutionImageRegistrationMethod2.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Registrations/MultiMetricMultiResolutionRegistration/itkMultiMetricMultiResolutionImageRegistrationMethod.hxx
Components/Registrations/MultiResolutionRegistrationWithFeatures/itkMultiInputMultiResolutionImageRegistrationMethodBase.hxx
Testing/itkAccumulateDerivativesParallellizationTest.cxx
Testing/itkAdvanceOneStepParallellizationTest.cxx

Replaced calls to the obsolete `vcl_ceil` macro from "ITK\Modules\ThirdParty\VNL\src\vxl\vcl\vcl_legacy_aliases.h" (in ITK5) by direct calls to `std::ceil`.
Fixes many "error C3861: identifier not found" messages, when using ITK5.
Follow-up to: 4e0a41732ad1654e9b801b698e2cf93ab772e9e1 (14 January 2019), "COMP: Replaced vcl_ceil (VXL) macro calls by direct calls to std::ceil"

COMP: Replaced vcl_ceil (VXL) macro calls by direct calls to std::ceil

---

CMakeLists.txt

Added command-line compilation defines to use `vnl_math` macro's for `abs`, `max`, `min`, `rnd`, etc., when ITK >= 5.
These macro's are also defined in "vxl\vcl\vcl_legacy_aliases.h"

COMP: Added compilation defines to use vnl_math legacy macro's with ITK5

---

Core/Kernel/elxElastixMain.cxx

Fixes compilation errors when using ITK 5 (from ITK git master branch):
elxElastixMain.cxx(164): error C2440: 'initializing': cannot convert from 'int' to 'itk::SmartPointer<elastix::ComponentDatabase::Self>'
elxElastixMain.cxx(165): error C2440: 'initializing': cannot convert from 'int' to 'itk::SmartPointer<elastix::ComponentLoader::Self>'
elxElastixMain.cxx(814): error C2440: 'initializing': cannot convert from 'int' to 'itk::SmartPointer<itk::Object::Self>'
elxElastixMain.cxx(816): error C2446: ':': no conversion from 'int' to 'elastix::ComponentDatabase::ObjectPointer'
Follow-up to revision 49421b181302c75e22158e282254c30b44631b55 (2019-01-08), "COMP: Fix error w/ ITK5, trying to initialize itk::SmartPointer by zero"

COMP: Fix elxElastixMain ITK5 errors, trying to use 0 for SmartPointer

---

Common/CostFunctions/itkExponentialLimiterFunction.hxx
Common/Transforms/itkAdvancedRigid2DTransform.hxx
Common/Transforms/itkAdvancedSimilarity2DTransform.hxx
Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/itkCorrespondingPointsEuclideanDistancePointMetric.hxx

Replaced uses of vcl versions of `numeric_limits`, `acos`, `exp`, and `atan` by using `std` directly. Fixes compile errors when trying to use ITK 5 (from the ITK git master branch).
Follow-up to d975c0d070246fe3f5b3a91db0570cc4061ff9af (8 January, 2019)

COMP: Replace vcl numeric_limits, acos, exp, atan by directly using std

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx

This commit replaces all direct access to the protected `itk::ImageToImageMetric` data member `m_NumberOfThreads` by calls to its `GetNumberOfThreads()` member function.
Doing so clarifies that elastix does not modify `itk::ImageToImageMetric::m_NumberOfThreads` directly. It is also a style improvement, because it reduces the dependency on the `itk::ImageToImageMetric` implementation.

STYLE: Avoid direct access to itk::ImageToImageMetric::m_NumberOfThreads

---

CMakeLists.txt
Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/ITK5Workaround/itkMultiThreader.h
Common/Transforms/itkAdvancedImageMomentsCalculator.hxx
Common/itkComputeDisplacementDistribution.hxx

This pull request allows compilation with both ITK4 _and_ ITK5 (latest from git master branch at https://github.com/InsightSoftwareConsortium/ITK/commit/dc26af240c732b2e74f8bcd0464066e8b189b2e1):
- COMP: Avoided m_Threader->SetUseThreadPool(false) with ITK5 
- COMP: Workaround ITK5, renaming NumberOfThreads into NumberOfWorkUnits 
- COMP: Workaround ITK5, renaming MultiThreader to PlatformMultiThreader

ITK5 thread workaround

---

CMakeLists.txt
Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx
Components/Metrics/MissingStructurePenalty/itkMissingStructurePenalty.hxx
Components/Metrics/PatternIntensity/itkPatternIntensityImageToImageMetric.hxx
Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx
Components/Metrics/StatisticalShapePenalty/elxStatisticalShapePenalty.hxx
Components/Metrics/StatisticalShapePenalty/itkStatisticalShapePointPenalty.hxx
Components/Optimizers/CMAEvolutionStrategy/itkCMAEvolutionStrategyOptimizer.cxx
Components/Optimizers/ConjugateGradientFRPR/elxConjugateGradientFRPR.hxx
Components/Transforms/AffineDTITransform/itkAffineDTI2DTransform.hxx
Components/Transforms/AffineDTITransform/itkAffineDTI3DTransform.hxx
Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.hxx
Components/Transforms/WeightedCombinationTransform/elxWeightedCombinationTransform.hxx

Initial commits to support ITK5 with elastix CMake option USE_ALL_COMPONENTS:
- Replace vcl macro calls by directly using std, in all components 
- Fix USE_ALL_COMPONENTS ITK5 SmartPointer compile errors 
- Added USE_ALL_COMPONENTS ITK5 C++11 vnl_math_cuberoot workaround

Initial commits to support ITK5 with USE_ALL_COMPONENTS

---

Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx

This commit replaces all direct access to the protected `itk::ImageToImageMetric` data member `m_NumberOfThreads` by calls to its `GetNumberOfThreads()` member function, in itkAdvancedKappaStatisticImageToImageMetric.hxx
Follow-up to commit 459bf068768a0b738d1ff8a39a55dd40ec30bab1 (18 Jan 2019)

STYLE: Avoid direct access AdvancedKappa to ITK m_NumberOfThreads

---

Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx
Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx

Originally `DummyIPPPixelType` was defined as `bool`, in `PolydataDummyPenalty::ReadTransformixPoints`, `MissingStructurePenalty::ReadTransformixPoints`, and `TransformBase::TransformPointsSomePoints`. This appears troublesome when using `DummyIPPPixelType` as `TElement` argument of `itk::VectorContainer<TElementIdentifier, TElement>`:
"COMP: Fix support itk::VectorContainer<TElementIdentifier, bool>"
InsightSoftwareConsortium/ITK#486
This commit defines `DummyIPPPixelType` as an `unsigned char` instead, in these three member functions.

COMP: Redefined DummyIPPPixelType as unsigned char

---

Testing/CI/Azure/ci.yml

Upgraded ITKv5_VERSION to today's revision of ITK's git master branch, which includes:
COMP: Fix support itk::VectorContainer<TElementIdentifier, bool>
https://github.com/InsightSoftwareConsortium/ITK/commit/8bd9a0d58c19adc38c0e58ea65be2fedaa2962e6
COMP: Fix SymmetricEigenAnalysis support TMatrix = itk::Array2D<T>
https://github.com/InsightSoftwareConsortium/ITK/commit/d7e352985f6c8e44cec02d9ad7e6eecebe32595f
These fixes appear necessary to compile elastix with ITKv5

COMP: Upgraded ITKv5_VERSION, to fix elastix compile errors with ITK5

---

Common/Transforms/itkTransformToDeterminantOfSpatialJacobianSource.hxx
Common/Transforms/itkTransformToSpatialJacobianSource.hxx
Common/itkComputeImageExtremaFilter.hxx
Common/itkParabolicErodeDilateImageFilter.hxx

Switched off modern ITK5 DynamicMultiThreading for ITK5, as `ThreadedGenerateData` should still be called.
Should fix elastix-ITK5 test failures.
See also:
https://github.com/InsightSoftwareConsortium/ITK/blob/v5.0rc01/Documentation/ITK5MigrationGuide.md#multithreading-refactored

BUG: Use classic ITK thread model in Source and Filter classes for ITK5

---

Common/TypeList.h

Reported by @kaspermarstal
opencl fixed pyramid:/home/kasper/dev/Elastix/Common/TypeList.h:494:45: error: expected primary-expression before ‘>’ token
visitor.CLANG_TEMPLATE operator()< Head >( );and/home/kasper/dev/Elastix/Components/FixedImagePyramids/OpenCLFixedGenericPyramid/elxOpenCLFixedGenericPyramid.cxx:21:45:   required from here
/home/kasper/dev/Elastix/Common/TypeList.h:744:63: error: return-statement with a value, in function returning 'void' [-fpermissive]
return impl.CLANG_TEMPLATE operator()< Visitor >( visitor );

COMP: fixed the VisitDimension OpenCL compilation issues

---

Testing/itkTestHelper.h

Fixed the error reported by @kaspermarstal
[ 58%] Building CXX object Testing/CMakeFiles/itkGPUResampleImageFilterTest.dir/itkGPUResampleImageFilterTest.cxx.o
In file included from /home/kasper/dev/Elastix/Testing/itkGPUResampleImageFilterTest.cxx:18:0:
/home/kasper/dev/Elastix/Testing/itkGPUResampleImageFilterTest.cxx: In function ‘int main(int, char**)’:
/home/kasper/dev/Elastix/Testing/itkTestHelper.h:58:27: error: ‘itk::MultiThreader’ has not been declared
#define MultiThreaderBase MultiThreader
^
/home/kasper/dev/Elastix/Testing/itkGPUResampleImageFilterTest.cxx:746:46: note: in expansion of macro ‘MultiThreaderBase’
unsigned int maximumNumberOfThreads = itk::MultiThreaderBase::GetGlobalDefaultNumberOfThreads();

COMP: fixed the compilation for the ITK4.

---

Common/Transforms/itkAdvancedTransform.h

Removed both `InverseJacobianPositionType` and `ComputeJacobianWithRespectToPosition(p, j)` from `AdvancedTransform`.
Neither the type nor the member function appear to be used. The type definition causes compilation errors with ITK4:
itkAdvancedTransform.h(116): error C2039: 'InverseJacobianPositionType': is not a member of 'itk::Transform'

COMP: Removed AdvancedTransform::InverseJacobianPositionType

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Common/ImageSamplers/itkImageToVectorContainerFilter.hxx
Common/Transforms/itkAdvancedImageMomentsCalculator.hxx
Common/itkComputeDisplacementDistribution.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.h
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.h
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx

There were a few simple things that prevented from Elastic to build with ITK5. This commit fixes these, preserving former ITK version compatibility with preprocessor ifs.

COMP: Fix ITK5 build issues

---

Common/Transforms/itkTransformToDeterminantOfSpatialJacobianSource.h
Common/Transforms/itkTransformToDeterminantOfSpatialJacobianSource.hxx
Common/Transforms/itkTransformToSpatialJacobianSource.h
Common/Transforms/itkTransformToSpatialJacobianSource.hxx
Common/itkImageSpatialObject2.h
Common/itkImageSpatialObject2.hxx
Common/itkMultiResolutionImageRegistrationMethod2.h
Common/itkMultiResolutionImageRegistrationMethod2.hxx
Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.h
Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.hxx
Components/Registrations/MultiMetricMultiResolutionRegistration/itkMultiMetricMultiResolutionImageRegistrationMethod.h
Components/Registrations/MultiMetricMultiResolutionRegistration/itkMultiMetricMultiResolutionImageRegistrationMethod.hxx
Components/Registrations/MultiResolutionRegistrationWithFeatures/itkMultiInputMultiResolutionImageRegistrationMethodBase.h
Components/Registrations/MultiResolutionRegistrationWithFeatures/itkMultiInputMultiResolutionImageRegistrationMethodBase.hxx

Used `ModifiedTimeType` for modified time, instead of `unsigned long`, thereby fixing many Elastix/ITK5 compile errors, like this:
error C2555: 'itk::ImageSpatialObject2::GetMTime': overriding virtual function return type differs and is not covariant from 'itk::SpatialObject::GetMTime'
Related ITK commits:
@mstaring, 2012-09-24: https://github.com/InsightSoftwareConsortium/ITK/commit/cbf91c49e4e598adfc5b36e0d55c58c4dedae8d7
@dzenanz, 2019-03-29: https://github.com/InsightSoftwareConsortium/ITK/commit/0598727d390e861f70b00a4a96a9c58e26b57036

COMP: Use ModifiedTimeType instead of unsigned long

---

Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNBruteForceTree.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNStandardTreeSearch.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNbdTree.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkBinaryANNTreeSearchBase.h
Components/Registrations/MultiMetricMultiResolutionRegistration/elxMultiMetricMultiResolutionRegistration.h
Components/Transforms/SplineKernelTransform/itkElasticBodyReciprocalSplineKernelTransform2.h

Follow-up to commit 5c875097f4d309f1704072e3db68fc92751f0399, 5 April 2019:
"COMP: Added override by Clang Tidy-Fix modernize-use-override"

COMP: Added C++11 override to Components

---

CMakeLists.txt
Common/GTesting/CMakeLists.txt
Common/GTesting/itkImageMaskSpatialObject2GTest.cxx

Added (optional) GoogleTest, to be enabled by advance CMake option `ELASTIX_USE_GTEST`.
Added first (rather trivial) GTest test function, for `ImageMaskSpatialObject2`.

ENH: GTest for ImageMaskSpatialObject2

---

Testing/CI/Azure/ci.yml

Upgrade from LLVM 9.1.0 (clang-902.0.39.2) to LLVM 10.0.1 (clang-1001.0.46.3)

ENH: Upgrade azure CI from macOS-10.14 to macOS-10.13

---

Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/ANN.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_fix_rad_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_pr_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_util.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/pr_queue.h

Removed C++ `register` keywords from ANN (Approximate Nearest Neighbors library).
Fixes Clang warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]

COMP: Removed register keyword from KNN/ANN

---

Common/ImageSamplers/itkImageRandomSamplerBase.h
Common/Transforms/itkAdvancedSimilarity3DTransform.h
Common/Transforms/itkAdvancedVersorRigid3DTransform.h
Common/Transforms/itkAdvancedVersorTransform.h
Common/Transforms/itkEulerTransform.h
Common/itkNDImageBase.h
Common/itkRecursiveBSplineInterpolationWeightFunction.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNFixedRadiusTreeSearch.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNPriorityTreeSearch.h
Components/Optimizers/AdaGrad/elxAdaGrad.h
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.h
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.h
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.h
Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.h
Components/Registrations/MultiMetricMultiResolutionRegistration/itkMultiMetricMultiResolutionImageRegistrationMethod.h
Components/Registrations/MultiResolutionRegistrationWithFeatures/itkMultiInputMultiResolutionImageRegistrationMethodBase.h
Components/Transforms/AffineDTITransform/itkAffineDTI3DTransform.h
Components/Transforms/SplineKernelTransform/itkElasticBodyReciprocalSplineKernelTransform2.h
Components/Transforms/SplineKernelTransform/itkElasticBodySplineKernelTransform2.h
Components/Transforms/WeightedCombinationTransform/itkWeightedCombinationTransform.h
Core/Install/elxMacro.h

Thirteen more commits that fix compilation warnings about missing `override` specifiers.
Previous `override` fixes (pull request #136 and #137) were applied automatically by clang-tidy (modernize-use-override), but the fixes from this pull request has to be done manually, and carefully.
This pull request hopefully completes the fixes for issue #110 ("-Winconsistent-missing-override on MacOS"), submitted by Harmen Stoppels @haampie

Many manual fixes of missing override specifiers (issue #110)

---

Common/GTesting/CMakeLists.txt
Common/GTesting/itkComputeImageExtremaFilterGTest.cxx
Common/itkComputeImageExtremaFilter.hxx

Added elementary unit tests to elastix `itk::ComputeImageExtremaFilter`.
Tests both with and without `SetUseMask(true)`.
Also added a missing `#include`.

Added unit tests for ComputeImageExtremaFilter 

---

Common/ImageSamplers/itkImageSamplerBase.h

Philipp Heinrich reported a case of integer overflow, when the number of pixels passed the function `sampleContainer->Reserve` could not be represented in an `unsigned long, at
"Re: [elastix-imageregistration] Re: Elastix crashes without any notice"
https://groups.google.com/forum/?utm_source=footer#!msg/elastix-imageregistration/Q1e1b2UNIQI/ySXTCJdvAwAJ
The overflow would occur in `ImageFullSampler::GenerateData()`:
https://github.com/SuperElastix/elastix/blob/421cc17074ca06388ea71c37f1150d1d6b4601f5/Common/ImageSamplers/itkImageFullSampler.hxx#L64
This commit should fix this issue by using `std::size_t`, instead of `unsigned long`, as `TElementIdentifier` template argument of `VectorDataContainer`.

BUG: Avoid overflow, passing number of pixels to sampleContainer Reserve

---

Components/Optimizers/QuasiNewtonLBFGS/itkQuasiNewtonLBFGSOptimizer.h
Testing/itkAdvancedBSplineDeformableTransformTest.cxx
Testing/itkBSplineInterpolationDerivativeWeightFunctionTest.cxx
Testing/itkBSplineInterpolationSODerivativeWeightFunctionTest.cxx
Testing/itkBSplineInterpolationWeightFunctionTest.cxx

Fixes a few obvious compile warnings

Avoid unnecessary clamp (itkSetClampMacro) and float truncations

---

Testing/CI/Azure/ci.yml

It was agreed at today's Elastix/SuperElastix sprint that ITK4 does not need to be supported anymore.
(The aim is now to allow elastix to build with ITK5 `ITK_LEGACY_REMOVE=ON`.)

COMP: Improve speed of github azure CI build by dropping ITK4

---

Common/LineSearchOptimizers/itkMoreThuenteLineSearchOptimizer.cxx
Common/Transforms/itkBSplineSecondOrderDerivativeKernelFunction2.h
Common/itkComputePreconditionerUsingDisplacementDistribution.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Testing/itkAdvancedLinearInterpolatorTest.cxx

Replaced calls to:
vnl_math::abs
vnl_math::cuberoot
Note: this pull request does not touch calls to:
vnl_math::sqr
vnl_math::rnd
vnl_math::sgn
vnl_math::sgn0
Those functions do not seem to have an equivalent function in the Standartd C++ Library.

Replace vnl_math function calls (cuberoot, abs) by std calls

---

Common/itkComputePreconditionerUsingDisplacementDistribution.hxx
Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx
Components/Metrics/MissingStructurePenalty/itkMissingStructurePenalty.h
Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx
Components/Metrics/PolydataDummyPenalty/itkPolydataDummyPenalty.h
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Components/Transforms/AffineDTITransform/elxAffineDTITransform.hxx
Components/Transforms/AffineLogTransform/elxAffineLogTransform.hxx
Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.hxx
Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx
Components/Transforms/WeightedCombinationTransform/elxWeightedCombinationTransform.hxx

Fixed errors like this, when ITK_FUTURE_LEGACY_REMOVE is on:
> elxAdaptiveStochasticLBFGS.hxx(1573): error C2440: 'initializing': cannot convert from 'const itk::AdvancedTransform<double,2,2> *' to 'itk::SmartPointer<itk::AdvancedTransform<double,2,2>>'
Replaced `itkGetObjectMacro` calls by `itkGetModifiableObjectMacro`, fixing errors like this:
> itkPolydataDummyPenalty.h(129): error C3861: 'purposeful_error': identifier not found

COMP: Fix ITK_FUTURE_LEGACY_REMOVE constness compile errors

---

Common/CostFunctions/itkLimiterFunctionBase.h
Common/CostFunctions/itkSingleValuedPointSetToPointSetMetric.h
Common/Transforms/itkAdvancedCombinationTransform.h
Common/Transforms/itkAdvancedMatrixOffsetTransformBase.h
Common/Transforms/itkAdvancedRigid2DTransform.h
Common/Transforms/itkAdvancedRigid3DTransform.h
Common/Transforms/itkAdvancedTranslationTransform.h
Common/itkImageFileCastWriter.h
Common/itkMeshFileReaderBase.h
Common/itkMultiResolutionGaussianSmoothingPyramidImageFilter.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/CMAEvolutionStrategy/itkCMAEvolutionStrategyOptimizer.cxx
Components/Optimizers/FiniteDifferenceGradientDescent/itkFiniteDifferenceGradientDescentOptimizer.cxx
Components/Optimizers/FullSearch/itkFullSearchOptimizer.cxx
Components/Optimizers/PreconditionedGradientDescent/itkPreconditionedGradientDescentOptimizer.cxx
Components/Optimizers/StandardGradientDescent/itkGradientDescentOptimizer2.cxx
Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx
Components/Transforms/DeformationFieldTransform/itkDeformationFieldInterpolatingTransform.h
Components/Transforms/TranslationStackTransform/itkAdvancedTranslationTransform.h

To address
/home/matt/src/ITK/Modules/Core/Common/include/itkExceptionObject.h:19:2:
error: "Do not include itkExceptionObject.h directly,  include
itkMacro.h instead."
when building against ITK Git master.

COMP: Include itkMacro.h instead of itkExceptionObject.h

---

CMake/elastixExportTarget.cmake
CMakeLists.txt

Instead of CMAKE_SOURCE_DIR / CMAKE_BINARY_DIR so elastix can be used
inside other projects with add_subdirectory.

BUG: Use elastix_SOURCE_DIR / elastix_BINARY_DIR

---

Core/Main/elxParameterObject.cxx
Core/Main/elxPixelType.h

To address:
_deps/elastix_fetch-src/Core/Main/elxParameterObject.cxx:499:80: error: 'pow' is not a member of 'std'

COMP: Include header for std::pow

---

Core/Main/elastix.cxx

Added support for --extended-version command-line option, which also prints the ITK version and the compiler version.

ENH: Add command-line option "--extended-version"

---

CMakeLists.txt
Core/Install/elxMacro.h
dox/manual/manual.tex

Attempts to build shared Elastix libraries have led to various problems, including a core dump recently reported by Luisa Sanchez Brea.
Pull request #145 "Make BUILD_SHARED_LIBS do its job" by Harmen Stoppels (@haampie) was abandoned because of lack of resources at our side.
This commit prevents users from accidentally switching on the CMake option `BUILD_SHARED_LIBS` for Elastix.
Moreover, it drops support for the macro `_ELASTIX_USE_SHARED_LIBRARY`.
The manual (TeX file) is adjusted accordingly.

COMP: Explicitly disable BUILD_SHARED_LIBS

---

Components/Registrations/MultiResolutionRegistration/elxMultiResolutionRegistration.hxx
Components/Transforms/AdvancedAffineTransform/itkCenteredTransformInitializer2.hxx
Components/Transforms/TranslationTransform/itkTranslationTransformInitializer.hxx
Core/ComponentBaseClasses/elxRegistrationBase.hxx

itk::ImageMaskSpatialObject::Update() should be called on various places, when the mask image is set, to ensure that the bounding box (in world space) is up-to-date.
Fixes issue #179, "Error when using fixed mask in MultiMetricMultiResolutionRegistration", reported by Patrick Carnahan (@pcarnah).

BUG: Add missing itk::ImageMaskSpatialObject Update() calls (issue #179)

---

Core/CMakeLists.txt
Core/Main/elastix.cxx

Extended the output of the elastix command-line option "--extended-version" by adding:
* The CMake version number
* _MSC_BUILD: the revision number element of MSVC's version number
* The patch component of ITK's version number
It appeared that `ITK_VERSION_STRING` only shows the major and the minor version component, for example, "5.0". With this commit, the patch number is included, as in "5.0.1".
The CMake version number is explicitly mentioned at https://github.com/SuperElastix/elastix/releases so it seems useful to provide it through command-line option "--extended-version" as well.

STYLE: Add CMake, _MSC_BUILD, ITK_VERSION_PATCH to --extended-version

---

.editorconfig
dox/externalproject/itkTimerTest.cxx

Replaced tabs, found by Visual Studio (Find In Files...) by spaces, as requested by Marius @mstaring
Added EditorConfig file, to preserve the formatting style during future editing.

STYLE: Replace tabs by spaces

---

Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/Copyright.txt
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/License.txt
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/ReadMe.txt
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/include/ANN/ANN.h.in
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/include/ANN/ANNperf.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/include/ANN/ANNx.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/ANN.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/bd_fix_rad_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/bd_pr_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/bd_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/bd_tree.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/bd_tree.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/brute.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_dump.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_fix_rad_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_fix_rad_search.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_pr_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_pr_search.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_search.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_split.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_split.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_tree.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_tree.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_util.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_util.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/perf.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/pr_queue.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/pr_queue_k.h

Extracted the source files from "include" and "source", from
https://www.cs.umd.edu/~mount/ANN/Files/1.1.2/ann_1.1.2.tar.gz
Renamed ANN.h (from include/ANN) to ANN.h.in, and adjusted to support the elastix CMake option for `ANN_ALLOW_SELF_MATCH`.
Updated Copyright.txt, and added License.txt and ReadMe.txt
Removed the `register` keywords again (which are deprecated with C++11), as in commit "COMP: Removed register keyword from KNN/ANN", April 25, 2019, 61ea010
Added C++11 `override` specifiers again, as in commit "COMP: Added override by Clang Tidy-Fix modernize-use-override", 5 April 2019, 5c87509
Solved -Wunused-const-variable warning about `EPSILON` again, as in commit "COMP: solving clang warning" by Marius @mstaring, Feb 11, 2014, 5ca641b

ENH: Upgrade ANN library from 1.1 (2005) to 1.1.2 (2010)

---

Core/Install/elxBaseComponent.h
dox/ITKCompilationOptions.txt

Increased __ELASTIX_VERSION and adjusted ITKCompilationOptions.txt
Note: the link to the manual (in CONTRIBUTING.md) should still be updated, once a new manual is available.

ENH: Bump elastix version from 4.9.0 to 5.0.0

---

Common/TypeList.h

Add a workaround for Visual Studio < 2017, to avoid VS2015 compile errors when building with OpenCL, reported by Denis (@dpshamonin):
> TypeList.h(539): error C2059: syntax error: 'template'
Partially reverts "COMP: fixed the VisitDimension OpenCL compilation issues" commit c9261630ee05a4ec72d8532151fedd79e3954258 (@dpshamonin Mar 5, 2019).

COMP: Fix VS2015 TypeList.h(539): error C2059: syntax error: 'template'

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Adapted from https://www.contributor-covenant.org/version/1/4/code-of-conduct

DOC: Add code of conduct (issue #198 -- adopt code of conduct)

---

dox/manual/manual.tex

ITK5 no longer supports the `int` value 0 as initial value of `SmartPointer`, so it is replaced by `nullptr` in the code examples.
`TRANSFORMIX::TransformImage` has an extra output_path parameter that was missing.
Placed `ELASTIX` and `TRANSFORMIX` on the stack, instead of the heap, getting rid of unnecessary code to explicitly clean up memory.

DOC: Fix compilation of code examples "Using elastix as a library"

---

Core/Configuration/elxConfiguration.cxx
Core/Configuration/elxConfiguration.h
Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixMain.h
Core/Kernel/elxTransformixMain.cxx
Core/Kernel/elxTransformixMain.h

Changed signature of `ElastixMain`, `TransformixMain`, and `Configuration` member functions, to pass maps by `const` instead of by non-const reference.
Improved code readability and type safety.

STYLE: Add const to maps passed by ref to ElastixMain member functions

---

Core/Configuration/elxConfiguration.cxx
Core/Configuration/elxConfiguration.h

Improved `GetCommandLineArgument`:
- Removed `const` from its return type, to allow fast (noexcept) move semantics.
- Removed a `map::count(key)` call.
- Removed conversion between `std::string` and `const char*` (`c_str()`).
Simplified `SetCommandLineArgument` by using `map::operator[]`.

PERF: Improve elastix::Configuration Get and Set CommandLineArgument

---

Core/Main/elxElastixFilter.h
Core/Main/elxParameterObject.h
Core/Main/elxTransformixFilter.h

The first argument to itkTypeMacro is used to generate the output of the
GetClassName() method -- this should be the specific class name instead
of Self.

BUG: ParameterObject argument for itkTypeMacro

---

dox/manual/manual.tex

The current manual instructs the user to use `git checkout v5.0.0` to get the latest release. The tags for this repository do not include the `v` prefix. The correct commmand should be `git checkout 5.0.0`.

STYLE : Updated manual to correctly describe checkout of 5.0.0 branch

---

Common/ParameterFileParser/itkParameterFileParser.cxx
Common/ParameterFileParser/itkParameterFileParser.h
Common/xout/xoutbase.h
Common/xout/xoutbase.hxx
Common/xout/xoutcell.hxx
Core/Kernel/elxElastixBase.h
Core/Main/elastix.cxx
Core/Main/elastix.h
Core/Main/elastixlib.cxx
Core/Main/elastixlib.h
Core/Main/transformix.cxx
Core/Main/transformixlib.cxx
Core/Main/transformixlib.h

Fix  various Visual Studio 2017 Code Analysis warnings, Clang Tidy warnings and other style issues encountered when building "elastix.cxx", "elastixlib.cxx", and "itkParameterFileParser.cxx".

Fix various VS2017 /analyze and Clang Tidy warnings in Core and Common

---

CMakeLists.txt
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Configuration/elxConfiguration.cxx
Core/Install/elxBaseComponent.cxx
Core/Install/elxBaseComponent.h
Core/Kernel/elxElastixBase.cxx
Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixTemplate.hxx
Core/Kernel/elxTransformixMain.cxx
Core/Main/elastixlib.cxx
Core/elxProgressCommand.cxx
Core/elxProgressCommand.h

Replaced `_ELASTIX_BUILD_LIBRARY` preprocessor definition by static member function, `BaseComponent::IsElastixLibrary()`.
Anticipates sharing the intermediate binary object files between the Elastix executable and the Elastix library, possibly building them within the same project, or the same (Visual Studio) solution.

STYLE: Replace _ELASTIX_BUILD_LIBRARY by BaseComponent::IsElastixLibrary

---

.gitignore

Having cmake* in there stopped Gokhan Gunay from adding his CMakeLists file to pull request #236 (Addition of PointToSurface metric).

COMP: Remove cmake* from .gitignore

---

Core/Main/elastix.h

To address:
_deps/elastix_fetch-src/Core/Main/elastix.h: In function ‘std::string
GetCurrentDateAndTime()’:
_deps/elastix_fetch-src/Core/Main/elastix.h:99:47: error: cannot convert
‘const tm’ to ‘int’ in initialization
const std::tm localTimeValue{ *localTimePtr };
with GCC 4.8.

COMP: elastix.h localTimeValue initialization

---

Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Common/Transforms/itkAdvancedCombinationTransform.hxx
Common/Transforms/itkBSplineSecondOrderDerivativeKernelFunction2.h
Components/Transforms/SplineKernelTransform/itkKernelTransform2.hxx

Fixes six Visual C++ 2019 Warning level 4 warnings, saying:
> warning C4702: unreachable code
These warnings occurred in Common/Transforms and Components/Transforms.

COMP: Remove unreachable code from Transforms

---

Core/Install/elxBaseComponent.cxx
Core/Install/elxBaseComponent.h
Core/Main/elastix.cxx
Core/Main/elastixlib.cxx
Core/Main/transformix.cxx

Kasper Marstal reported yesterday via direct messaging that the introduction of `IsElastixLibrary()`, pull request #231, commit 64ced5942604b055e3a11ee235af186811bf11dc (March 2, 2020, "Replace _ELASTIX_BUILD_LIBRARY by BaseComponent::IsElastixLibrary"), did break SimpleElastix.  SimpleElastix depends on the library interface, while it does not construct an `elastix::ELASTIX` library object.
The most elegant and reliable fix appears to be flipping the default value returned by `IsElastixLibrary()`, from `false` to `true`, and then ensuring that the value is set to `false` at the start of each run of the executable.

ENH: Replace InitializeElastixLibrary() by InitializeElastixExecutable()

---

Core/Main/elastixlib.cxx
Core/Main/transformixlib.cxx

Replaced calls to "Get" member functions by the corresponding "GetModifiable" member functions.
Follow-up to commit aa4bb6518441be05e8ac787bb635838d7a8d40dd, January 11 2019, COMP: Allow building with ITK_FUTURE_LEGACY_REMOVE=ON, fixing issue #85
Related to elastix issue #85: "Build with ITK_FUTURE_LEGACY_REMOVE=ON", from Dženan Zukić (@dzenanz).

COMP: Allow build lib.cxx files w/ ITK_FUTURE_LEGACY_REMOVE (issue #85)

---

Common/GTesting/itkComputeImageExtremaFilterGTest.cxx

Fixes various compilation errors reported at https://dev.azure.com/kaspermarstal/d9c40921-2d83-43b7-b98b-be691988c03a/_apis/build/builds/756/logs/25 including:
> itkComputeImageExtremaFilterGTest.cxx:29:54: error: expected unqualified-id before ; token
> itkComputeImageExtremaFilterGTest.cxx:226:83: error: no type named "New"

COMP: Fix Clang, GCC compile errors in ComputeImageExtremaFilterGTest

---

CMake/elastixExportTarget.cmake
CMakeLists.txt
Core/CMakeLists.txt
Core/Main/GTesting/CMakeLists.txt
ElastixConfig.cmake.in
Testing/CI/Azure/ci.yml
Testing/CMakeLists.txt
Testing/Dashboard/elxDashboard_LKEB_win10-64_VS2015.cmake

Also enabled GoogleTest on the CI (Azure pipelines).

ENH: Allow building exe and lib of elastix and transformix together

---

Core/Main/elastix.h

Allows these functions to be called from an executable that links against the elastix library.

COMP: Declare ConvertSecondsToDHMS and GetCurrentDateAndTime inline

---

Common/OpenCL/ITKimprovements/itkOpenCLLogger.cxx
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Common/Transforms/itkAdvancedCombinationTransform.h
Common/Transforms/itkAdvancedCombinationTransform.hxx
Common/Transforms/itkAdvancedIdentityTransform.h
Common/Transforms/itkAdvancedMatrixOffsetTransformBase.h
Common/Transforms/itkAdvancedTranslationTransform.h
Components/Optimizers/RegularStepGradientDescent/elxRegularStepGradientDescent.hxx
Components/Optimizers/SimultaneousPerturbation/elxSimultaneousPerturbation.h
Components/Optimizers/SimultaneousPerturbation/elxSimultaneousPerturbation.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Testing/CI/Azure/ci.yml

To address:
In file included from _deps/elastix_fetch-src/Core/ComponentBaseClasses/elxTransformBase.h:384:0,
from _deps/elastix_fetch-src/Core/Kernel/elxElastixTemplate.h:39,
from _deps/elastix_fetch-src/Core/Install/elxIncludes.h:39,
from _deps/elastix_fetch-src/Components/FixedImagePyramids/FixedRecursivePyramid/elxFixedRecursivePyramid.h:21,
from _deps/elastix_fetch-src/Components/FixedImagePyramids/FixedRecursivePyramid/elxFixedRecursivePyramid.cxx:19:
_deps/elastix_fetch-src/Core/ComponentBaseClasses/elxTransformBase.hxx: In member function ‘void itk::PixelTypeChangeCommand<T>::Execute(itk::Object*, const itk::EventObject&)’:
_deps/elastix_fetch-src/Core/ComponentBaseClasses/elxTransformBase.hxx:75:55: error: ‘VECTOR’ is not a member of ‘itk::ImageIOBase’ …

COMP: Use ITK 5.1.0 strongly typed enums in elxTransformBase

---

dox/manual/manual.tex

The parameter name in the manual was not according to the implementation of elastix. Issue encountered by @ViktorvdValk

DOC: Fix "AdvancedMeanSquares" parameter name

---

Core/Configuration/elxConfiguration.cxx
Core/Main/transformixlib.cxx

Include guards are only useful for files that are included by `#include`. (In practice: *.h and *.hxx files)

STYLE: Remove include guards from *.cxx files

---

Common/OpenCL/Factories/itkGPUObjectFactoryBase.h
Common/OpenCL/Filters/itkGPUAdvancedBSplineDeformableTransform.h
Common/OpenCL/Filters/itkGPUAdvancedCombinationTransformCopier.h
Common/OpenCL/Filters/itkGPUBSplineBaseTransform.h
Common/OpenCL/Filters/itkGPUBSplineDecompositionImageFilter.h
Common/OpenCL/Filters/itkGPUBSplineInterpolateImageFunction.h
Common/OpenCL/Filters/itkGPUBSplineTransform.h
Common/OpenCL/Filters/itkGPUCastImageFilter.h
Common/OpenCL/Filters/itkGPUCompositeTransformBase.h
Common/OpenCL/Filters/itkGPUIdentityTransform.h
Common/OpenCL/Filters/itkGPUInterpolateImageFunction.h
Common/OpenCL/Filters/itkGPUInterpolatorCopier.h
Common/OpenCL/Filters/itkGPULinearInterpolateImageFunction.h
Common/OpenCL/Filters/itkGPUMatrixOffsetTransformBase.h
Common/OpenCL/Filters/itkGPUNearestNeighborInterpolateImageFunction.h
Common/OpenCL/Filters/itkGPURecursiveGaussianImageFilter.h
Common/OpenCL/Filters/itkGPUResampleImageFilter.h
Common/OpenCL/Filters/itkGPUShrinkImageFilter.h
Common/OpenCL/Filters/itkGPUTransformCopier.h
Common/OpenCL/Filters/itkGPUTranslationTransformBase.h
Common/OpenCL/ITKimprovements/itkGPUDataManager.h
Common/OpenCL/ITKimprovements/itkGPUImage.h
Common/OpenCL/ITKimprovements/itkGPUImageDataManager.h
Common/OpenCL/ITKimprovements/itkOpenCLContext.h
Common/OpenCL/ITKimprovements/itkOpenCLKernelManager.h
Common/OpenCL/ITKimprovements/itkOpenCLLogger.h
Common/OpenCL/ITKimprovements/itkOpenCLMacro.h

Fixes warnings from Common/OpenCL when ELASTIX_USE_OPENCL=ON, like:
> In file included from _deps/elx-src/Common/OpenCL/ITKimprovements/itkGPUDataManager.cxx:35:
> _deps/elx-src/Common/OpenCL/ITKimprovements/itkGPUDataManager.h:154:16: warning: 'PrintSelf' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
virtual void PrintSelf( std::ostream & os, Indent indent ) const;
https://github.com/InsightSoftwareConsortium/ITKElastix/pull/58/checks?check_run_id=1096122147#step:4:2219
Follow-up to elastix issue #110 ("-Winconsistent-missing-override on MacOS") by Harmen Stoppels

COMP: Apply Clang Tidy-Fix modernize-use-override to Common/OpenCL

---

Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixMain.h
Core/Kernel/elxTransformixMain.cxx

Moved the `#include "itkOpenCLContext.h"` from elxElastixMain.h to elxElastixMain.cxx and elxTransformixMain.cxx, hoping to ease fixing the error:
> /work/_skbuild/linux-x86_64-3.5/cmake-build/_deps/elx-src/Core/Kernel/elxElastixMain.h:33:10: fatal error: 'itkOpenCLContext.h' file not found
at https://github.com/InsightSoftwareConsortium/ITKElastix/pull/58/checks?check_run_id=1096122268#step:4:2894
(Pull request https://github.com/InsightSoftwareConsortium/ITKElastix/pull/58 "ENH: Switch to latest version of SuperElastix/elastix (using ITK 5.1.1)")

COMP: Move #include "itkOpenCLContext.h" from elxElastixMain.h to elxElastixMain.cxx and elxTransformixMain.cxx

---

Components/Transforms/SplineKernelTransform/itkKernelTransform2.hxx

Fixed warnings from `vnl_matrix_fixed::operator const vnl_matrix_ref<T>()` saying:
> Implicit cast conversion is dangerous.\nUSE: .as_vector() or .as_ref() member function for clarity.
These warnings were introduced with ITK commit "Merge branch 'upstream-vnl' into UpdateVNL-11-17-19",
https://github.com/InsightSoftwareConsortium/ITK/commit/b8b821825c9d4104a9aef21d2b13375c8cfa3737

COMP: Fix vnl_matrix_fixed "Implicit cast conversion" warnings

---

Core/Main/elxParameterObject.h

To address:
d:\a\1\build\_deps\elastix_fetch-src\core\main\elxParameterObject.h(67): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data

COMP: elxParameterObject size_t to unsigned int

---

CMakeLists.txt

Fixed the warnings reported by Jean-Christophe Fillion-Robin, issue #21 (August 8, 2017!):
> The OLD behavior for policy CMP0033 will be removed from a future version of CMake.
> The OLD behavior for policy CMP0007 will be removed from a future version of CMake.
Removed `export_library_dependencies` call, which is no longer supported now. ("The export_library_dependencies command should not be called; see CMP0033")

COMP: Fix CMake 3.x warnings policy CMP0033 and CMP0007 (issue #21)

---

CMakeLists.txt

Aims to fix the following CMake Warning from https://open.cdash.org/build/6758579/configure Build: InsightSoftwareConsortium/ITKElastix-macos-10.15--refs/pull/60/merge
> CMake Warning (dev) at /Users/runner/work/ITKElastix/build/_deps/elx-src/CMakeLists.txt:37 (option):
>  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
> --help-policy CMP0077" for policy details.  Use the cmake_policy command to
> set the policy and suppress this warning.
>
> For compatibility with older versions of CMake, option is clearing the
> normal variable 'BUILD_SHARED_LIBS'.
Follow-up to commit bb902f795244a66ab830775b1e9ad2ad026bd233, "COMP: Explicitly disable BUILD_SHARED_LIBS", September 11, 2019.
Related to:
- pull request #184 "COMP: Explicitly disable BUILD_SHARED_LIBS"
- pull …

COMP: No longer add BUILD_SHARED_LIBS option

---

Common/Transforms/itkAdvancedImageMomentsCalculator.hxx

Addresses:
> itkAdvancedImageMomentsCalculator.hxx: warning: 'vnl_matrix_fixed::operator const vnl_matrix_ref<T>() const ' is deprecated: Implicit cast conversion is dangerous.
At https://open.cdash.org/viewBuildError.php?type=1&buildid=6758978
Site: GitHubActions
Build Name: InsightSoftwareConsortium/ITKElastix-ubuntu-18.04--refs/pull/60/merge
Build Time: 2020-09-12 22:46:31
Follow-up to pull request #280, "Fix vnl_matrix_fixed "Implicit cast conversion" warnings", commit 69bfa5ac64f05c54fcda14865713a3ad05185db3, 11 Sep 2020

COMP: Fix implicit conversion warnings itkAdvancedImageMomentsCalculator

---

Components/Optimizers/PreconditionedGradientDescent/elxPreconditionedGradientDescent.hxx
Components/Optimizers/PreconditionedGradientDescent/itkAdaptiveStochasticPreconditionedGradientDescentOptimizer.cxx
Components/Optimizers/PreconditionedGradientDescent/itkPreconditionedGradientDescentOptimizer.cxx

Replaced the four `vnl_math_max` calls in the PreconditionedGradientDescent component by corresponding `std::max` calls.
Addresses issue #234, "Probably a bug: vnl_math_max in elxPreconditionedGradientDescent", by Ibraheem Al-Dhamari (@idhamari).
Note that PreconditionedGradientDescent is switched off by default, as it depends on the SuiteSparse library (which may not be installed).
Discussed with Marius Staring (@mstaring).

COMP: Replace vnl_math_max in PreconditionedGradientDescent (issue #234)

---

Testing/itkTestOutputWindow.h

Follow-up to elastix issue #110 ("-Winconsistent-missing-override on MacOS") by Harmen Stoppels

COMP: Clang Tidy-Fix modernize-use-override at itkTestOutputWindow.h

---

Core/Install/elxBaseComponent.cxx
Core/Install/elxBaseComponent.h

- Declare ComponentLabel getter and setter non-virtual (In C++, the `virtual` keyword should only be used when it is really useful!)
- Declare ConvertSecondsToDHMS `static`, as it does not use `this`.
- Default default-constructor and destructor (C++11).
- Use ITK_DISALLOW_COPY_AND_ASSIGN instead of "purposely not implemented" (ITK 5 coding convention)
- Move `#include`'s from BaseComponent.h to BaseComponent.cxx (to reduce compilation times)

STYLE: Modernize code in BaseComponent.h

---

Core/Install/elxBaseComponentSE.h
Core/Install/elxBaseComponentSE.hxx

- Declared getter and setter non-virtual
- Defaulted default-constructor and destructor (C++11).
- Replaced "purposely not implemented" by a `ITK_DISALLOW_COPY_AND_ASSIGN` call (ITK 5 coding convention)
- Made Configuration types independent of TElastix
- #include's exactly those ITK header files that are being used

STYLE: Modernize code of BaseComponentSE

---

Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx

- Used `using` for typedef's from Superclass
- Defaulted default-constructor and destructor (C++11).
- Replaced "purposely not implemented" by `ITK_DISALLOW_COPY_AND_ASSIGN` calls
- Made three protected data members `private`
- Replaced a raw pointer by `std::unique_ptr`
- Did clean up the #include's.
- Used `const auto` for variables that are initialized by `New()`
- Replaced old for-loops in `AutomaticScalesEstimation` and `AutomaticScalesEstimationStackTransform` by modern C++11 range-based for-loops.

STYLE: Modernize code of elxTransformBase

---

CMake/elastixVersion.cmake
CMakeLists.txt
Core/CMakeLists.txt
Core/Install/elxBaseComponent.h
Core/Kernel/elxElastixBase.cxx
Core/Main/elastix.cxx
Core/Main/transformix.cxx
Core/elxVersionMacros.h.in

And added `GetElastixVersionString()` helper function.
(Discussed with Marius Staring at internal superelastix.slack.com channel #elastix)

ENH: Replace __ELASTIX_VERSION by ELASTIX_VERSION_MAJOR/MINOR/PATCH

---

Core/Install/elxBaseComponentSE.hxx

The cast in `dynamic_cast< RegistrationPointer >( m_Elastix->GetElxRegistrationBase() )` appeared unnecessary, as the return type of this `GetElxRegistrationBase()` call, `elastix::RegistrationBase<elastix::ElastixTemplate<TFixedImage, TMovingImage>> *` is just the same as `RegistrationPointer`.
Also improved const-correctness, added C++11 `auto`, and increased readability by comparing pointers explicitly to `nullptr`.

STYLE: Remove unnecessary dynamic_cast from BaseComponentSE::SetElastix

---

Core/CMakeLists.txt

Aims to fix issue #305 "Elastix 5.0.1 binaries (elastix and transformix) not installed by default cmake build", reported by Ben Darwin (@bcdarwin).

BUG: Add elastix_exe and transformix_exe to CMake install (issue #305)

---

Core/ComponentBaseClasses/elxInterpolatorBase.h
Core/ComponentBaseClasses/elxResampleInterpolatorBase.h
Core/ComponentBaseClasses/elxResamplerBase.h
Core/ComponentBaseClasses/elxTransformBase.h
Core/Kernel/elxElastixBase.h
Core/Kernel/elxElastixTemplate.h

Reduces unnecessary template argument type dependencies (as `ElastixTemplate` is a template, while `ElastixBase` is not).
Aims to eventually reduce compilation duration.

STYLE: Move CoordRepType typedef from ElastixTemplate<> to ElastixBase

---

Components/FixedImagePyramids/FixedShrinkingPyramid/CMakeLists.txt
Components/Interpolators/BSplineInterpolatorFloat/CMakeLists.txt
Components/Interpolators/NearestNeighborInterpolator/CMakeLists.txt
Components/Interpolators/RayCastInterpolator/CMakeLists.txt
Components/Metrics/AdvancedKappaStatistic/CMakeLists.txt
Components/Metrics/DisplacementMagnitudePenalty/CMakeLists.txt
Components/Metrics/GradientDifference/CMakeLists.txt
Components/Metrics/MissingStructurePenalty/CMakeLists.txt
Components/Metrics/NormalizedGradientCorrelation/CMakeLists.txt
Components/Metrics/PatternIntensity/CMakeLists.txt
Components/Metrics/PolydataDummyPenalty/CMakeLists.txt
Components/Metrics/StatisticalShapePenalty/CMakeLists.txt
Components/MovingImagePyramids/MovingShrinkingPyramid/CMakeLists.txt
Components/Optimizers/AdaGrad/CMakeLists.txt
Components/Optimizers/AdaptiveStochasticLBFGS/CMakeLists.txt
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/CMakeLists.txt
Components/Optimizers/CMAEvolutionStrategy/CMakeLists.txt
Components/Optimizers/ConjugateGradientFRPR/CMakeLists.txt
Components/Optimizers/RSGDEachParameterApart/CMakeLists.txt
Components/Optimizers/Simplex/CMakeLists.txt
Components/Optimizers/SimultaneousPerturbation/CMakeLists.txt
Components/ResampleInterpolators/BSplineResampleInterpolatorFloat/CMakeLists.txt
Components/ResampleInterpolators/LinearResampleInterpolator/CMakeLists.txt
Components/ResampleInterpolators/NearestNeighborResampleInterpolator/CMakeLists.txt
Components/ResampleInterpolators/RayCastResampleInterpolator/CMakeLists.txt
Components/Transforms/AffineDTITransform/CMakeLists.txt
Components/Transforms/AffineLogTransform/CMakeLists.txt
Components/Transforms/MultiBSplineTransformWithNormal/CMakeLists.txt
Components/Transforms/SimilarityTransform/CMakeLists.txt
Components/Transforms/WeightedCombinationTransform/CMakeLists.txt

Removed default "OFF" for `ADD_ELXCOMPONENT` calls of 27 components.
Note that Optimizers/PreconditionedGradientDescent is still OFF by default because of its SuiteSparse library dependency.
Transforms/BSplineDeformableTransformWithDiffusion also remained OFF by default.

ENH: Enable almost all components by default

---

Common/Transforms/itkRecursiveBSplineTransform.hxx
Common/Transforms/itkRecursiveBSplineTransformImplementation.h

Fix const-correctness of last parameter of static `RecursiveBSplineTransformImplementation` member functions `GetJacobianOfSpatialJacobian` and `GetJacobianOfSpatialHessian` (a pointer to InternalFloatType).

STYLE: Add const RecursiveBSplineTransformImplementation::GetJacobianOf

---

Core/Kernel/elxElastixBase.h

Removed `#include <itkCostFunction.h>` and then simply defined `ElastixBase::CoordRepType` as `double` (which is the same type as `itk::CostFunction::ParametersValueType` anyway).
Aims to fix:
> _deps/elx-src/Core/Kernel/elxElastixBase.h:39:10: fatal error: 'itkCostFunction.h' file not found
itkElastixRegistrationMethodTest.cxx
At https://open.cdash.org/viewBuildError.php?buildid=6806022
ITKElastix pull request https://github.com/InsightSoftwareConsortium/ITKElastix/pull/66

COMP: Quick-fix ITKElastix error: 'itkCostFunction.h' file not found

---

Core/Kernel/elxElastixTemplate.h

`ElastixTemplate<TFixedImage, TMovingImage>` appears to be used only as a "leaf class" (not a base class). So it appears not useful to declare any of the member functions that it introduces as `virtual`.
For the sake of clarity, this commit also makes all of its `protected` members `private`.

STYLE: Declare ElastixTemplate `final` and remove `virtual` keywords

---

Core/Kernel/elxElastixBase.h

The `virtual` keyword should only be used for member functions that are meant to be overridden in a derived class.

Remove virtual from ElastixBase member functions 

---

Core/Kernel/elxElastixBase.cxx
Core/Kernel/elxElastixBase.h
Core/Kernel/elxElastixTemplate.h
Core/Kernel/elxElastixTemplate.hxx

Aims to reduce "template code bloat" during compilation, and increase compilation speed.

STYLE: Make itk::Object base class of ElastixBase, move data from ElastixTemplate to ElastixBase

---

Common/xout/xoutsimple.hxx

Aims to fix ITKElastix Ubuntu build-linux-python-packages error:
> _deps/elx-src/Common/xout/xoutsimple.hxx:98:3: error: prototype for ‘const typename xoutlibrary::xoutsimple<charT, traits>::XStreamMapType& xoutlibrary::xoutsimple<charT, traits>::GetXOutputs()’ does not match any in class ‘xoutlibrary::xoutsimple<charT, traits>’
https://github.com/N-Dekker/ITKElastix/runs/1263271436#step:5:1863

COMP: Trailing return type (auto) for xoutsimple GetXOutputs/GetCOutputs

---

Core/ComponentBaseClasses/elxTransformBase.hxx

When the name of the initial transform is not "NoInitialTransform", and it cannot be interpreted as an index value (unsigned integer), the Elastix library should just assume that it is the file name of the transform file, and read it, in `TransformBase::ReadFromFile()`.
The elastix library and the elastix executable should deal with this in the same way.
As discussed with @ViktorvdValk and Marius @mstaring .

ENH: Elastix library should read the initial transform from file

---

Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixMain.h
Core/Main/elastixlib.cxx
Core/Main/elxElastixFilter.hxx
Core/Main/elxTransformixFilter.hxx
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.hxx
Core/Main/transformixlib.cxx

Implements the "core part" of issue #297, "Feature Request: Allow closing log file in library"
ITKElastix issue https://github.com/InsightSoftwareConsortium/ITKElastix/issues/61 "Is the log file really closed?"

BUG: Close output streams at the end of GenerateData()

---

Core/Main/itkTransformixFilter.h
Core/Main/itkTransformixFilter.hxx
Testing/CMakeLists.txt
Testing/itkTransformixFilterTest.cxx

Improvements to help with functional Python interface.
GetOutput has indexed interface.
"MovingImage" is the required, first indexed input
("TransformParameterObject") is the second.

ENH: Better indexed inputs and output support in itk::TransformixFilter

---

Core/Kernel/elxElastixMain.cxx

Worked around a GCC 4.8.2 compile error on ITKElastix build, reported by Matt McCormick, issue #331 (xout on `develop` branch do not build on Linux / GCC 4.8):
> _deps/elx-src/Core/Kernel/elxElastixMain.cxx: In destructor ‘elastix::xoutManager::Guard::~Guard()’:
> _deps/elx-src/Core/Kernel/elxElastixMain.cxx:146:10: error: use of deleted function ‘{anonymous}::Data& {anonymous}::Data::operator=({anonymous}::Data&&)’
...
> /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’

COMP: Avoid GCC4 error xoutManager "use of deleted function", issue #331

---

Core/CMakeLists.txt

Fixes issue #327 (Linking error when trying to build project with elastix 5.0.1), as suggested by Konstantinos Ntatsis (@ntatsisk).

COMP: Fix CMake variable ELASTIX_LIBRARIES (issue #327)

---

Common/LineSearchOptimizers/itkMoreThuenteLineSearchOptimizer.h
Components/Optimizers/ConjugateGradient/itkGenericConjugateGradientOptimizer.h
Core/Install/elxBaseComponent.cxx
Core/Install/elxComponentLoader.h
Core/Main/elastix.h
Core/elxProgressCommand.h

and also removed two assignments that appeared unnecessary.

Remove virtual keywords to fix Clang "Call bypasses virtual dispatch" warnings 

---

Common/CostFunctions/itkScaledSingleValuedCostFunction.cxx
Common/LineSearchOptimizers/itkLineSearchOptimizer.cxx
Common/LineSearchOptimizers/itkMoreThuenteLineSearchOptimizer.cxx
Common/MevisDicomTiff/itkUseMevisDicomTiff.cxx
Common/ParameterFileParser/itkParameterFileParser.cxx
Common/itkScaledSingleValuedNonLinearOptimizer.cxx
Common/xout/xoutmain.cxx
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNBinaryTreeCreator.cxx
Components/Optimizers/AdaGrad/itkAdaptiveStepsizeOptimizer.cxx
Components/Optimizers/AdaptiveStochasticLBFGS/itkAdaptiveStochasticLBFGSOptimizer.cxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkAdaptiveStochasticVarianceReducedGradientOptimizer.cxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStandardStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/CMAEvolutionStrategy/itkCMAEvolutionStrategyOptimizer.cxx
Components/Optimizers/ConjugateGradient/itkGenericConjugateGradientOptimizer.cxx
Components/Optimizers/FiniteDifferenceGradientDescent/itkFiniteDifferenceGradientDescentOptimizer.cxx
Components/Optimizers/FullSearch/itkFullSearchOptimizer.cxx
Components/Optimizers/PreconditionedGradientDescent/itkAdaptiveStochasticPreconditionedGradientDescentOptimizer.cxx
Components/Optimizers/PreconditionedGradientDescent/itkPreconditionedGradientDescentOptimizer.cxx
Components/Optimizers/PreconditionedGradientDescent/itkStochasticPreconditionedGradientDescentOptimizer.cxx
Components/Optimizers/PreconditionedStochasticGradientDescent/itkPreconditionedASGDOptimizer.cxx
Components/Optimizers/QuasiNewtonLBFGS/itkQuasiNewtonLBFGSOptimizer.cxx
Components/Optimizers/RSGDEachParameterApart/itkRSGDEachParameterApartBaseOptimizer.cxx
Components/Optimizers/RSGDEachParameterApart/itkRSGDEachParameterApartOptimizer.cxx
Components/Optimizers/StandardGradientDescent/itkStandardGradientDescentOptimizer.cxx
Core/Install/elxComponentDatabase.cxx
Core/Install/elxComponentLoader.cxx
Core/Main/elxParameterObject.cxx

Include guards (like `#define FileName_h`) are intended to avoid the problem of double inclusion: https://en.wikipedia.org/wiki/Include_guard
They should only be used in header files (*.h, *.hxx).

STYLE: Remove "include guards" from cxx files

---

Core/Main/GTesting/ElastixFilterGTest.cxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

It appears unnecessary to specify "FixedImageDimension" and "MovingImageDimension" to `itkElastixRegistrationMethod`and `ElastixFilter`. As was mentioned during the internal weekly Elastix project sprint.

STYLE: No longer specify Fixed/Moving ImageDimension parameters in GTest

---

Core/ComponentBaseClasses/elxTransformBase.h

For the obvious reasons: `private` members are easier to maintain than `public` members, and the `virtual` keyword should only be used for member functions that are meant to be overridden in a derived class.

Make TransformBase member functions private and non-virtual

---

Core/Main/elastixlib.cxx
Core/Main/elastixlib.h
Core/Main/transformixlib.cxx
Core/Main/transformixlib.h

Added `const` keywords to the declarations of `ELASTIX::GetTransformParameterMap(void)` and `ELASTIX::GetTransformParameterMapList(void)`. These two member functions do not modify the state of an `ELASTIX` library object in any way.
See also C++ Core Guidelines (August 3, 2020) "Con.2: By default, make member functions const", https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rconst-fct
Also added const overloads of `GetResultImage()` to ELASTIX and TRANSFORMIX library classes.

STYLE: Add const to ELASTIX and TRANSFORMIX member functions

---

Core/Kernel/elxElastixBase.cxx
Core/Main/elastix.cxx
Core/Main/elxElastixFilter.hxx
Core/Main/elxTransformixFilter.hxx
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.hxx
Core/Main/transformix.cxx
Testing/itkCommandLineArgumentParser.cxx

Improved code readability and simplicity by using `std` member function `back()`.

STYLE: Replace `v[v.size() - 1]` by `v.back()`, in elastix Core

---

Core/Install/elxComponentLoader.cxx
Core/Install/elxComponentLoader.h
Core/Kernel/elxElastixMain.cxx

Removed `argv0` parameter from `ComponentLoader::LoadComponents`, as it is not used anymore. No longer passed a dangling pointer as `argv0` argument, fixing a Clang warning, reported by Matt McCormick:
> _deps/elx-src/Core/Kernel/elxElastixMain.cxx:791:7: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
At build "InsightSoftwareConsortium/ITKElastix-macos-10.15--refs/heads/transformix_extras"
https://open.cdash.org/viewBuildError.php?type=1&buildid=6869971
Thereby, fixed issue #355: ElastixMain LoadComponents - Clang warning "dangling-gsl"
Declared `ComponentLoader::LoadComponents` non-virtual, as it was not overridden anyway. Following C++ Core Guidelines (August 3, 2020), "C.132: Don't make a function virtual without reason", …

COMP: Fix  Clang dangling-gsl warning in LoadComponents (issue #355)

---

Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Install/elxBaseComponent.h

Cleaning up the code, preparing to extend `TransformBase::WriteToFile(const ParametersType &)` to support other file formats (TFM, HDF5)

TransformBase style improvements, mostly regarding WriteToFile(const ParametersType &)

---

Common/CostFunctions/itkScaledSingleValuedCostFunction.cxx
Common/LineSearchOptimizers/itkLineSearchOptimizer.cxx
Common/LineSearchOptimizers/itkMoreThuenteLineSearchOptimizer.cxx
Common/MevisDicomTiff/itkMevisDicomTiffImageIOFactory.cxx
Common/ParameterFileParser/itkParameterFileParser.cxx
Common/ParameterFileParser/itkParameterMapInterface.cxx
Common/itkScaledSingleValuedNonLinearOptimizer.cxx
Components/Optimizers/AdaGrad/itkAdaptiveStepsizeOptimizer.cxx
Components/Optimizers/AdaptiveStochasticGradientDescent/itkAdaptiveStochasticGradientDescentOptimizer.cxx
Components/Optimizers/AdaptiveStochasticLBFGS/itkAdaptiveStochasticLBFGSOptimizer.cxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkAdaptiveStochasticVarianceReducedGradientOptimizer.cxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStandardStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/ConjugateGradient/itkGenericConjugateGradientOptimizer.cxx
Components/Optimizers/FiniteDifferenceGradientDescent/itkFiniteDifferenceGradientDescentOptimizer.cxx
Components/Optimizers/FullSearch/itkFullSearchOptimizer.cxx
Components/Optimizers/PreconditionedGradientDescent/itkAdaptiveStochasticPreconditionedGradientDescentOptimizer.cxx
Components/Optimizers/PreconditionedGradientDescent/itkPreconditionedGradientDescentOptimizer.cxx
Components/Optimizers/PreconditionedGradientDescent/itkStochasticPreconditionedGradientDescentOptimizer.cxx
Components/Optimizers/PreconditionedStochasticGradientDescent/itkPreconditionedASGDOptimizer.cxx
Components/Optimizers/RSGDEachParameterApart/itkRSGDEachParameterApartBaseOptimizer.cxx
Components/Optimizers/RSGDEachParameterApart/itkRSGDEachParameterApartOptimizer.cxx
Components/Optimizers/StandardGradientDescent/itkStandardGradientDescentOptimizer.cxx
Components/Optimizers/StandardStochasticGradientDescent/itkStandardStochasticGradientDescentOptimizer.cxx
Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx
Core/Configuration/elxConfiguration.cxx
Core/Kernel/elxElastixMain.cxx
Core/Main/elxParameterObject.cxx
Core/elxProgressCommand.cxx
Testing/itkCommandLineArgumentParser.cxx

It appears that clang-format has in some cases introduced a space character between `ClassName` and `::MemberName`. This typically seems to have happened when there originally was a line break between the class name and the member name.
This commit fixes the formatting by removing those spaces, as follows:
find . \( -iname *.cxx \) -exec perl -pi -w -e 's/([A-Z][a-z]+) \:\:([A-Z][a-z])/$1::$2/g;' {} \;
Follows ITK:
- pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2096
- commit: https://github.com/InsightSoftwareConsortium/ITK/commit/734d6f84d728b343baae5ef66643a5568a5a30c7

STYLE: Remove space between class and member names in C++ source files

---

Common/Transforms/itkAdvancedImageMomentsCalculator.hxx

The class `itk::InvalidImageMomentsError` appears unused, while it has been defined twice:
- https://github.com/InsightSoftwareConsortium/ITK/blob/v5.1.1/Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx#L28
- https://github.com/SuperElastix/elastix/blob/5.0.1/Common/Transforms/itkAdvancedImageMomentsCalculator.hxx#L29
Which caused compilation errors like:
> ITK511\Modules\Filtering\ImageStatistics\include\itkImageMomentsCalculator.hxx(28,32): error C2011: 'itk::InvalidImageMomentsError': 'class' type redefinition
> elx\elastix\Common\Transforms\itkAdvancedImageMomentsCalculator.hxx(29): message : see declaration of 'itk::InvalidImageMomentsError'
When doing:
#include "AdvancedAffineTransform/elxAdvancedAffineTransform.h"
#include "EulerTransform/elxEulerTransform.h" …

COMP: Remove itk::InvalidImageMomentsError from Calculator hxx file

---

.github/workflows/clang_format_check.yml

The proposed style changes are given as output of GitHub actions, which fails if files do not adhere to the clang format file.

STYLE: add clang format check

---

Common/CMakeLists.txt
Common/GTesting/CMakeLists.txt
Common/GTesting/elxTransformIOGTest.cxx
Common/ParameterFileParser/itkParameterMapInterface.h
Common/Transforms/elxTransformIO.cxx
Common/Transforms/elxTransformIO.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Configuration/elxConfiguration.h

Allows specifying output file types for transform files by their file name extension, for example:
(TransformOutputFileNameExtensions ".h5" ".mat" ".tfm")

ENH: Add parameter file support for TransformOutputFileNameExtensions

---

Common/Transforms/elxTransformIO.cxx
Common/Transforms/elxTransformIO.h
Core/ComponentBaseClasses/elxTransformBase.hxx

Did rerun clang-format as follows:
find . -regex '.*\.\(hxx\|h\|cxx\)' -exec /c/Users/Niels_Dekker/AppData/Roaming/ClangPowerTools/LLVM/LLVM8.0.1/bin/clang-format.exe -style=file -i {} \;
Formatting errors were introduced by merging pull request #358 ("ENH: Add parameter file support for TransformOutputFileNameExtensions")

STYLE: Fix clang-format errors #358 (TransformOutputFileNameExtensions)

---

Common/CostFunctions/itkImageToImageMetricWithFeatures.h
Common/CostFunctions/itkImageToImageMetricWithFeatures.hxx
Common/CostFunctions/itkMultiInputImageToImageMetricBase.hxx
Components/Transforms/AdvancedAffineTransform/elxAdvancedAffineTransform.hxx
Components/Transforms/AffineDTITransform/elxAffineDTITransform.hxx
Components/Transforms/AffineLogStackTransform/elxAffineLogStackTransform.hxx
Components/Transforms/AffineLogTransform/elxAffineLogTransform.hxx
Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx
Components/Transforms/EulerTransform/elxEulerTransform.hxx
Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx

For any `bool` variable `b`, a statement of the form `b &= true` has no effect at all.
`b &= false` has exactly the same effect as a simple `b = false` assignment.

Remove bitwise AND assignment of literal bool values (true and false)

---

Common/GTesting/elxTransformIOGTest.cxx
Core/ComponentBaseClasses/elxTransformBase.hxx

After calling `elxTransform.SetUseAddition(true)`, a call to `CreateTransformParametersMap` should yield a map with parameterMap["HowToCombineTransforms"] returning "Add", and not "Compose". Just like `TransformBase::WriteToFile` writes "(HowToCombineTransforms Add)", in that case.
This commit aims to fix this bug, and includes a GoogleTest unit test. Discussed with Marius (@mstaring) at our internal weekly elastix sprint.

BUG: Transform UseAddition should affect CreateTransformParametersMap

---

Components/Transforms/AffineLogStackTransform/elxAffineLogStackTransform.hxx
Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx

Reran:
find . -regex '.*\.\(hxx\|h\|cxx\)' -exec '/c/Program Files/LLVM/8.0.1-ITK/clang-format.exe' -style=file -i {} \;
After merge of pull request #363 from ntatsisk/automaticScalesEstimationStackTransform, commit b6467ba7d6648d343582d57d55b8eec317ebea75 by Stefan Klein, 11 January 2021.

STYLE: Rerun clang-format after pull request #363

---

Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.hxx
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.hxx

When the current transform parameter filename would not have "TransformParameters." as a substring, the creation of the "lastpart" of a `DeformationFieldFileName` would go wrong (typically causing an `std::out_of_range` exception). However, it still appears useful to make a `DeformationFieldFileName` in that case. Especially when trying to write a default-constructed transform, for test purposes.
This commit makes the "lastpart" empty, in that case. Discussed with Marius @mstaring at the weekly internal elastix sprint.

ENH: DeformationFieldFileName when "TransformParameters." is not found

---

Common/GTesting/elxTransformIOGTest.cxx
Components/Transforms/WeightedCombinationTransform/elxWeightedCombinationTransform.hxx

Anticipating pull request https://github.com/SuperElastix/elastix/pull/385 "Sync Transform WriteToFile with CreateTransformParametersMap".

ENH: Add SubTransforms to WeightedCombinationTransform parameter map

---

Common/GTesting/elxTransformIOGTest.cxx
Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.hxx

Added "MultiBSplineTransformWithNormalLabels" to the transform parameter map of `MultiBSplineTransformWithNormal`, addressing a "TODO" comment.
Anticipating pull request https://github.com/SuperElastix/elastix/pull/385 "Sync Transform WriteToFile with CreateTransformParametersMap".
Also improved the `Test_CreateTransformParametersMap_for_default_transform()` unit test function for `MultiBSplineTransformWithNormal`. Note that this change is not yet completely unit tested, because `MultiBSplineTransformWithNormal::BeforeAll()` throws an exception, saying "ERROR: Missing -labels argument!".

ENH: Add MultiBSplineTransformWithNormalLabels to parameter map

---

Common/GTesting/elxBaseComponentGTest.cxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Install/elxBaseComponent.cxx
Core/Install/elxBaseComponent.h

Aims to improve performance and thread-safety of `TransformBase::WriteToFile`.
Intended to be reused by `WriteToFile` member functions of other classes from "Core/ComponentBaseClasses".

ENH: Add BaseComponent::ParameterMapToString(map) + unit test

---

Common/xout/xoutbase.h
Common/xout/xoutbase.hxx
Common/xout/xoutmain.cxx
Common/xout/xoutmain.h
Core/Kernel/elxElastixMain.cxx

Made `xoutbase<char>` an abstract base class (as was already documented), by declaring its destructor pure (`= 0`) virtual, and its default-constructor `protected`.
Derived an `xoutmain` class as the new type of the xout singleton.
Aims to clarify the design of the xout library, by distinguishing clearly between base and leaf classes. See also Scott Meyers's book "More Effective C++", Item 33: "Make non-leaf classes abstract".

STYLE: Make xoutbase abstract and add xoutmain type for xout singleton

---

Common/xout/CMakeLists.txt
Common/xout/xoutbase.cxx
Common/xout/xoutbase.h
Common/xout/xoutcell.cxx
Common/xout/xoutcell.h
Common/xout/xoutmain.h
Common/xout/xoutrow.cxx
Common/xout/xoutrow.h
Common/xout/xoutsimple.cxx
Common/xout/xoutsimple.h
Core/Kernel/elxElastixBase.h
Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixTemplate.hxx

It does not appear necessary to support template arguments (charT and traits) for the xout classes, as elastix always only uses 8-bits `char` as character type of output streams.
Removing those template arguments significantly reduces compilation time (especially when adjusting the implementation of xout) and code complexity.
Discussed at our internal SuperElastix/elastix slack channel.

STYLE: Remove template arguments charT, traits from xout classes

---

Common/GTesting/elxResampleInterpolatorGTest.cxx
Common/GTesting/elxResamplerGTest.cxx
Components/ResampleInterpolators/BSplineResampleInterpolator/elxBSplineResampleInterpolator.h
Components/ResampleInterpolators/BSplineResampleInterpolator/elxBSplineResampleInterpolator.hxx
Components/ResampleInterpolators/BSplineResampleInterpolatorFloat/elxBSplineResampleInterpolatorFloat.h
Components/ResampleInterpolators/BSplineResampleInterpolatorFloat/elxBSplineResampleInterpolatorFloat.hxx
Components/ResampleInterpolators/RDBSplineResampleInterpolator/elxRDBSplineResampleInterpolator.h
Components/ResampleInterpolators/RDBSplineResampleInterpolator/elxRDBSplineResampleInterpolator.hxx
Components/ResampleInterpolators/RayCastResampleInterpolator/elxRayCastResampleInterpolator.h
Components/ResampleInterpolators/RayCastResampleInterpolator/elxRayCastResampleInterpolator.hxx
Components/Resamplers/OpenCLResampler/elxOpenCLResampler.h
Components/Resamplers/OpenCLResampler/elxOpenCLResampler.hxx
Core/ComponentBaseClasses/elxResampleInterpolatorBase.h
Core/ComponentBaseClasses/elxResampleInterpolatorBase.hxx
Core/ComponentBaseClasses/elxResamplerBase.h
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/Install/elxConversion.cxx
Core/Install/elxConversion.h
Core/Kernel/elxElastixTemplate.hxx

Follow-up to "Sync Transform WriteToFile with CreateTransformParametersMap" pull request #385 commit af382ee
Making use of the new `ParameterMapToString` function from pull request #394 commit 1a31732

Sync Resamplers, ResampleInterpolators WriteToFile with their ParameterMap 

---

Common/GTesting/elxTransformIOGTest.cxx
Common/Transforms/elxTransformIO.cxx
Common/Transforms/elxTransformIO.h
Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.hxx
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.hxx

Adds "DeformationFieldFileName" to the parameter maps of both `DeformationFieldTransform` and `BSplineTransformWithDiffusion`.
Reduced code duplication by adding a helper function, `TransformIO::MakeDeformationFieldFileName`.
Adjusted GTest `CreateTransformParametersMap` unit tests by expecting the added parameter for those two transform types.

ENH: Add DeformationFieldFileName from two transforms to ParameterMap

---

CMakeLists.txt

This avoids circular dependency when building ITKElastix as part of ITK.

ENH: specify required ITK components explicitly

---

Common/GTesting/elxConversionGTest.cxx
Common/ParameterFileParser/itkParameterMapInterface.cxx
Common/ParameterFileParser/itkParameterMapInterface.h
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/Install/elxConversion.h
Core/Main/elxParameterObject.cxx

Follow-up to pull request  #403, "ParameterMapInterface style improvements, round trip tests, Infinity and NaN support"
Including: 
- a more useful workaround for the LLVM Bug 39012, [ostream writes a double that istream can't read](https://bugs.llvm.org/show_bug.cgi?id=39012)
- restored and improved support for (signed/unsigned) char pixel types
- improved I/O for `DefaultPixelValue` parameter value, taking the pixel type into account

Restore char pixel type support, work around Clang denormal bug, improve DefaultPixelValue I/O

---

Common/GTesting/elxResampleInterpolatorGTest.cxx
Common/GTesting/elxResamplerGTest.cxx
Common/GTesting/elxTransformIOGTest.cxx
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNbdTree.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNbdTree.hxx
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNkDTree.h
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/itkANNkDTree.hxx
Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxElastixTemplate.h
Core/Kernel/elxElastixTemplate.hxx
Core/Main/elxElastixFilter.h
Core/Main/elxElastixFilter.hxx
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/transformixlib.cxx
Core/Main/transformixlib.h

See also https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-value-param.html
(Clang-Tidy also found the template template parameter issue, which is fixed as well.)

Small fixes based on Clang-Tidy performance-unnecessary-value-param

---

Components/Metrics/RigidityPenalty/elxTransformRigidityPenaltyTerm.hxx
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/CMAEvolutionStrategy/elxCMAEvolutionStrategy.hxx
Components/Optimizers/ConjugateGradient/elxConjugateGradient.hxx
Components/Optimizers/ConjugateGradientFRPR/elxConjugateGradientFRPR.hxx
Components/Optimizers/FiniteDifferenceGradientDescent/elxFiniteDifferenceGradientDescent.hxx
Components/Optimizers/FullSearch/elxFullSearchOptimizer.hxx
Components/Optimizers/Powell/elxPowell.hxx
Components/Optimizers/PreconditionedGradientDescent/elxPreconditionedGradientDescent.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Components/Optimizers/QuasiNewtonLBFGS/elxQuasiNewtonLBFGS.hxx
Components/Optimizers/RSGDEachParameterApart/elxRSGDEachParameterApart.hxx
Components/Optimizers/RegularStepGradientDescent/elxRegularStepGradientDescent.hxx
Components/Optimizers/Simplex/elxSimplex.hxx
Components/Optimizers/SimultaneousPerturbation/elxSimultaneousPerturbation.hxx
Components/Optimizers/StandardGradientDescent/elxStandardGradientDescent.hxx
Components/Registrations/MultiMetricMultiResolutionRegistration/elxMultiMetricMultiResolutionRegistration.hxx
Core/ComponentBaseClasses/elxMetricBase.hxx
Core/Install/elxBaseComponentSE.h
Core/Kernel/elxElastixBase.cxx
Core/Kernel/elxElastixBase.h
Core/Kernel/elxElastixTemplate.hxx

No longer added `ElastixBase::m_IterationInfo` to `xout["iteration"]`. Accessed `IterationInfo` via newly added member functions of `ElastixBase` and `BaseComponentSE`, instead. 
Aims to improve thread-safety, as discussed at our internal weekly elastix sprint.
Related to issue #174 "elastix 4.9 static library version not thread safe"

Replace xout["iteration"] by access to IterationInfo via ElastixBase and BaseComponentSE 

---

Common/xout/xoutbase.cxx
Common/xout/xoutbase.h
Common/xout/xoutrow.cxx
Common/xout/xoutrow.h
Core/Kernel/elxElastixTemplate.hxx

Dropped "WriteHeaders" as special case for `xout[name]`.
Replaced "WriteHeaders" by a direct call to `xoutrow::WriteHeaders()`.
Aims to just simplify the code.

STYLE: Remove xout["WriteHeaders"] logic, simply call WriteHeaders()

---

Common/GTesting/elxResampleInterpolatorGTest.cxx
Common/GTesting/elxResamplerGTest.cxx
Common/GTesting/elxTransformIOGTest.cxx
Core/ComponentBaseClasses/elxResampleInterpolatorBase.h
Core/ComponentBaseClasses/elxResampleInterpolatorBase.hxx
Core/ComponentBaseClasses/elxResamplerBase.h
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxElastixTemplate.hxx

Replaced `ParameterMapType *` by `ParameterMapType &` as parameter type, to express that `CreateTransformParametersMap` does not support `nullptr` as argument.
Follows C++ Core Guidelines section "Parameter passing expression rules" from https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-functions (August 3, 2020)

STYLE: Pass parameter map "by reference" to CreateTransformParametersMap

---

Components/Resamplers/OpenCLResampler/elxOpenCLResampler.h

Addressed issue https://github.com/SuperElastix/elastix/issues/414 "OpenCLResampler build error: 'ParameterMapType does not name a type'", reported by @1989HD.

COMP: Fix OpenCLResampler ParameterMapType build error

---

Components/Transforms/AdvancedAffineTransform/elxAdvancedAffineTransform.h
Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.h
Components/Transforms/AffineDTITransform/elxAffineDTITransform.h
Components/Transforms/AffineLogStackTransform/elxAffineLogStackTransform.h
Components/Transforms/AffineLogTransform/elxAffineLogTransform.h
Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.h
Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.h
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.h
Components/Transforms/EulerStackTransform/elxEulerStackTransform.h
Components/Transforms/EulerTransform/elxEulerTransform.h
Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.h
Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.h
Components/Transforms/SimilarityTransform/elxSimilarityTransform.h
Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.h
Components/Transforms/TranslationStackTransform/elxTranslationStackTransform.h
Components/Transforms/TranslationTransform/elxTranslationTransform.h
Components/Transforms/WeightedCombinationTransform/elxWeightedCombinationTransform.h
Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx

Replaced 11 `dynamic_cast`'s from the implementation of `elx::TransformBase` by calls to `this->GetAsCombinationTransform()`, which is now pure `virtual`. Did override `TransformBase::GetAsCombinationTransform()` in all of its 17 derived transform classes.
Aims to fix MacOS segfaults, mentioned by Matt McCormick (@thewtex), issue https://github.com/SuperElastix/elastix/issues/411, "elastix::TransformBase itk::Object casting".

BUG: Replace dynamic_cast's TransformBase by GetAsCombinationTransform()

---

Common/Transforms/itkRecursiveBSplineTransformImplementation.h

Solved fifteen Visual C++ warnings from `RecursiveBSplineTransformImplementation::GetJacobianOfSpatialHessian`, which said:
> warning C4789: buffer 'jsh_tmp' of size 32 bytes will be overrun; 8 bytes will be written starting at offset 64
Note that the buffer overrun would not occur in practice, as the size of `jsh_tmp` depends on `OutputDimension`, which was checked at runtime. But the compiler still issued those warnings. Which are fixed by this commit.

COMP: Fix GetJacobianOfSpatialHessian warnings on jsh_tmp buffer overrun

---

Core/Main/GTesting/CMakeLists.txt
Core/Main/GTesting/ElastixFilterGTest.cxx
Core/Main/GTesting/ElastixLibGTest.cxx
Core/Main/GTesting/elxCoreMainGTestUtilities.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

Aims to support both ITK 5.1 and ITK 5.2, by allowing `ImageRegionRange` to be either in `namespace itk` or in `namespace itk::Experimental`.

ENH: Move FillImageRegion to elxCoreMainGTestUtilities.h

---

.github/workflows/ElastixGitHubActions.yml
.gitignore
Dockerfile
README.md

The CI now builds a docker image of every tagged elastix commit. The docker image is uploaded to [dockerhub](https://hub.docker.com/repository/docker/superelastix/elastix) and labeled by it's tag.

CI: Elastix docker image build and push to docker hub

---

Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixMain.h
Core/Kernel/elxTransformixMain.cxx

Two little commits to modernize the implementation, interface, and calls to `ElastixMain::GetElastixBase(void)`.

Modernize ElastixMain::GetElastixBase(void)

---

Common/xout/xoutmain.cxx
Common/xout/xoutmain.h
Core/Kernel/elxElastixMain.cxx
Core/Main/elxElastixFilter.h
Core/Main/elxElastixFilter.hxx
Core/Main/elxTransformixFilter.h
Core/Main/elxTransformixFilter.hxx

Added `DisableOutput(void)` member function to both `elx::ElastixFilter` and  `elx::TransformixFilter`, which allows skipping an internal `xoutSetup` call, during `GenerateData()`. Effectively suppressed the output that is otherwise produced, when doing `xl::xout["some-stream"] << "some-output"`.
Aims to ease multi-threading support, as discussed with Konstantinos Ntatsis (@ntatsisk) .

Allow disabling all output from `xout`, to ease multi-threading support

---

Components/Resamplers/OpenCLResampler/elxOpenCLResampler.h

Fixed compilation errors like:
> Components\Resamplers\OpenCLResampler\elxOpenCLResampler.h(158,1): error C2535: 'const elastix::OpenCLResampler<TElastix> &elastix::OpenCLResampler<TElastix>::GetSelf(void) const': member function already defined or declared
> Components\Resamplers\OpenCLResampler\elxOpenCLResampler.h(157): message : see declaration of 'elastix::OpenCLResampler<TElastix>::GetSelf'

COMP: Remove duplicated elxOverrideGetSelfMacro from OpenCLResampler

---

Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx
Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx
Components/Optimizers/AdaGrad/elxAdaGrad.h
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.h
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.h
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.h
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.h
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.hxx
Core/ComponentBaseClasses/elxResamplerBase.hxx

Removed "no-op" dynamic_casts, that just cast a pointer to its own compile-time type.
Remove unused `CheckForAdvancedTransform(void)` member functions, which have such "no-op" dynamic_casts.
Removal of dynamic_casts could ease avoiding the MacOS segfaults that we observed.

STYLE: Remove 14 unnecessary dynamic_casts from T* tot T*

---

Common/Transforms/elxTransformIO.cxx
Common/Transforms/elxTransformIO.h
Core/ComponentBaseClasses/elxTransformBase.hxx

Just to reduce the noise, just like using `std::string` for `std::basic_string<char>`.

STYLE: Use itk::TransformBase for itk::TransformBaseTemplate<double>

---

Common/GTesting/CMakeLists.txt
Common/GTesting/itkParameterMapInterfaceTest.cxx
Common/ParameterFileParser/itkParameterMapInterface.h
Core/Configuration/elxConfiguration.h

Added convenience member functions, `itk::ParameterMapInterface::RetrieveValues(parameterName)` and `elx::Configuration::RetrieveValuesOfParameter(parameterName)`.
Included six `ParameterMapInterface` GoogleTest unit tests.

ENH: Add RetrieveValues to ParameterMapInterface and elx::Configuration

---

Core/Kernel/elxElastixBase.cxx
Core/Main/elastixlib.cxx
Core/Main/transformixlib.cxx

Addressed warnings from LLVM 11.1.0 Clang Power Tools, saying:
> 'find_last_of' called with a string literal consisting of a single character; consider using the more effective overload accepting a character [performance-faster-string-find]

COMP: Replace string::find_last_of("/") calls by using string::back()

---

Core/Main/GTesting/ElastixFilterGTest.cxx
Core/Main/GTesting/ElastixLibGTest.cxx
Core/Main/GTesting/elxCoreMainGTestUtilities.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

Preparing to add more unit tests, for example for https://github.com/SuperElastix/elastix/pull/438 (ENH: Read data from an external transform file into the parameter map)

STYLE: Move CreateParameterMap function to elx::CoreMainGTestUtilities

---

Common/ParameterFileParser/itkParameterFileParser.cxx

Removed checks on special characters (",;!@#$%&|<>?") from `ParameterFileParser::GetParameterFromLine` for parameter values, in order to be more permissive towards free text strings, and to allow any file path name as parameter value.

ENH: Lift ParameterFileParser restrictions on chars of parameter values

---

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Testing/Data/Translation(1,-2)/Special characters [(0-9,;!@#$%&)]/ITK-Transform.tfm
Testing/Data/Translation(1,-2)/TransformParameters-link-to-file-with-special-chars-in-path-name.txt

Follow-up to commit 0a962b866dd8a1f15ca1a1eee11ca84a170534ab "ENH: Lift ParameterFileParser restrictions on chars of parameter values".

ENH: Test ability to use special chars in external transform file paths

---

Core/Main/GTesting/CMakeLists.txt
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Added the following unit tests:
- itkTransformixFilter.Translation2D
- itkTransformixFilter.Translation3D
- itkTransformixFilter.TranslationViaExternalTransformFile
- itkTransformixFilter.ITKTranslationTransform2D
- itkTransformixFilter.ITKTranslationTransform3D

ENH: Add five GoogleTest unit tests for itk::TransformixFilter

---

Core/Main/GTesting/elxCoreMainGTestUtilities.cxx
Testing/itkAccumulateDerivativesParallellizationTest.cxx
Testing/itkAdvanceOneStepParallellizationTest.cxx
Testing/itkAdvancedLinearInterpolatorTest.cxx
Testing/itkBSplineDerivativeKernelFunctionTest.cxx
Testing/itkBSplineInterpolationDerivativeWeightFunctionTest.cxx
Testing/itkBSplineInterpolationSODerivativeWeightFunctionTest.cxx
Testing/itkBSplineInterpolationWeightFunctionTest.cxx
Testing/itkBSplineSODerivativeKernelFunctionTest.cxx
Testing/itkCompareCompositeTransformsTest.cxx
Testing/itkGPUFactoriesTest.cxx
Testing/itkMevisDicomTiffImageIOTest.cxx
Testing/itkOpenCLBufferTest.cxx
Testing/itkOpenCLContextTest.cxx
Testing/itkOpenCLDeviceTest.cxx
Testing/itkOpenCLEventTest.cxx
Testing/itkOpenCLImageTest.cxx
Testing/itkOpenCLKernelManagerTest.cxx
Testing/itkOpenCLKernelTest.cxx
Testing/itkOpenCLKernelToImageBridgeTest.cxx
Testing/itkOpenCLPlatformTest.cxx
Testing/itkOpenCLProfilingTimeProbeTest.cxx
Testing/itkOpenCLSamplerTest.cxx
Testing/itkOpenCLSimpleTest.cxx
Testing/itkOpenCLSizeTest.cxx

Fixed various Visual C++ 2019 Warning Level 4 warnings, saying:
> warning C4130: '!=': logical operation on address of string constant
> warning C4100: 'argc': unreferenced formal parameter
> warning C4100: 'argv': unreferenced formal parameter

Fix warnings: '!=' on address of string, 'argv', 'argc' unreferenced parameter

---

Common/xout/xoutbase.cxx
Common/xout/xoutbase.h
Common/xout/xoutcell.cxx
Common/xout/xoutcell.h
Common/xout/xoutrow.cxx
Common/xout/xoutrow.h
Common/xout/xoutsimple.cxx
Common/xout/xoutsimple.h

Followed "Coding Standards" FAQ, "Should I use using namespace std in my code?" (Answer: "Probably not.")
https://isocpp.org/wiki/faq/coding-standards#using-namespace-std

STYLE: Remove `using namespace std` from Common/xout

---

Components/Transforms/AdvancedAffineTransform/elxAdvancedAffineTransform.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Also fixed a bug in `TransformBase::ReadFromFile()` that I introduced last month, with "ENH: Read data from an external transform file into the parameter map" pull request #438 commit 1c294607e55e18018874005e57aac458b6f4e013

Support ITK Parameters and FixedParameters from itk::AffineTransform

---

Common/GTesting/itkParameterMapInterfaceTest.cxx
Common/ParameterFileParser/itkParameterMapInterface.cxx

Replaced `std::istringstream` by `StringToDoubleConverter` from Google's double-conversion library <https://github.com/google/double-conversion>, inside the implementation of `ParameterMapInterface::StringCastToFloatingPoint`.
`double_conversion::StringToDoubleConverter` is not affected by locale settings (specifically the decimal separator), so this commit should fix issue https://github.com/SuperElastix/elastix/issues/454 "elastix crash when LANG=fr_FR.UTF-8".
The new `StringCastToFloatingPoint` implementation detects more types of user input errors, for example when a user tries to use a comma as decimal separator (as in "2,375").
This commit also cleans up, by removing code which is no longer necessary now, from "BUG: ParameterMapInterface::StringCast workaround Clang denormal bug", …

BUG: Use double-conversion instead of std::istringstream in ParameterMap

---

Common/GTesting/elxConversionGTest.cxx
Core/Install/elxConversion.cxx

Accidentally, `ToString(float)` called the "double" specialization of `itk::NumberToString`, which led to a sub-optimal string representation. For example, 0.1f would yield "0.10000000149011612", instead of simply "0.1".
Fixed by calling the "float" specialization of `itk::NumberToString` instead.

BUG: Fix Conversion::ToString(float) itk::NumberToString specialization

---

Common/GTesting/itkParameterMapInterfaceTest.cxx
Common/ParameterFileParser/itkParameterMapInterface.h
Core/Configuration/elxConfiguration.h

Small commits in preparation of extended support of transform parameters from ITK.

Add `HasParameter(const std::string &)` member functions, add `const` to `Configuration::ReadParameter` overloads

---

Common/OpenCL/Filters/itkGPUBSplineBaseTransform.hxx
Common/OpenCL/Filters/itkGPUBSplineInterpolateImageFunction.hxx
Common/OpenCL/Filters/itkGPUIdentityTransform.hxx
Common/OpenCL/Filters/itkGPULinearInterpolateImageFunction.hxx
Common/OpenCL/Filters/itkGPUMatrixOffsetTransformBase.hxx
Common/OpenCL/Filters/itkGPUNearestNeighborInterpolateImageFunction.hxx
Common/OpenCL/Filters/itkGPUResampleImageFilter.hxx
Common/OpenCL/Filters/itkGPUTranslationTransformBase.hxx
Common/OpenCL/ITKimprovements/itkOpenCLContext.cxx
Common/OpenCL/ITKimprovements/itkOpenCLProgram.cxx
Common/Transforms/itkStackTransform.h
Common/itkGenericMultiResolutionPyramidImageFilter.hxx
Common/itkMeshFileReaderBase.hxx
Components/Metrics/RigidityPenalty/elxTransformRigidityPenaltyTerm.hxx
Components/Registrations/MultiMetricMultiResolutionRegistration/elxMultiMetricMultiResolutionRegistration.hxx
Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.hxx
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.hxx
Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.hxx
Core/ComponentBaseClasses/elxMetricBase.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Configuration/elxConfiguration.cxx
Core/Configuration/elxConfiguration.h
Core/Kernel/elxElastixBase.cxx
Core/Kernel/elxElastixMain.cxx
Core/Main/elxElastixFilter.hxx
Core/Main/elxParameterObject.cxx
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.hxx
Testing/elxTransformParametersCompare.cxx

Ran Clang-Tidy (LLVM 11.1.0) `readability-container-size-empty`, as motivated at https://clang.llvm.org/extra/clang-tidy/checks/readability-container-size-empty.html :
"The emptiness of a container should be checked using the empty() method instead of the size() method. It is not guaranteed that size() is a constant-time function, and it is generally more efficient and also shows clearer intent to use empty(). Furthermore some containers may implement the empty() method but not implement the size() method. Using empty() whenever possible makes it easier to switch to another container in the future."
Got extra motivated by having my very first microsoft/STL commit on this topic: https://github.com/microsoft/STL/commit/b95ba0ef2f018530587977d0c730cf0881dfc51a "Avoid calling size() in …

STYLE: Call the `empty()` member function of `std` containers

---

Core/ComponentBaseClasses/elxResamplerBase.hxx

Ran Clang-Tidy-Fix (LLVM 11.1.0) `readability-string-compare`:
https://clang.llvm.org/extra/clang-tidy/checks/readability-string-compare.html
Which says:
"A common mistake is to use the string’s compare method instead of using the equality or inequality operators. The compare method is intended for sorting functions and thus returns a negative number, a positive number or zero depending on the lexicographical relationship between the strings compared. If an equality or inequality check can suffice, that is recommended. This is recommended to avoid the risk of incorrect interpretation of the return value and to simplify the code."
Fixes Clang warnings like:
> elxResamplerBase.hxx(501): warning: do not use 'compare' to test equality of strings; use the string equality operator instead …

STYLE: Replace `std::string::compare` calls by simple `==` expressions

---

Common/OpenCL/Filters/itkGPUResampleImageFilter.hxx
Components/Metrics/DistancePreservingRigidityPenalty/elxDistancePreservingRigidityPenaltyTerm.hxx
Components/Metrics/RigidityPenalty/elxTransformRigidityPenaltyTerm.hxx
Components/Optimizers/FullSearch/elxFullSearchOptimizer.hxx
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.hxx
Core/ComponentBaseClasses/elxRegistrationBase.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxElastixBase.cxx
Core/Kernel/elxElastixMain.cxx
Core/Main/transformix.cxx
Core/Main/transformixlib.cxx
Testing/elxComputeOverlap.cxx
Testing/elxInvertTransform.cxx

Ran Clang-Tidy-Fix (LLVM 11.1.0) `readability-redundant-string-cstr`:
https://clang.llvm.org/extra/clang-tidy/checks/readability-redundant-string-cstr.html

STYLE: Remove unnecessary `std::string::c_str()` calls, using Clang-Tidy

---

Testing/CI/Azure/ci.yml

Addressed:
> ##[warning]Ubuntu 16.04 LTS environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details, see https://github.com/actions/virtual-environments/issues/3287.
From https://dev.azure.com/kaspermarstal/Elastix/_build/results?buildId=2229&view=results

COMP: Upgrade Azure CI from ubuntu-16.04 to ubuntu-18.04

---

CMakeLists.txt
Testing/CI/Azure/ci.yml

Upgraded to ITK version 5.2.0, which was released on May 28, 2021.
ITK 5.2.0 fixed a critical issue, with commit  https://github.com/InsightSoftwareConsortium/ITK/commit/7cebc26dfae73d90dbf4702aa1ccc544e9b70a37 "COMP: Fix OpenJPEG build error with Visual Studio 16.9", by James Butler (@jamesobutler) and @spacelg
Following pull request https://github.com/SuperElastix/SimpleElastix/pull/425 and https://github.com/SuperElastix/SimpleElastix/pull/428 by David Young (@yoda-vid)
Obviously, ITK 5.2.0 has many other improvements: https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v5.2.0

COMP: Upgrade ITK from v5.1.1 to v5.2.0

---

Core/ComponentBaseClasses/elxResamplerBase.h
Core/Main/GTesting/ElastixFilterGTest.cxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/elxElastixFilter.hxx
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx

Both `ElastixFilter::GenerateData()` and `ElastixRegistrationMethod::GenerateData()` did overwrite a user preference by explicitly setting the "WriteResultImage" parameter. This behavior was added with commit a6e8f10 "ENH: Add ElastixFilter support for initial transform parameter file" by Kasper Marstal (@kaspermarstal), 3 February 2016.
Which causes a performance issue, #370 "Final image transformation takes long time", reported by @orange676.
With this commit these `GenerateData()` member functions longer set  "WriteResultImage". When the value of this parameter is false, the elastix library will no longer generate a result image; `GetOutput()` will return an empty image.
Discussed at the internal elastix sprint of 7 June 2021, with Marius (@mstaring), Stefan (@stefanklein), and Viktor …

PERF: GenerateData() should not set "WriteResultImage" (issue #370)

---

Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.h
Core/Install/elxMacro.h
Core/Kernel/elxElastixTemplate.h
Core/Main/elastixlib.h
dox/doxygen/doxyfile.in

Fixed various warnings from Doxygen 1.9.1.
Triggered by issue #233 "Some missing figures in documentation", reported by Ibraheem Al-Dhamari (@idhamari)
Related to issue #479 "Document how to generate Doxygen documentation"

Fix Doxygen 1.9.1 warnings on unsupported tags, IMAGE_PATH, and unresolved link requests

---

Core/Main/GTesting/elxCoreMainGTestUtilities.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx

With ITK 5.2.0, `ImageRegionRange` and `ImageBufferRange` moved from `itk::Experimental` namespace to the root `itk` namespace.
Follow-up to pull request https://github.com/SuperElastix/elastix/pull/475 commit 6803b26a73aea270cf7b75e0febc4d53ea21053e "COMP: Upgrade ITK from v5.1.1 to v5.2.0"

STYLE: Remove ITK 5.1/5.2 `itk::Experimental` namespace workaround

---

Common/GTesting/elxConversionGTest.cxx
Common/GTesting/elxTransformIOGTest.cxx
Common/Transforms/itkStackTransform.hxx
Common/itkComputePreconditionerUsingDisplacementDistribution.hxx
Components/Optimizers/CMAEvolutionStrategy/itkCMAEvolutionStrategyOptimizer.cxx
Core/Install/elxConversion.cxx
Testing/elxInvertTransform.cxx

Simplified the code by using these two `explicit` constructors, which are added with ITK 5.2:
OptimizerParameters(SizeValueType dimension, const ValueType & value);
OptimizerParameters(const ValueType * inputData, SizeValueType dimension);
Follow-up to pull request https://github.com/SuperElastix/elastix/pull/475 commit 6803b26a73aea270cf7b75e0febc4d53ea21053e "COMP: Upgrade ITK from v5.1.1 to v5.2.0"

STYLE: Use the new ITK 5.2 `OptimizerParameters` constructors

---

Core/Main/GTesting/itkTransformixFilterGTest.cxx

Distinguished between equal and "almost equal", to improve readability.
Also added a sanity check that the (expected) output images do have nonzero pixel values.

Add `Expect_TransformixFilter_output_equals_ResampleImageFilter_output`  to itkTransformixFilterGTest

---

Common/GTesting/elxTransformIOGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Related to issue  #464 "Support HDF5 or TFM format for all transforms in transform parameters file..."

More ITK translation, affine, and Euler transform GoogleTest unit tests

---

Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx

Simplified `elastix::TransformBase<TElastix>::ReadFromFile(void)` by using `ParametersType` instead of `std::unique_ptr<ParametersType>`.

STYLE: Replace m_TransformParametersPointer by ParametersType member var

---

Common/Transforms/itkEulerTransform.h
Components/Transforms/AffineDTITransform/itkAffineDTITransform.h
Components/Transforms/SimilarityTransform/itkSimilarityTransform.h

Simplified the code that selects the base class (template) of a transform, based on its `ScalarType` and `Dimension`.

STYLE: Replace Dummy classes of transforms by C++11 template aliases

---

Common/Transforms/itkAdvancedBSplineDeformableTransform.h
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Common/Transforms/itkAdvancedEuler3DTransform.h
Common/Transforms/itkAdvancedIdentityTransform.h
Common/Transforms/itkAdvancedMatrixOffsetTransformBase.h
Common/Transforms/itkAdvancedRigid2DTransform.h
Common/Transforms/itkAdvancedRigid3DTransform.h
Common/Transforms/itkAdvancedSimilarity2DTransform.h
Common/Transforms/itkAdvancedSimilarity3DTransform.h
Common/Transforms/itkAdvancedTransform.h
Common/Transforms/itkAdvancedTranslationTransform.h
Common/Transforms/itkAdvancedVersorRigid3DTransform.h
Common/Transforms/itkAdvancedVersorTransform.h
Common/Transforms/itkBSplineInterpolationDerivativeWeightFunction.h
Common/Transforms/itkBSplineInterpolationSecondOrderDerivativeWeightFunction.h
Common/Transforms/itkBSplineInterpolationWeightFunction2.h
Common/Transforms/itkCyclicBSplineDeformableTransform.h
Common/Transforms/itkEulerTransform.h
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.h
Components/Metrics/DisplacementMagnitudePenalty/itkDisplacementMagnitudePenaltyTerm.h
Components/Transforms/AffineDTITransform/itkAffineDTI2DTransform.h
Components/Transforms/AffineDTITransform/itkAffineDTI3DTransform.h
Components/Transforms/AffineDTITransform/itkAffineDTITransform.h
Components/Transforms/AffineLogTransform/itkAffineLogTransform.h
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.h
Components/Transforms/SimilarityTransform/itkSimilarityTransform.h
Components/Transforms/SplineKernelTransform/itkKernelTransform2.h
Components/Transforms/WeightedCombinationTransform/itkWeightedCombinationTransform.h

These spaces must have been introduced accidentally, by clang-format.
Similar to pull request https://github.com/SuperElastix/elastix/pull/367 commit a133a51a9880f2b81de29e33324bad0744f66e25 "STYLE: Remove space between class and member names in C++ source files"

STYLE: Remove unnecessary spaces from `Superclass ::` in source files

---

Common/GTesting/elxGTestUtilities.h
Common/GTesting/elxTransformIOGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Simplifies creation of an `itk::Point` or an `itk::Vector` "on the fly".

ENH: Add `MakeVector` and `MakePoint` to GTestUtilities

---

Common/GTesting/elxGTestUtilities.h
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Simplifies creation of an `itk::Size` "on the fly".

ENH: Add `MakeSize` to GTestUtilities

---

Components/Transforms/AdvancedAffineTransform/elxAdvancedAffineTransform.h
Components/Transforms/AdvancedAffineTransform/elxAdvancedAffineTransform.hxx
Components/Transforms/AffineDTITransform/elxAffineDTITransform.h
Components/Transforms/AffineDTITransform/elxAffineDTITransform.hxx
Components/Transforms/AffineLogTransform/elxAffineLogTransform.h
Components/Transforms/AffineLogTransform/elxAffineLogTransform.hxx
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.h
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.hxx
Components/Transforms/EulerTransform/elxEulerTransform.h
Components/Transforms/EulerTransform/elxEulerTransform.hxx
Components/Transforms/SimilarityTransform/elxSimilarityTransform.h
Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx
Components/Transforms/TranslationTransform/elxTranslationTransform.h
Components/Transforms/TranslationTransform/elxTranslationTransform.hxx
Components/Transforms/WeightedCombinationTransform/elxWeightedCombinationTransform.h
Components/Transforms/WeightedCombinationTransform/elxWeightedCombinationTransform.hxx

Replace `TransformType::New()` assignments in the body of constructors by C++11 in-class default-member-initialization, for the "current transform" data member of eight elastix transforms.

STYLE: Use in-class default-member-initialization for current transforms

---

Common/GTesting/elxTransformIOGTest.cxx
Components/Transforms/EulerTransform/elxEulerTransform.hxx
Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx
Core/ComponentBaseClasses/elxTransformBase.h
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Regarding issue #464 "Support HDF5 or TFM format for all transforms"

Support reading Euler and Similarity transforms from ITK (HDF5, TFM) into elastix

---

Common/Transforms/itkAdvancedSimilarity3DTransform.hxx

Following ITK issue https://github.com/InsightSoftwareConsortium/ITK/issues/2629 and pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2627

BUG: `AdvancedSimilarity3DTransform::SetScale` should recompute m_Offset

---

Common/GTesting/elxGTestUtilities.h
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Using a new helper function, `elx::GTestUtilities::GeneratePseudoRandomParameters`.

ENH: Add itkTransformixFilter ITKBSplineTransform GoogleTest unit tests

---

Core/Main/GTesting/ElastixLibGTest.cxx
Core/Main/GTesting/elxCoreMainGTestUtilities.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

Wrapping GoogleTest `ASSERT`s into lambda's appeared to be a clever workaround to avoid compile errors, like
> error C2440: 'return': cannot convert from 'void' to 'std::array<double,2>'
From elastix\Core\Main\GTesting\ElastixLibGTest.cxx as follows:
template <unsigned VDimension>
std::array<double, VDimension>
ConvertStringsToArrayOfDouble(const std::vector<std::string> & strings)
{
ASSERT_EQ(strings.size(), VDimension);  // compile error!!!
...
Wrapped in a lambda as:
[&strings] { ASSERT_EQ(strings.size(), VDimension); }();
However, the wrapped versions don't break the program flow anymore, as "expected" from an assert failure.
Fixed by using GoogleTest `EXCEPT` macro's instead, and the introduced `ELX_GTEST_EXPECT_FALSE_AND_THROW_EXCEPTION_IF(condition)`

BUG: Do not wrap any GoogleTest `ASSERT` into a lambda

---

Components/Optimizers/RSGDEachParameterApart/itkRSGDEachParameterApartBaseOptimizer.h
Components/Optimizers/StandardGradientDescent/itkGradientDescentOptimizer2.h

Made `protected` data members of `GradientDescentOptimizer2` and `RSGDEachParameterApartBaseOptimizer` `private` instead.
Note that this cannot be achieved easily for all `protected` data members of all Optimizer classes, without having to deal with various compile errors.
Follows C++ Core Guidelines (June 17, 2021): "C.133: Avoid protected data"
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rh-protected

STYLE: Make protected data GradientDescent, RSGDEach...Optimizer private

---

Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/FiniteDifferenceGradientDescent/itkFiniteDifferenceGradientDescentOptimizer.cxx
Components/Optimizers/PreconditionedGradientDescent/itkPreconditionedGradientDescentOptimizer.cxx
Components/Optimizers/StandardGradientDescent/itkGradientDescentOptimizer2.cxx
Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

Until now, optimizers appear to do a single iteration step, even when the elastix parameter "MaximumNumberOfIterations" has the value "0". It appears that those optimizers did the check `if (m_CurrentIteration >= m_NumberOfIterations) break;` when it was too late already to avoid the first iteration. 
Supporting MaximumNumberOfIterations = 0 (by doing no optimizer iteration at all) allows inspecting the result of just doing an AutomaticTransformInitialization. As hereby tested.

Support MaximumNumberOfIterations = 0, allowing to just do an AutomaticTransformInitialization

---

.github/workflows/ElastixGitHubActions.yml

Added `USE_ALL_COMPONENTS` to include components that are OFF by default:
Optimizers\AdaGrad
Optimizers\AdaptiveStochasticLBFGS
Optimizers\AdaptiveStochasticVarianceReducedGradient
Transforms\BSplineDeformableTransformWithDiffusion
(The component Optimizers\PreconditionedGradientDescent is still excluded, because of its SuiteSparse dependency.) See also pull request #291 "ENH: Enable almost all components by default"
Added `ELASTIX_USE_GTEST`, to include GoogleTest based unit tests.

ENH: Add `ELASTIX_USE_GTEST` and `USE_ALL_COMPONENTS` to GitHub Actions

---

Common/ImageSamplers/itkVectorDataContainer.h
Common/Transforms/itkAdvancedEuler3DTransform.h
Common/Transforms/itkAdvancedMatrixOffsetTransformBase.h
Common/Transforms/itkAdvancedRigid2DTransform.h
Common/Transforms/itkAdvancedRigid3DTransform.h
Common/Transforms/itkAdvancedTransform.h

Did run LLVM 12.0.1 Clang-Tidy option `google-explicit-constructor`:
> Checks that constructors callable with a single argument and conversion operators are marked explicit to avoid the risk of unintentional implicit conversions.
https://clang.llvm.org/extra/clang-tidy/checks/google-explicit-constructor.html
Note that the `ConstIterator(const Iterator &)` constructor of `VectorDataContainer::ConstIterator` does intentionally support implicit conversion, so this constructor is not marked `explicit`.

STYLE: Mark constructors `explicit`, to avoid unintended conversions

---

Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx

It was only called once, internally within `elx::TransformBase<TElastix>::ReadFromFile(void)`.
Follow-up to commit fa6397bb56305a49f0458b3f7cc8f0b45bc68669 "STYLE: Share code between TransformBase::ReadInitialTransform functions".

STYLE: Remove elx::TransformBase::ReadInitialTransformFromVector(size_t)

---

Common/ParameterFileParser/CMakeLists.txt
Common/ParameterFileParser/itkParameterMapInterface.cxx

Aims to fix a SimpleElastix compilation error, encountered by Viktor (@ViktorvdValk).

COMP: Do `#include <double-conversion.h>`, and add its include path

---

Components/Transforms/SplineKernelTransform/itkElasticBodyReciprocalSplineKernelTransform2.h
Components/Transforms/SplineKernelTransform/itkElasticBodySplineKernelTransform2.h
Components/Transforms/SplineKernelTransform/itkKernelTransform2.h
Core/Install/elxMacro.h

`elxOverrideGetConstMacro` was only used to override `KernelTransform2::GetAlpha()`, and even this specific use case did not appear very relevant, as `KernelTransform2::GetAlpha()` was never called anywhere in elastix.

STYLE: Remove elxOverrideGetConstMacro and KernelTransform2::GetAlpha()

---

Common/GTesting/itkParameterMapInterfaceTest.cxx
Common/ParameterFileParser/itkParameterMapInterface.cxx
Common/ParameterFileParser/itkParameterMapInterface.h

Allows calling something like `configuration.RetrieveValuesOfParameter<bool>("parameter")`.
Extended `ParameterMapInterface` GoogleTest to test `RetrieveValues<bool>`.
Adjusted the `bool` specific overload of `ReadParameter` to internally use `StringCast`.

ENH: Add `ParameterMapInterface::StringCast` overload to convert to bool

---

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.h
Common/MevisDicomTiff/itkMevisDicomTiffImageIO.h
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Common/itkMultiOrderBSplineDecompositionImageFilter.h
Common/itkMultiResolutionImageRegistrationMethod2.h
Components/Metrics/DistancePreservingRigidityPenalty/itkDistancePreservingRigidityPenaltyTerm.h
Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.h
Components/Metrics/StatisticalShapePenalty/itkStatisticalShapePointPenalty.h
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.h
Components/Optimizers/FiniteDifferenceGradientDescent/itkFiniteDifferenceGradientDescentOptimizer.h
Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.h
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.h
Components/Transforms/SplineKernelTransform/itkKernelTransform2.h
Core/Kernel/elxElastixMain.h
Core/Main/elxElastixFilter.h
Core/Main/elxTransformixFilter.h
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkTransformixFilter.h
Testing/itkCommandLineArgumentParser.h

Removed the commented-out `itkGetMacro` calls, and replaced the remaining calls with `itkGetConstMacro`, to improve const-correctness and consistency.

Remove `itkGetMacro` calls, replace them with `itkGetConstMacro`

---

Common/GTesting/elxConversionGTest.cxx
Common/GTesting/elxTransformIOGTest.cxx
Common/Transforms/elxTransformIO.cxx
Common/Transforms/elxTransformIO.h
Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

When the `AdvancedCombinationTransform` to be written by the `WriteToFile` member function of `elx::TransformBase` has more than one transform, `WriteToFile` now writes an ITK CompositeTransform of all of them to TFM or HDF5 (experimentally).
Removed the BSpline test from `TransformIO.CorrespondingItkTransform`, as it is broken by this enhancement.
Added `itkElastixRegistrationMethod.WriteCompositeTransform` GoogleTest unit test.

ENH: Write CompositeTransform when combination has multiple transforms

---

Common/GTesting/elxTransformIOGTest.cxx

Found by temporarily adding `#define ITK_MANUAL_INSTANTIATION`.

COMP: Add missing #include directives to "elxTransformIOGTest.cxx"

---

Common/Transforms/itkStackTransform.h
Common/Transforms/itkStackTransform.hxx

`m_NumberOfSubTransforms` is always identical to `m_SubTransformContainer.size()`, by definition.
Removed `virtual` from member function declarations of `StackTransform`, as these are not overridden. (Actually, `StackTransform` not being used as base class anyway.) Following C++ Core Guidelines, August 19, 2021, "C.132: Don't make a function virtual without reason", https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-virtual

STYLE: Remove `StackTransform::m_NumberOfSubTransforms` and `virtual`

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx

Added a new member function to `AdvancedImageToImageMetric`, `FastEvaluateMovingImageValueAndDerivative`, which calls the multi-threaded overload of ITK's `itk::BSplineInterpolateImageFunction::EvaluateValueAndDerivativeAtContinuousIndex`, indirectly. (It does so via `EvaluateMovingImageValueAndDerivativeWithOptionalThreadId`, another new member function.)
Made `AdvancedNormalizedCorrelationImageToImageMetric::ThreadedGetValueAndDerivative` faster, by calling this new `FastEvaluateMovingImageValueAndDerivative`.
A large performance improvement was observed for GoogleTest unit test `itkElastixRegistrationMethod.EulerDiscRotation2D` (which uses the "AdvancedNormalizedCorrelation" metric), from ~1.5 second before this commit down to ~0.9 second after this commit, using Visual Studio 2019, …

PERF: Make AdvancedNormalizedCorrelationImageToImageMetric faster

---

Common/CostFunctions/itkMultiInputImageToImageMetricBase.h
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx
Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx

Follow-up to pull request #556 "PERF: Make AdvancedNormalizedCorrelationImageToImageMetric faster"

Call `FastEvaluateMovingImageValueAndDerivative` in six more metrics

---

Testing/CI/Azure/ci.yml

Addressed:
> ##[warning]The macOS-10.14 environment is deprecated and will be removed on December 10, 2021. For more details see https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/
From https://dev.azure.com/kaspermarstal/Elastix/_build/results?buildId=2778&view=results

COMP: Upgrade Azure CI from macOS-10.14 to macOS-10.15

---

Common/GTesting/elxTransformIOGTest.cxx

Related to issue https://github.com/SuperElastix/elastix/issues/561 "Convert elastix RecursiveBSplineTransform to ITK BSplineTransform during I/O"

ENH: RecursiveBSplineTransform in TransformedPointSameAsITKBSpline tests

---

Common/Transforms/itkStackTransform.hxx

Instead of using `OutputSpaceDimension` as initial "guess" for the number of parameters to be allocated, just make it zero, in the `StackTransform` default-constructor.
Eventually, the number of parameters of a stack transform is defined as the number of subtransforms _times_ the number of parameters of a single subtransform.
The original initial number (`OutputSpaceDimension`) just caused unnecessary memory reallocations.

STYLE: Make StackTransform Parameters empty by default

---

Common/Transforms/itkStackTransform.h

These defaults appear counter-intuitive. For example, it does not seem logical to have `NOutputDimensions = 3` by default, for `StackTransform<double, 2>`.

STYLE: Remove `StackTransform` template argument defaults for dimensions

---

Common/Transforms/itkStackTransform.h
Components/Transforms/AffineLogStackTransform/elxAffineLogStackTransform.hxx
Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.hxx
Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx
Components/Transforms/TranslationStackTransform/elxTranslationStackTransform.hxx

Declared the `transform` parameter as a `const` reference, rather than a non-const pointer, to express that the argument may not be null, and that it will not be modified by the member function.

STYLE: Declare `StackTransform::SetAllSubTransforms` parameter const ref

---

Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.h
Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.hxx
Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.h
Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.hxx
Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.h
Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.hxx

Removing duplicate code from elastix B-spline Transform components that created a `BSplineDeformableTransform` object, based upon the spline order.
Also removed unnecessary related typedef's.

ENH: Add `AdvancedBSplineDeformableTransformBase::Create(splineOrder)`

---

Testing/itkAdvancedRecursiveBSplineTransformTest.cxx

Removed unused local variables, `weights`, `weights2`, `indices`, and `indices2`.
These variables were introduced with commit 5a80b720269e7c6b660283d75bb9a087f6dcb678 "ENH: adding RecursiveBSplineTransform", 9 June 2016 (but then, they were already unused).
Removing them now will ease the upgrade to ITK 5.3, which has a new definition of `WeightsType`.

STYLE: Remove unused variables AdvancedRecursiveBSplineTransformTest

---

Common/Transforms/itkBSplineInterpolationWeightFunctionBase.h
Common/itkRecursiveBSplineInterpolationWeightFunction.h

`itk::Math::UnsignedPower(base, exponent)` may be evaluated at compile-time, just like the original `GetConstNumberOf...Hack<SplineOrder, Dimension>::Value` expressions.

STYLE: Remove `GetConstNumber` "hacks", use Math::UnsignedPower instead

---

Common/GTesting/elxTransformIOGTest.cxx

Following GoogleTest pull request https://github.com/google/googletest/pull/2444 commit https://github.com/google/googletest/commit/e0d16aa33662857a5b3f47359f46910d4d18ab5b "Remove GTEST_ARRAY_SIZE_", Krystian Kuzniarek, 22 October 2019.
This commit is necessary before upgrading to ITK 5.3 (which has a newer version of GoogleTest than ITK 5.2.0).

COMP: Replace `GTEST_ARRAY_SIZE_` by `std::extent<decltype(x)>::value`

---

Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx

Just use `std::array`, instead of the original, clever combination of a C-array and a `WeightsType`, to represent `coeffs`.
Paves the way for upgrading to ITK 5.3, which defines `WeightsType` differently.

STYLE: Remove local `coeffArray` from AdvancedBSplineDeformableTransform

---

Core/ComponentBaseClasses/elxTransformBase.hxx

LLVM 13.0.0 Clang-Tidy said:
> elxTransformBase.hxx(1259): error: no type named 'JacobianWriterType' in 'elastix::TransformBase<elastix::ElastixTemplate<itk::Image<float, 2>, itk::Image<float, 2>>>' [clang-diagnostic-error]
Apparently, it does not like a member function of a local class to use a type outside the class.
Fixed by removing `JacobianWriterType` (anywhere anyway, also where it didn't really harm) and adding helper type alias, `PrivateJacobianImageType`.

COMP: Workaround "no type named 'JacobianWriterType' [clang-diagnostic-error]"

---

Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.hxx

The RecursiveBSplineTransform component accidentally used the non-recursive `itk::AdvancedBSplineDeformableTransform`.
Bug introduced with pull request https://github.com/SuperElastix/elastix/pull/572 commit 02396ca959d4775faddd313cb9369b0425a445bd "ENH: Add `AdvancedBSplineDeformableTransformBase::Create(splineOrder)`" (merged on 30 December 2021).

BUG: RecursiveBSplineTransform should use itk::RecursiveBSplineTransform

---

Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.hxx

Paving the way to support reading and writing BSpline transforms with a spline order 1 or 2 (rather than just the default spline order = 3).

Remove m_SplineOrderOdd and add GetSplineOrder() to AdvancedBSplineDeformableTransformBase

---

Common/CMakeLists.txt
Common/Transforms/elxTransformFactoryRegistration.cxx
Common/Transforms/elxTransformIO.cxx
Common/elxSupportedImageDimensions.h
Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.hxx
Core/Configuration/elxConfiguration.cxx
Core/Kernel/elxElastixMain.cxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Supported writing a b-spline transform from elastix to ITK HDF5 or TFM file, and then reading it back into either elastix or transformix.

Add ITK I/O support to BSplineTransform spline order 1 and 2

---

Common/Transforms/itkAdvancedMatrixOffsetTransformBase.h
Common/Transforms/itkAdvancedMatrixOffsetTransformBase.hxx

Use in-class default member-initializers in `AdvancedMatrixOffsetTransformBase`, just like in ITK's "itkMatrixOffsetTransformBase.h":
https://github.com/InsightSoftwareConsortium/ITK/blob/v5.3rc01/Modules/Core/Transform/include/itkMatrixOffsetTransformBase.h#L579-L585
Following pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2491 commit https://github.com/InsightSoftwareConsortium/ITK/commit/e6f5f969751dd2a018ff3bc1cc16c7e9f709737b "STYLE: Combine code MatrixOffsetTransformBase constructors"
Resized `m_FixedParameters`, just like in commit https://github.com/InsightSoftwareConsortium/ITK/commit/168f84f1ac3e209cc46d1c9b07a896fc895cdd8a
"BUG: MatrixOffsetTransformBase::GetFixedParameters not thread safe."

STYLE: Sync `AdvancedMatrixOffsetTransformBase` constructor with ITK 5.3

---

Common/LineSearchOptimizers/itkLineSearchOptimizer.cxx
Common/MevisDicomTiff/itkMevisDicomTiffImageIO.cxx
Common/Transforms/itkBSplineDerivativeKernelFunction2.h
Common/Transforms/itkBSplineKernelFunction2.h
Common/itkComputeDisplacementDistribution.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/NormalizedMutualInformation/itkParzenWindowNormalizedMutualInformationImageToImageMetric.hxx
Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.hxx
Components/Transforms/BSplineDeformableTransformWithDiffusion/itkVectorMeanDiffusionImageFilter.hxx
Core/ComponentBaseClasses/elxResamplerBase.hxx

Follow-up to the merged pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3146 "STYLE: Replace `NumericTraits<double>::ZeroValue()` and `NumericTraits<double>::OneValue()` calls by `0.0` and `1.0`, respectively"

Replace NumericTraits::ZeroValue() by 0.0, and NumericTraits::ZeroValue() by 1.0

---

Common/Transforms/elxTransformIO.cxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

Allows writing a composite transform from elastix to ITK, when it contains an elastix "RecursiveBSplineTransform".

BUG: Convert elastix "RecursiveBSplineTransform" to ITK BSplineTransform

---

Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.hxx
Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.hxx
Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.hxx
Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.hxx

Using the `OptimizerParameters(const SizeValueType dimension, const ValueType & value)` constructor, which was added to ITK with pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2248 commit  https://github.com/InsightSoftwareConsortium/ITK/commit/73ce4ca9dd73498a7f8de4d9aca3b72b1f8b59fe (merged on 11 January 2021).

STYLE: Fill `newScales` variables by one, directly during initialization

---

Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.hxx
Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.hxx

`RecursiveBSplineTransform::ReadFromFile()` should not do `Configuration::ReadParameter` if it has "ITKTransformParameters".
On the other hand, the old `AdvancedBSplineTransform` should not get its data from an ITK transform.

BUG: BSplineTransform should not read config params if it has ITK params

---

Common/Transforms/itkStackTransform.h
Components/Transforms/BSplineStackTransform/itkBSplineStackTransform.h
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Supported ITK I/O for BSplineStackTransform order 1 and 2, by adding the spline order to the FixedParameters.
Preferred alternative to the rejected pull request #598 "ENH: Add ITK I/O support to BSplineStackTransform spline order 1 and 2"

ENH: Add BSplineStackTransform spline order to FixedParameters

---

Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.hxx
Common/Transforms/itkCyclicBSplineDeformableTransform.hxx
Common/Transforms/itkRecursiveBSplineTransform.hxx
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.hxx
Testing/itkBSplineTransformPointPerformanceTest.cxx

Return-by-value is easier to read than pass-by-non-const-reference, and `ContinuousIndexType` has lightweight copy semantics, so it appears preferable for `AdvancedBSplineDeformableTransformBase::TransformPointToContinuousGridIndex` to simply return the continuous index.
Declared local continuous index variables `const`.
Analogous to ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/868 commit https://github.com/InsightSoftwareConsortium/ITK/commit/65233e36b64ac7835fe2b80de2a6b981204554f4 "ENH: Convenience overloads for ImageBase Transform member functions"

STYLE: Let TransformPointToContinuousGridIndex return the index by value

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h

Declared the local Jacobian variable within `AdvancedTransform::EvaluateJacobianWithImageGradientProduct` thread-local, as its repetitive creation and destruction appeared to be a major performance bottleneck.
The number of elements of the Jacobian variable depends on the specific (derived) run-time type of the transform:
4 elements with AdvancedTranslationTransform<double,2>
6 elements with AdvancedTranslationTransform<double,3>
6 elements with EulerTransform<double,2>
18 elements with EulerTransform<double,3>
36 elements with AdvancedMatrixOffsetTransformBase<double,3,3>
With this commit, the GoogleTest unit test `itkElastixRegistrationMethod.EulerDiscRotation2D` appears to run almost twice as fast (from ~2.5 seconds to ~1.5 second, on GitHub Actions Windows-2109)

PERF: Make Jacobian variable in AdvancedTransform Evaluate thread-local

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h

This reverts commit 63227d6ef640cde96de02358c5e78fb87b83a7c0 which was only meant for a local experiment, and was accidentally committed.
So pull request https://github.com/SuperElastix/elastix/pull/604/ "PERF: Make Jacobian variable in AdvancedTransform Evaluate thread-local" had the wrong code change, eventually!

BUG: Revert making `AdvancedImageToImageMetric::TransformPoint` final

---

Common/Transforms/itkAdvancedTransform.hxx

Declared the local Jacobian variable within `AdvancedTransform::EvaluateJacobianWithImageGradientProduct` thread-local, as its repetitive creation and destruction appeared to be a major performance bottleneck.
The number of elements of the Jacobian variable depends on the specific (derived) run-time type of the transform:
4 elements with AdvancedTranslationTransform<double,2>
6 elements with AdvancedTranslationTransform<double,3>
6 elements with EulerTransform<double,2>
18 elements with EulerTransform<double,3>
36 elements with AdvancedMatrixOffsetTransformBase<double,3,3>
With this commit, the GoogleTest unit test `itkElastixRegistrationMethod.EulerDiscRotation2D` appears to run almost twice as fast (from ~2.5 seconds to ~1.5 second, on GitHub Actions Windows-2109)

PERF: Make Jacobian variable in AdvancedTransform thread-local (2nd try)

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/itkCorrespondingPointsEuclideanDistancePointMetric.hxx
Components/Metrics/DisplacementMagnitudePenalty/itkDisplacementMagnitudePenaltyTerm.hxx
Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx
Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx

`AdvancedImageToImageMetric::TransformPoint` did always just return true, at least from commit 8b9a4b0ce51f9602106bf5872b2ccf3892fcef0f (11 August 2009).
Although it was declared `virtual`, there appears no override of this particular member function. 
Discussed with @stefanklein at the internal weekly sprint

STYLE: Make AdvancedImageToImageMetric::TransformPoint return the point

---

Core/Main/GTesting/ElastixLibGTest.cxx

Two optimization iterations appear sufficient to check that the `TransformParameters` are all zero, when the fixed is equal to the moving image.
Reduced the duration of GoogleTest unit test `ElastixLib.TransformParametersAreZeroWhenFixedImageIsMovingImage`, from more than 1500 ms down to less than 500 ms (locally, VS2019 Debug build).

PERF: Set MaximumNumberOfIterations = 2 in GoogleTest `ElastixLib.TransformParametersAreZeroWhenFixedImageIsMovingImage`

---

Core/Main/GTesting/ElastixLibGTest.cxx

The original `GetPixelTypeName<TPixel>()` only supported short and int, causing compile errors in `ElastixLib.TransformParametersAreZeroWhenFixedImageIsMovingImage`, when other pixel types were added (CMake flags `ELASTIX_IMAGE_2D_PIXELTYPES`, `ELASTIX_IMAGE_3D_PIXELTYPES`, and `ELASTIX_IMAGE_4D_PIXELTYPES`).

ENH: Support any pixel type ElastixLibGTest `GetPixelTypeName<TPixel>()`

---

Common/xout/xoutbase.h
Common/xout/xoutrow.cxx
Common/xout/xoutrow.h
Core/Kernel/elxElastixBase.h

Also removed the dummy implementation of `AddTargetCell(const char *)` from its base class. Declared the new `xoutrow::AddNewTargetCell(const char *)` non-virtual.
Aims to fix warnings from cfnCentOSAgent_2-Linux, saying:
> xoutbase.h:109:3: warning: 'virtual int xoutlibrary::xoutbase::AddTargetCell(const char*, xoutlibrary::xoutbase::Self*)' was hidden [-Woverloaded-virtual]
> xoutrow.h:67:3: warning:   by 'virtual int xoutlibrary::xoutrow::AddTargetCell(const char*)' [-Woverloaded-virtual]
From https://open.cdash.org/viewBuildError.php?type=1&buildid=7807857
Triggered by pull request https://github.com/SimpleITK/SimpleITK/pull/1611 "Support adding Elastix component by CMake SimpleITK_USE_ELASTIX=ON"

COMP: Rename `xoutrow` member "AddTargetCell" to "AddNewTargetCell"

---

CMakeLists.txt

The `/bigobj` compile option (introduced with MSVC 2005) still appears useful nowadays, and there appear no downsides to enabling /bigobj", according to "Enable /bigobj by default", Machiel van Hooren, May 14, 2020, https://developercommunity.visualstudio.com/t/Enable-bigobj-by-default/1031214
Marius Staring confirmed that there was no specific reason to avoid adding `/bigobj` for MinSizeRel.

COMP: Add /bigobj to any MSVC WIN32 configuration (including MinSizeRel)

---

CMakeLists.txt
dox/externalproject/CMakeLists.txt

Follows ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2588 commit https://github.com/InsightSoftwareConsortium/ITK/commit/0c3b8cbf9b0b25f2fed789c1a7effe48f29b6967 "COMP: Increased min cmake from 3.10.2 to 3.16.3" (merged on on June 16, 2021), included with ITK tags v5.3rc03 ... v5.3rc01.
Such an upgrade appears necessary in order to allow a Debug compilation of SimpleITK with `SimpleITK_USE_ELASTIX=ON`, as proposed by pull request https://github.com/SimpleITK/SimpleITK/pull/1611 ("WIP: Support adding Elastix component by CMake SimpleITK_USE_ELASTIX=ON"), especially because of CMake improvements regarding the MSVC runtime library selection flags, introduced with CMake 3.15.

ENH: Upgrade cmake_minimum_required from 3.10.2 to 3.16.3, following ITK

---

Common/xout/xoutbase.cxx
Common/xout/xoutbase.h
Common/xout/xoutrow.cxx
Common/xout/xoutrow.h
Common/xout/xoutsimple.cxx

Renamed the `SetTargetCells` overload for `CStreamMapType` arguments "SetCTargetCells", and the other one "SetXTargetCells", and declared them `protected`, instead of `public`.
Addressed SimpleITK warnings from cfnCentOSAgent_1-Linux, at https://open.cdash.org/viewBuildError.php?type=1&buildid=7819092, saying:
> xoutbase.h:115:3: warning: 'virtual void xoutlibrary::xoutbase::SetTargetCells(const CStreamMapType&)' was hidden [-Woverloaded-virtual]
> xoutrow.h:77:3: warning:   by 'virtual void xoutlibrary::xoutrow::SetTargetCells(const XStreamMapType&)' [-Woverloaded-virtual]
Which appeared with pull request https://github.com/SimpleITK/SimpleITK/pull/1611 "WIP: Support adding Elastix component by CMake SimpleITK_USE_ELASTIX=ON".

Rename `xoutbase::SetTargetCells(cellmap)` overloads, addressing SimpleITK warnings

---

Core/Main/elxTransformixFilter.h
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkTransformixFilter.h

Added private using-declarations, to work around warnings from SimpleITK/cfnCentOSAgent_2-Linux CI at https://open.cdash.org/viewBuildError.php?type=1&buildid=7820245 like:
> itkTransformixFilter.hxx:402:1: warning:   by 'itk::TransformixFilter<itk::Image<float, 2> >::SetInput' [-Woverloaded-virtual]
Which appeared from pull request https://github.com/SimpleITK/SimpleITK/pull/1611 "WIP: Support adding Elastix component by CMake SimpleITK_USE_ELASTIX=ON"

COMP: Work around SimpleITK/GCC overloaded-virtual/hidden warnings

---

Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/Kernel/elxElastixBase.h
Testing/elxTransformParametersCompare.cxx
Testing/itkAdvancedBSplineDeformableTransformTest.cxx
Testing/itkAdvancedRecursiveBSplineTransformTest.cxx
Testing/itkBSplineJacobianGradientPerformanceTest.cxx
Testing/itkBSplineTransformPointPerformanceTest.cxx

Called `DirectionType::GetIdentity()` whenever it did simplify the code.
Follow-up to ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2460 commit https://github.com/InsightSoftwareConsortium/ITK/commit/f8ad6cfdee624591c74ce24512ba211c7154a5b4 "ENH: Add static member function, `itk::Matrix::GetIdentity()`", merged on 1 April 2021, and included with ITK v5.2.0.

STYLE: Call `DirectionType::GetIdentity()`, instead of `SetIdentity()`

---

Common/Transforms/itkAdvancedCombinationTransform.hxx
Components/Metrics/DistancePreservingRigidityPenalty/elxDistancePreservingRigidityPenaltyTerm.hxx
Components/Metrics/RigidityPenalty/elxTransformRigidityPenaltyTerm.hxx
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.hxx

Follow-up to pull request https://github.com/SuperElastix/elastix/pull/639 commit 073ddd55e5a614897dbab412b9164357865911ea "STYLE: Call `DirectionType::GetIdentity()`, instead of `SetIdentity()`

STYLE: Call `DirectionType::GetIdentity()` (part 2)

---

Components/Metrics/DistancePreservingRigidityPenalty/elxDistancePreservingRigidityPenaltyTerm.hxx
Components/Metrics/RigidityPenalty/elxTransformRigidityPenaltyTerm.hxx
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.hxx
Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.hxx
Core/Kernel/elxElastixBase.h
Testing/elxComputeOverlap.cxx
Testing/elxTransformParametersCompare.cxx
Testing/itkTransformixFilterTest.cxx

Follow-up to ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2184 commit https://github.com/InsightSoftwareConsortium/ITK/commit/aeea88b1925e400fa6df099871b149a37f1dee17 "ENH: Add convenience function ReadImage", merged on on 22 December 2020, and included with ITK v5.2rc01.

STYLE: Use `itk::ReadImage` instead of `itk::ImageFileReader`

---

Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.h
Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.hxx
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Testing/elxImageCompare.cxx
Testing/elxTransformParametersCompare.cxx
Testing/itkMevisDicomTiffImageIOTest.cxx
Testing/itkTransformixFilterTest.cxx

Follow-up to ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2160 commit https://github.com/InsightSoftwareConsortium/ITK/commit/60b0984d4196841844424e33963e161f3f0c709d "ENH: add a convenience function WriteImage", merged on 9 December 2020, and included with ITK v5.2rc01.

STYLE: Use `itk::WriteImage` instead of `itk::ImageFileWriter`

---

Common/Transforms/itkAdvancedImageMomentsCalculator.h
Common/itkComputeDisplacementDistribution.h

Made data members of `AdvancedImageMomentsCalculator` and `ComputeDisplacementDistribution` private, including their `m_ComputePerThreadVariables` member.
Based on the first commit of pull request https://github.com/SuperElastix/elastix/pull/132 "Improved style of m_ComputePerThreadVariable data members".
Follows C++ Core Guidelines (April 10, 2022): "C.133: Avoid protected data" http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-protected

STYLE: Make data ImageMomentsCalculator, ComputeDisplacementDist private

---

Common/Transforms/itkAdvancedImageMomentsCalculator.h
Common/Transforms/itkAdvancedImageMomentsCalculator.hxx
Common/itkComputeDisplacementDistribution.h
Common/itkComputeDisplacementDistribution.hxx

Declared m_ComputePerThreadVariables of both as `AdvancedImageMomentsCalculator` and `ComputeDisplacementDistribution` as an `std::vector<AlignedComputePerThreadStruct>`, instead of a raw pointer to the structs. Simplified zero-initialization of the structs. Removed manual `delete[]` statements.
Based on the second commit of pull request https://github.com/SuperElastix/elastix/pull/132 "Improved style of m_ComputePerThreadVariable data members".
Follows C++ Core Guidelines (April 10, 2022): "Avoid calling new and delete explicitly" http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-ptr

STYLE: Declared `m_ComputePerThreadVariables` as an `std::vector` (2 x)

---

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.h
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.h
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.h
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.h
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx

Instead of declaring these "PerThreadVariables" data members as raw pointers, of four `Metric` types. Removed the corresponding "PerThreadVariablesSize" data members. Defaulted ( `= default`) their destructors.Replaced `for (ThreadIdType i = 0; i < numberOfThreads; ++i)` loops by range-based for-loops.
Follow-up to pull request https://github.com/SuperElastix/elastix/pull/644 commit 398cea90b14bf00c8d150ad9737f70fe2bcb13e0 "STYLE: Declared `m_ComputePerThreadVariables` as an `std::vector` (2 x)"

STYLE: Declare "PerThreadVariables" data members as `std::vector` (4x)

---

Common/OpenCL/Filters/itkGPUAdvancedEuler2DTransform.h
Common/OpenCL/Filters/itkGPUAdvancedEuler3DTransform.h
Common/OpenCL/Filters/itkGPUAdvancedMatrixOffsetTransformBase.h
Common/OpenCL/Filters/itkGPUAdvancedSimilarity2DTransform.h
Common/OpenCL/Filters/itkGPUAdvancedSimilarity3DTransform.h
Common/OpenCL/Filters/itkGPUAffineTransform.h
Common/OpenCL/Filters/itkGPUEuler2DTransform.h
Common/OpenCL/Filters/itkGPUEuler3DTransform.h
Common/OpenCL/Filters/itkGPUMatrixOffsetTransformBase.h
Common/OpenCL/Filters/itkGPUMatrixOffsetTransformBase.hxx
Common/OpenCL/Filters/itkGPUSimilarity2DTransform.h
Common/OpenCL/Filters/itkGPUSimilarity3DTransform.h
Common/OpenCL/Kernels/GPUMatrixOffsetTransformBase.cl
Common/Transforms/itkAdvancedMatrixOffsetTransformBase.h

Addressed the compile errors reported by Georg Walther (@georg-walther), issue #647 "[GPU] Compilation fails with ELASTIX_USE_OPENCL: ON", including:
> error: ‘GetInverseMatrix()’ is private within this context
> error: ‘GPUAdvancedEuler3DTransform’ has no member named ‘GetOffset’
`GetInverseMatrix()` was used only to pass the inverse matrix to the `inverse_matrix` data members of `GPUMatrixOffsetTransformBase` (the OpenCL implementation), but these data members were never actually used, so they could simply be removed. All `GetCPUInverseMatrix()` member functions then also appeared unnecessary.
`AdvancedMatrixOffsetTransformBase::GetOffset()` needed to be restored (albeit only `protected`), as it was removed by pull request https://github.com/SuperElastix/elastix/pull/544 commit …

COMP: Fix OPENCL errors GetInverseMatrix() and GetOffset() (issue #647)

---

CMake/elastixExportTarget.cmake
CMakeLists.txt
ElastixConfig.cmake.in

Created variables in ElastixConfig.cmake to specify installation path
and build path uniformly.

Install ElastixTargets.cmake file

---

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.h
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Common/LineSearchOptimizers/itkMoreThuenteLineSearchOptimizer.cxx
Common/LineSearchOptimizers/itkMoreThuenteLineSearchOptimizer.h
Common/Transforms/itkBSplineDerivativeKernelFunction2.h
Common/Transforms/itkBSplineKernelFunction2.h
Common/Transforms/itkBSplineSecondOrderDerivativeKernelFunction2.h
Common/itkComputePreconditionerUsingDisplacementDistribution.h
Common/itkComputePreconditionerUsingDisplacementDistribution.hxx
Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.h
Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx
Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.h
Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.hxx
Core/ComponentBaseClasses/elxFixedImagePyramidBase.h
Core/ComponentBaseClasses/elxFixedImagePyramidBase.hxx
Core/ComponentBaseClasses/elxMovingImagePyramidBase.h
Core/ComponentBaseClasses/elxMovingImagePyramidBase.hxx
Core/ComponentBaseClasses/elxResamplerBase.h
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Main/elxParameterObject.cxx
Core/Main/elxParameterObject.h
Core/elxProgressCommand.cxx
Core/elxProgressCommand.h

Removed the ampersand (`&`) from declarations of "in" (`const`) parameters of a fundamental type (bool, unsigned int, unsigned long, float, double).
Following C++ Core Guidelines, April 10, 2022, "For “in” parameters, pass cheaply-copied types by value and others by reference to `const`":
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f16-for-in-parameters-pass-cheaply-copied-types-by-value-and-others-by-reference-to-const
Also removed any `virtual` keyword from the declarations of those member functions, as the change from pass by-reference to pass by-value would break any possible `override` anyway. (But no such `override` was found anyway). Following the guideline, "Don’t make a function virtual without reason"

STYLE: Pass parameters of fundamental types by value, not by `const` ref

---

Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.h
Core/Main/itkTransformixFilter.hxx

The same functionality was added in Elastix/TransformixFilter in commit cf968a92abb00a12aa419671f09d9c7c97d78ed8 for thread safety.

ENH: Add DisableOutput() to itkElastixRegistration/itkTransformix

---

Testing/PythonTests/CMakeLists.txt
Testing/PythonTests/transformix_test.py

Environment variables are also supported by Visual Studio Test Explorer .runsettings files, for example:
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
<RunConfiguration>
<EnvironmentVariables>
<TRANSFORMIX_EXE>C:\Bin\elastix\bin\Debug\transformix.exe</TRANSFORMIX_EXE>
<TRANSFORMIX_TEST_TEMP_DIR>C:\src\elastix\Testing\PythonTests\temporary</TRANSFORMIX_TEST_TEMP_DIR>
</EnvironmentVariables>
</RunConfiguration>
</RunSettings>

ENH: Pass TransformixTest parameters as environment variables to Python

---

Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/elxCorrespondingPointsEuclideanDistanceMetric.hxx
Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx
Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx
Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx
Components/Metrics/StatisticalShapePenalty/elxStatisticalShapePenalty.hxx
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Optimizers/ConjugateGradient/elxConjugateGradient.hxx
Components/Optimizers/FullSearch/elxFullSearchOptimizer.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Components/Optimizers/QuasiNewtonLBFGS/elxQuasiNewtonLBFGS.hxx
Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.hxx
Core/ComponentBaseClasses/elxFixedImagePyramidBase.hxx
Core/ComponentBaseClasses/elxMovingImagePyramidBase.hxx
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Configuration/elxConfiguration.cxx
Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixTemplate.hxx
Core/Kernel/elxTransformixMain.cxx
Testing/elxComputeOverlap.cxx
Testing/elxImageCompare.cxx
Testing/elxInvertTransform.cxx
Testing/elxTransformParametersCompare.cxx
Testing/itkMevisDicomTiffImageIOTest.cxx
Testing/itkThinPlateSplineTransformPerformanceTest.cxx
Testing/itkThinPlateSplineTransformTest.cxx

Various style improvements, preparing to reuse code from `elx::TransformBase<TElastix>::TransformPointsSomePoints` (as needed to re-implement the transformix executable in terms of the library)

Remove redundant `GetElxResamplerBase()->GetAsITKBaseType()` calls, and do other style improvements

---

Core/CMakeLists.txt
Core/Main/elastix.cxx
Core/Main/elxMainExeUtilities.cxx
Core/Main/elxMainExeUtilities.h
Core/Main/transformix.cxx

Caught and reported exceptions from the `main` function of elastix and transformix, which would otherwise just cause the program to terminate unexpectedly.
Addressed LLVM 14.03 LLVM clang-tidy check `bugprone-exception-escape` regarding `main`:
> Finds functions which may throw an exception directly or indirectly, but they should not.
https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-exception-escape.html

ENH: Report any exception from elastix and transformix `main` functions

---

Core/CMakeLists.txt
Core/Main/elastix.cxx
Core/Main/elxMainExeUtilities.cxx
Core/Main/elxMainExeUtilities.h
Core/Main/transformix.cxx
Core/elxGitRevisionInfo.h.in
Testing/PythonTests/transformix_test.py

With this commit, the output of `elastix.exe --extended-version` will look something like this:
elastix version: 5.0.1
Git revision SHA: 81eb3b35e0fe24db05679254b2394b4201b047e2
Git revision date: Fri Jul 8 11:46:04 2022 +0200
Build date: Jul  8 2022 15:15:40
Compiler: Visual C++ version 192930145.0
Memory address size: 64-bit
CMake version: 3.23.1
ITK version: 5.3.0
Triggered by issue #671 "Version numbering of develop branch", submitted by Sebastian van der Voort (@Svdvoort).

ENH: Add git revision info to commandline output of `--extended-version`

---

Core/Configuration/elxConfiguration.cxx
Core/Configuration/elxConfiguration.h
Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixMain.h

Follows C++ Core Guidelines (July 13, 2022), "Prefer initialization to assignment in constructors", at
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c49-prefer-initialization-to-assignment-in-constructors

STYLE: Implement ElastixMain, Configuration constructors by `= default`

---

.github/workflows/ElastixGitHubActions.yml
Testing/CI/Azure/ci.yml

Addresses a warning at https://dev.azure.com/kaspermarstal/Elastix/_build/results?buildId=3342&view=logs&j=d9d370b1-18a3-5231-ee95-54c0a379145c saying:
> ##[warning]The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead. For more details see https://github.com/actions/virtual-environments/issues/5583
May also be relevant to issue https://github.com/SuperElastix/elastix/issues/650 "MacOS GitHub Actions, Azure Pipelines fatal error: ‘omp.h’ file not found"

COMP: Upgrade Azure Pipelines and GitHub Actions yml files to macOS-11

---

Common/GTesting/elxTransformIOGTest.cxx

Allowing ITK_LEGACY_REMOVE=0N for ITK version >= 5.3rc04, which made those constructors `explicit`:
- ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3237 commit https://github.com/InsightSoftwareConsortium/ITK/commit/8825834406356a66705437b74c843a54a47c57c3 "ENH: Declare converting `Point(v)` constructors `explicit`"
- ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3255 commit https://github.com/InsightSoftwareConsortium/ITK/commit/abb88ccc48e79656e1481ad3ad995ae3d370539d "ENH: Make Vector constructor from scalar explicit, unless LEGACY enabled"

STYLE: Make conversion from value to itk::Point or itk::Vector explicit

---

Common/GTesting/elxConversionGTest.cxx
Core/Install/elxConversion.h

`itk::FixedArray::size()` is included with ITK from version v5.2rc01, and was added on May 10, 2020, with pull request https://github.com/InsightSoftwareConsortium/ITK/pull/1800  commit https://github.com/InsightSoftwareConsortium/ITK/commit/38939ff86d97777e8d507963c13a2221e86b601e "ENH: Add data() and size() member functions to FixedArray" by Pablo Hernandez-Cerdan.

STYLE: Remove `GetNumberOfElements`, now that ITK has FixedArray::size()

---

Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx
Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx
Components/Metrics/StatisticalShapePenalty/elxStatisticalShapePenalty.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx

Related to issue #698 "Double-check limitations of vtk file support"

Replace VTKPolyDataReader with itk::MeshFileReader, remove mesh reader/writer typefdefs

---

Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx
Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx

`itk::WriteMesh` was introduced with ITK v5.3rc03 by pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2880 commit
https://github.com/InsightSoftwareConsortium/ITK/commit/bd2a2e484dc5fd7e59082736f75efd18a95fd1e3 "ENH: Add itk::WriteMesh", by Matt McCormick.

STYLE: Replace `itk::MeshFileWriter` with `itk::WriteMesh` (3x)

---

Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx
Core/Main/itkTransformixFilter.h
Core/Main/itkTransformixFilter.hxx

Supported transforming points as follows:
transformixFilter.SetInputMesh(inputMesh);
transformixFilter.Update();
outputMesh = transformixFilter.GetOutputMesh();
Using the OutputImagePixelType of TransformixFilter as `TPixelType` template argument of the mesh type, as was suggested by Matt McCormick (@thewtex).

ENH: Support transforming points of Mesh objects by itk::Transformix API

---

Common/CMakeLists.txt
Common/GTesting/CMakeLists.txt
Common/GTesting/elxDefaultConstructGTest.cxx
Common/GTesting/elxTransformIOGTest.cxx
Common/ParameterFileParser/itkParameterFileParser.cxx
Common/Transforms/itkRecursiveBSplineTransform.h
Common/elxDefaultConstruct.h
Core/ComponentBaseClasses/elxTransformBase.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx

As it is used quite often now, it appears helpful for readability to shorten its name.

STYLE: Rename `DefaultConstructibleSubclass` to `DefaultConstruct`

---

CONTRIBUTING.md
README.md
Testing/Dashboard/elxDashboardCommon.cmake
Testing/elx_nightly_dashboard.py

Part of issue https://github.com/SuperElastix/elastix/issues/718 Rename the default branch of elastix git from "develop" to "main"

ENH: Replaced occurrences of git branch name "develop" with "main"

---

Common/GTesting/CMakeLists.txt
Common/GTesting/itkImageGridSamplerGTest.cxx
Common/ImageSamplers/itkImageGridSampler.hxx

Addresses issue https://github.com/SuperElastix/elastix/issues/722 "ImageGridSampler default-constructor fills its m_SampleGridSpacing twice"
Follow-up to:
- commit 2fc2c495837f64416263fa7c5d1e2bc4e3e061fa "ENH: HUGE merge of the performance branch", Marius Staring (@mstaring), November 14, 2013
- commit be9fd66ced2673bd4063879ae529a2f2b9c0ac00 "BUG: Initialize m_SampleGridSpacing with zeros in constructor to prevent Valgrind MemCheck errors", Coert Metz (@coertmetz), May 13, 2013

BUG: Fill `ImageGridSampler::m_SampleGridSpacing` only once, with ones

---

Common/itkMeshFileReaderBase.h
Common/itkMeshFileReaderBase.hxx

Removed `this->` when referring to its own data member. Removed unnecessary `std::string::c_str()` calls, unnecessary `std::fstream::close()` calls, and unreachable `return` statements.

STYLE: Cleanup MeshFileReaderBase, defaulting its default-constructor

---

Common/OpenCL/ITKimprovements/itkOpenCLKernels.h.in
Core/Install/elxOpenCLSupportedImageTypes.h.in
Core/Install/elxSupportedImageTypes.h.in

Follow-up to pull request https://github.com/SuperElastix/elastix/pull/339 commit 505bb39c7349ae786b4d61f5d7450ac606d8c2fa "COMP: Remove double underscores from include guards of header files", 29 October 2020.

COMP: Remove double underscores from include guards of "*h.in" files

---

.github/workflows/ElastixGitHubActions.yml
CMakeLists.txt

By adding CMake variables ${OpenMP_CXX_INCLUDE_DIRS} and ${OpenMP_CXX_LIBRARIES}

Fix MacOS CI errors, "‘omp.h’ file not found", "Undefined symbols"

---

Common/OpenCL/Factories/itkGPUResampleImageFilterFactory.h
Common/OpenCL/Filters/itkGPUResampleImageFilter.h
Common/OpenCL/Filters/itkGPUResampleImageFilter.hxx
Common/OpenCL/ITKimprovements/itkGPUImage.h
Components/FixedImagePyramids/OpenCLFixedGenericPyramid/elxOpenCLFixedGenericPyramid.hxx
Components/MovingImagePyramids/OpenCLMovingGenericPyramid/elxOpenCLMovingGenericPyramid.hxx
Testing/itkGPUFactoriesTest.cxx
Testing/itkGPUGenericMultiResolutionPyramidImageFilterTest.cxx

This PR provides the cosmetic changes needed for PR https://github.com/SuperElastix/elastix/pull/243 together with a small addition. Hence, full credits should be given to @squll1peter for writing up the original PR and resolving the CL_OUT_OF_RESOURCES issue discussed in PR https://github.com/SuperElastix/elastix/pull/243 and issue https://github.com/SuperElastix/elastix/issues/70!  Two different bugs are actually solved. In short summary:
1. The CL_OUT_OF_RESOURCES error. This bug was created because `itk::SmoothingRecursiveGaussianImageFilter` was overriding (here: https://github.com/InsightSoftwareConsortium/ITK/blob/3c6de8f009aadfab8f801070237cb699f5c895cb/Modules/Filtering/Smoothing/include/itkSmoothingRecursiveGaussianImageFilter.h#L80-L87) the internal pixel type of …

BUG: Fix OpenCL pyramids (original: https://github.com/SuperElastix/elastix/pull/243)

---

Testing/CI/Azure/ci.yml

Because of issue https://github.com/SuperElastix/elastix/issues/739 "MacOS Azure Pipelines fails to install requirements.txt for Python".
The intention is now to defer the issue for a while.

COMP: Remove tests from MacOS job on Azure Pipelines CI

---

Common/OpenCL/Filters/itkGPUMatrixOffsetTransformBase.hxx
Testing/CMakeLists.txt
Testing/itkGPUBSplineDecompositionImageFilterTest.cxx
Testing/itkGPUCastImageFilterTest.cxx
Testing/itkGPUFactoriesTest.cxx
Testing/itkGPURecursiveGaussianImageFilterTest.cxx
Testing/itkGPUResampleImageFilterTest.cxx
Testing/itkGPUShrinkImageFilterTest.cxx
Testing/itkGPUSmoothingRecursiveGaussianImageFilterTest.cxx
Testing/itkOpenCLBufferTest.cxx
Testing/itkOpenCLContextTest.cxx
Testing/itkOpenCLEventTest.cxx
Testing/itkOpenCLImageTest.cxx
Testing/itkOpenCLKernelManagerTest.cxx
Testing/itkOpenCLKernelToImageBridgeTest.cxx
Testing/itkOpenCLSamplerTest.cxx
Testing/itkOpenCLSimpleTest.cxx
Testing/itkOpenCLSizeTest.cxx
Testing/itkOpenCLVectorTest.cxx

The tests for any GPUMatrixOffset transform (Affine, Euler and Similarity) were failing since the final output from the GPU was an empty image - it did not cause any code crash, but high RMSE between CPU and GPU instead. I think that the error was introduced by commit https://github.com/SuperElastix/elastix/commit/b556886c26c0a9301d81325e6dbb9d4365c68a76, when fixing issue https://github.com/SuperElastix/elastix/issues/647. The `inverse_matrix` data member of the structs `GPUMatrixOffsetTransformBase1D/2D/3D` were the only ones not removed, effectively passing unitialized memory to the GPU. This PR fixes that. In addition, it adds a random seed as in commit https://github.com/SuperElastix/elastix/commit/bb0b4fb9177ca3987d394769988b2af765fec6e7, and removes the calls to `ReleaseContext()` …

BUG: Fix OpenCL resampler for GPUMatrixOffset transforms + tests

---

ElastixConfig.cmake.in

When elastix is embedded with add_subdirectory in cases like CMake FetchContent, the targets will be created, and we should not try to use the target exports file.

BUG: Do not try to load targets file when embedded

---

Core/Main/GTesting/itkTransformixFilterGTest.cxx
Core/Main/itkTransformixFilter.h
Core/Main/itkTransformixFilter.hxx

Added support for single and composite transforms (itk::CompositeTransform). Tested with itk::TranslationTransform, itk::AffineTransform, itk::Euler2DTransform, itk::Euler3DTransform, itk::Similarity2DTransform, itk::Similarity3DTransform, and itk::BSplineTransform.

Add `TransformixFilter::SetTransform`

---

Common/ParameterFileParser/itkParameterFileParser.cxx
Common/ParameterFileParser/itkParameterFileParser.h

Following C++ Core Guidelines, September 23, 2022, _Use an unnamed (anonymous) namespace for all internal/non-exported entities_, https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf22-use-an-unnamed-anonymous-namespace-for-all-internalnon-exported-entities
Did a few more style improvements in itkParameterFileParser.cxx

Move the private member functions of ParameterFileParser to an unnamed namespace

---

Common/GTesting/elxConversionGTest.cxx
Common/ParameterFileParser/itkParameterFileParser.cxx
Common/ParameterFileParser/itkParameterFileParser.h

Allows specifying a parameter map by the content of a parameter text file, without having to have the file on disk.

ENH: Add `ParameterFileParser::ConvertToParameterMap(text)`

---

Core/Main/itkTransformixFilter.h

The ITKElastix Python wrapper might prefer a raw pointer (`const MeshType *`) as parameter type, instead of `MeshType::ConstPointer`.

COMP: Use `itkSetConstObjectMacro` for TransformixFilter InputMesh

---

Components/Metrics/DistancePreservingRigidityPenalty/elxDistancePreservingRigidityPenaltyTerm.hxx
Components/Metrics/RigidityPenalty/elxTransformRigidityPenaltyTerm.hxx
Components/Transforms/DeformationFieldTransform/elxDeformationFieldTransform.hxx
Core/Kernel/elxElastixBase.h

The `OutputDirection` of an `itk::ChangeInformationImageFilter` is already the identity matrix by default. It was already the identity matrix by default with ITK commit e974315f3ebec0c35db4d717cfca59ba95c37c9f "ENH: now supports changing direction." by Bill Lorensen, April 18, 2005: https://github.com/InsightSoftwareConsortium/ITK/blob/e974315f3ebec0c35db4d717cfca59ba95c37c9f/Code/BasicFilters/itkChangeInformationImageFilter.txx#L46

STYLE: Remove redundant SetOutputDirection(GetIdentity()) calls

---

Core/ComponentBaseClasses/elxTransformBase.hxx

These casts appear entirely superfluous, as GetAsITKBaseType() already returns a `const ITKBaseType *`.

STYLE: Remove `const_cast<const ITKBaseType *>` from TransformBase (3x)

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.h
Common/Transforms/itkAdvancedCombinationTransform.h
Common/Transforms/itkAdvancedImageMomentsCalculator.h
Common/Transforms/itkBSplineDerivativeKernelFunction2.h
Common/Transforms/itkBSplineKernelFunction2.h
Common/Transforms/itkBSplineSecondOrderDerivativeKernelFunction2.h
Common/Transforms/itkRecursiveBSplineTransformImplementation.h
Common/itkAdvancedLinearInterpolateImageFunction.h
Common/itkAdvancedRayCastInterpolateImageFunction.h
Common/itkComputeDisplacementDistribution.h
Common/itkNDImageTemplate.h
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.h
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.h
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.h
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.h
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.h
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.h
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.h
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.hxx

According to deft_code, answering "When should I write the keyword 'inline' for a function/method?", November 18, 2009:
> Generally, declaring templates `inline` is pointless, as they have the linkage semantics of `inline` already.
https://stackoverflow.com/questions/1759300/when-should-i-write-the-keyword-inline-for-a-function-method/1759575#1759575

STYLE: Remove unnecessary `inline` keywords from "itk*.h" files

---

Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxElastixTemplate.hxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx
Core/Main/itkTransformixFilter.h
Core/Main/itkTransformixFilter.hxx

This commit adds two `itk::TransformixFilter` member functions, `ComputeSpatialJacobianDeterminantImage()` and `ComputeSpatialJacobianMatrixImage()`, both producing an `itk::Image`.
It has replaced the old `elx::TransformBase` member functions ComputeDeterminantOfSpatialJacobian() and ComputeSpatialJacobian() by `ComputeAndWriteSpatialJacobianDeterminantImage()` and `ComputeAndWriteSpatialJacobianMatrixImage()`, respectively. And it has added `elx::TransformBase` member functions `ComputeSpatialJacobianDeterminantImage()` and `ComputeSpatialJacobianMatrixImage()`, which just produce the image, but do not write the result to disk.

ENH: Add TransformixFilter SpatialJacobian, DeterminantOfSpatialJacobian

---

Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx

Preliminary step to eventually add support for Transform object retrieval.

ENH: Add `ElastixRegistrationMethod::m_ElastixMain`

---

Common/Transforms/elxTransformIO.h
Core/Kernel/elxElastixBase.h
Core/Kernel/elxElastixTemplate.h
Core/Kernel/elxElastixTemplate.hxx
Core/Kernel/elxTransformixMain.cxx
Core/Kernel/elxTransformixMain.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.h
Core/Main/itkTransformixFilter.hxx

Added public functions to retrieve the transformation(s) produced by elastix through the `itk::ElastixRegistrationMethod` interface:
- ElastixRegistrationMethod::GetCombinationTransform()
- TransformixFilter::SetCombinationTransform(transform)
-  ~~ElastixRegistrationMethod::GetCompositeTransform()~~
- ElastixRegistrationMethod::GetNumberOfTransforms()
- ElastixRegistrationMethod::GetNthTransform(n)
- ElastixRegistrationMethod::ConvertToItkTransform(transform)
The transform return by `ConvertToItkTransform(transform)` is a standard ITK transform. Note that this function may throw an exception, if there is no corresponding ITK transform for the actual elastix transform.
The transforms returned by `GetCombinationTransform()` and `GetNthTransform(n)` are specific to elastix. However, the …

ElastixRegistrationMethod transform objects

---

Testing/PythonTests/transformix_test.py

Addressed two messages:
- warning W0301: Unnecessary semicolon [W:unnecessary-semicolon]
- convention C0301: Line too long (106/100) [C:line-too-long]

COMP: Fix PyLint [W:unnecessary-semicolon], [C:line-too-long] messages

---

CMakeLists.txt
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/FullSearch/itkFullSearchOptimizer.cxx
Components/Optimizers/QuasiNewtonLBFGS/itkQuasiNewtonLBFGSOptimizer.cxx
Components/Optimizers/RSGDEachParameterApart/itkRSGDEachParameterApartBaseOptimizer.cxx

CMake no longer adds /W3 automatically, by default (from CMake 3.15), so the Visual C++ warning level has dropped unintentionally from /W3 to /W1 with pull request #631 commit a349180014ee0824a2e9a9763803bc25d5fb63d7, "ENH: Upgrade cmake_minimum_required from 3.10.2 to 3.16.3, following ITK", 26 March 2022.
See also:
"MSVC warning flags are not in CMAKE_<LANG>_FLAGS by default"
https://cmake.org/cmake/help/latest/policy/CMP0092.html
"MSVC: Do not add /W3 to CMAKE_<LANG>_FLAGS by default"
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/3250

Restore MSVC warning level (`/W3`) and fix the warnings

---

Common/itkComputePreconditionerUsingDisplacementDistribution.hxx
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/FullSearch/elxFullSearchOptimizer.hxx
Components/Optimizers/PreconditionedGradientDescent/elxPreconditionedGradientDescent.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Core/Configuration/elxConfiguration.cxx

Follow-up to pull request #786 Chain consecutive insertions (`<<`) to the same "xout" stream, replace `std::endl` by `\n`

Chain insertions (`<<`) to the same "xout" stream in Configuration and Optimizers

---

Common/CMakeLists.txt

`clock_gettime()` was only used by the `Timer` class: commit 2a25d6c6504c5e6aad71ecfa5ddd9978f281db08, 16 February 2011. This `Timer` class was removed by commit e058d54e7fc8cc2101b7c03793408e84c85c3b53, 6 May 2014.

STYLE: No longer link to "rt", because clock_gettime() is no longer used

---

Components/Optimizers/AdaGrad/elxAdaGrad.h
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.h
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.h
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.h
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/PreconditionedGradientDescent/elxPreconditionedGradientDescent.h
Components/Optimizers/PreconditionedGradientDescent/elxPreconditionedGradientDescent.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.h
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Core/ComponentBaseClasses/elxOptimizerBase.h
Core/ComponentBaseClasses/elxOptimizerBase.hxx

Removed the duplicated `PrintSettingsVector` implementations from six optimizers:
AdaGrad
AdaptiveStochasticGradientDescent
AdaptiveStochasticLBFGS
AdaptiveStochasticVarianceReducedGradient
PreconditionedGradientDescent
PreconditionedStochasticGradientDescent

STYLE: Move PrintSettingsVector and Settings types to `OptimizerBase`

---

.github/workflows/ElastixGitHubActions.yml

Addresses warnings at https://github.com/SuperElastix/elastix/actions/runs/3854586355 saying
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2, actions/setup-python@v1, lukka/get-cmake@v3.18.3, actions/upload-artifact@v2

COMP: Update GitHub actions that were still using Node.js 12

---

dox/externalproject/ElastixTranslationExample.cxx

Such an exception occurred when trying to run ElastixTranslationExample with an elastix build that was configured to have a minimal number of components.

ENH: Catch exceptions in externalproject/ElastixTranslationExample

---

Core/Main/elastix.cxx
Core/Main/elxMainExeUtilities.cxx
Core/Main/elxMainExeUtilities.h
Core/Main/transformix.cxx

Eases migration of the logging framework.

STYLE: Replace PrintArguments with MakeStringOfCommandLineArguments

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/itkComputePreconditionerUsingDisplacementDistribution.hxx

During today's internal weekly elastix sprint, we agreed that the "itk*.*" files in elastix/Common should not use the elastix specific logging system (neither the old xout system, nor the new one that is under development). @mstaring @stefanklein

Remove xout from "itk*.*" files in elastix/Common

---

Core/elxProgressCommand.cxx

Note that this commit does not yet address issue https://github.com/SuperElastix/elastix/issues/756 "Executable progress indication appears suppressed on Windows"

STYLE: Replace `xl::xout["coutonly"]` with std::cout, in ProgressCommand

---

Core/Kernel/elxElastixMain.h
Core/Kernel/elxMainBase.h
Core/Kernel/elxTransformixMain.cxx

Made clearer that TransformixMain does not need to use the `InitialTransform` property of ElastixMain. `MainBase` is the common base class of TransformixMain and ElastixMain (from pull request https://github.com/SuperElastix/elastix/pull/806 commit c2a5de712dd14ade6f36cc45b443e8f7113b501d). So it appears preferable to move InitialTransform from MainBase to the elastix specific class ElastixMain.
Removed the `SetInitialTransform` call from TransformixMain, as it does not seem to make sense. Discussed with Marius (@mstaring) at our weekly internal elastix sprint.

STYLE: Move `InitialTransform` from MainBase to ElastixMain

---

Common/ParameterFileParser/itkParameterMapInterface.cxx
Common/ParameterFileParser/itkParameterMapInterface.h
Core/Configuration/elxConfiguration.h

@stefanklein FYI We agreed at today's sprint that those typical "WARNING: The parameter..." messages from `ParameterMapInterface` should be suppressed when the user specifies that only error messages should be displayed (command-line option `-loglevel error`).

Suppress "WARNING: The parameter..." logging when level is `error` (errors only)

---

Core/Configuration/elxConfiguration.cxx
Core/Kernel/elxElastixTemplate.hxx
Core/Kernel/elxlog.cxx
Core/Kernel/elxlog.h

Replaced `log::to_log_file` with `log::info_to_log_file`, which _only_ writes to file when the log level is `info` (which is the default).
ElastixTemplate::CreateTransformParameterFile and Configuration::PrintParameterFile() no longer write to file when the log level is `warning`, `error`, or `off`.

ENH: Only write parameter file to log file when level = `info` (default)

---

Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx
Common/Transforms/itkCyclicBSplineDeformableTransform.hxx
Common/Transforms/itkRecursiveBSplineTransform.hxx

Removed unnecessary local variables, `numberOfWeights`, `indicesArray`, `indices`, `transformedPoint`, `outputPoint`, and `basePointer` from both `AdvancedBSplineDeformableTransform` and `CyclicBSplineDeformableTransform`.
A small but significant improvement of the runtime performance (more than 6%) was observed, from ~3.0 sec. (before this commit) down to ~2.8 sec. (with this commit), when calling `AdvancedBSplineDeformableTransform::TransformPoint` 10'000'000 times.
Also did some code clean-up  within `RecursiveBSplineTransform::TransformPoint`
Follow-up to pull request #582 "Code cleanup BSpline Transforms from Common/Transforms" (January 17, 2022)
@ntatsisk Can you see if this obvious code clean-up makes the regular (non-recursive) BSpline Transform any faster?

PERF: Simplify TransformPoint member functions of BSpline Transform class templates

---

Core/CMakeLists.txt
Core/Install/elxComponentInstaller.h
Core/Install/elxIncludes.h
Core/Install/elxMacro.h

Moved most of the code from the definition of `elxInstallMacro(_classname)` from "elxMacro.h" to a new file "elxComponentInstaller.h", and a new class template, `elx::ComponentInstaller`.
Aims to improve code readability and ease further maintenance.

STYLE: Add elx::ComponentInstaller, simplify elxInstallMacro(_classname)

---

Core/Kernel/elxlog.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/itkElastixLogLevel.h
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.h
Core/Main/itkTransformixFilter.hxx

Added `GetLogLevel` and `SetLogLevel` member functions to both `itk::ElastixRegistrationMethod` and `itk::TransformixFilter`, allowing the user to reduce the amount of logging from elastix and transformix, both to the log file and the console (standard output).

ENH: Add `ElastixLogLevel` to the ITK interface

---

Core/Kernel/elxElastixMain.cxx

Fixed the errors that occur when ELASTIX_USE_OPENCL is enabled, saying:
> elxElastixMain.cxx(84,10): error C2039: 'CreateOpenCLContext': is not a member of 'itk'
...
> elxElastixMain.cxx(95,26): error C3861: 'CreateOpenCLLogger': identifier not found
These errors were introduced with pull request https://github.com/SuperElastix/elastix/pull/806 commit c2a5de712dd14ade6f36cc45b443e8f7113b501d "STYLE: Add `MainBase`, a base class of ElastixMain and TransformixMain", and reported by Konstantinos Ntatsis (@ntatsisk).

COMP: Fix OpenCL elxElastixMain.cxx compilation errors

---

Testing/CI/Azure/ci.yml

Further extended the exclusion of specific files from the Azure Pipelines CI runs. Those files were not tested by the CI anyway.
Inspired by ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3930 commit https://github.com/InsightSoftwareConsortium/ITK/commit/eb5ca2585a62e5031d137a46194dd944600e758b "COMP: Exclude Utilities/Maintenance and documentation files from AZP CI"

COMP: Exclude Doxygen related files from Azure Pipelines CI

---

Common/OpenCL/Filters/itkGPUInterpolatorCopier.hxx
Components/Resamplers/OpenCLResampler/elxOpenCLResampler.hxx

While doing some benchmarks for issue: https://github.com/SuperElastix/elastix/issues/226, I noticed that when `BSplineInterpolator` is being used then `Transformix` runs faster in the CPU than the GPU. The order of the `itk::ProcessObject`s that is called is the following:
```
######################################### CPU TRANSFORMIX #########################################
class itk::ImageFileReader<class itk::Image<float,3>,class itk::DefaultConvertPixelTraits<float> >
class itk::TransformixFilter<class itk::Image<float,3> >
class itk::BSplineDecompositionImageFilter<class itk::Image<float,3>,class itk::Image<double,3> >
class elastix::MyStandardResampler<class elastix::ElastixTemplate<class itk::Image<float,3>,class itk::Image<float,3> > >
class …
```

PERF: OpenCL resampler speedup when using BSplineInterpolator

---

Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/elxProgressCommand.cxx
Core/elxProgressCommand.h

Allows enabling showing progress percentages at the console (standard output), by adding the following elastix parameter:
(ShowProgressPercentage "true")
As I discussed last week with Marius Staring (@mstaring).
This pull request aims to supersede PR #826 "Show progress percentage only when requested by user" (which would instead add an extra command-line option `-progress on`, and `ShowProgressPercentageOn`/`Off` member functions.) It also addresses issue #756 "Executable progress indication appears suppressed on Windows".

Support "ShowProgressPercentage" parameter (false by default)

---

Components/Resamplers/OpenCLResampler/elxOpenCLResampler.hxx

Fixed an OpenCL compile error, saying:
> Components\Resamplers\OpenCLResampler\elxOpenCLResampler.hxx(73,9): error C2039: 'm_ShowProgress': is not a member of 'elastix::Open
CLResampler<ElastixType>'
Reported by Konstantinos Ntatsis (@ntatsisk).
Error was introduced with commit e39de3ab5c80ec947ccd68e243b27c6f098632e2 "STYLE: Remove `ResamplerBase::m_ShowProgress` (which was always true)"

COMP: error C2039: 'm_ShowProgress': is not a member of OpenCLResampler

---

Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxElastixBase.cxx
Core/Kernel/elxElastixBase.h
Core/Main/elastixlib.cxx
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.hxx

Abandoned the hack that was introduced by commit f9a51b81bfb7d631b75c9ceba1c4638787f72158 (Coert Metz, @coertmetz, June 13, 2013), which said:
> Instead of a filename, the initial transform parameters are referenced to with an index and transform parameters of all registration steps are stored in a vector of configuration objects. It is still a kind of hack, but given the current elastix architecture at least a practical one.
Instead, simply assumed that the configurations are stored in the vector in the order of which they should be applied.   (Which was always the case anyway.)
Aims to make the meaning of "InitialTransformParametersFileName" straightforward and unambiguous, and make it easier for end-users to create a sequence of transformation parameter maps in memory, as input to the …

Find previous configuration without interpreting "InitialTransformParametersFileName" as index value

---

Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxElastixBase.cxx
Core/Kernel/elxElastixBase.h
Core/Kernel/elxMainBase.cxx
Core/Kernel/elxMainBase.h
Core/Kernel/elxTransformixMain.cxx

Renamed ElastixBase and MainBase member variables `m_Configurations` to `m_TransformConfigurations`. Also renamed ElastixBase member function `GetConfiguration(size_t)`  to `GetTransformConfiguration(size_t)`.
Aims to clarify that these particular configurations represent transformations (rather than arbitrary sets of registration parameters).

STYLE: Rename "Configurations" from Kernel to "TransformConfigurations"

---

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

Triggered by 
- https://github.com/SuperElastix/elastix/pull/857
Also did some code cleanup of the GoogleTest of `itk::ElastixRegistrationMethodGTest`.

Test SetInitialTransformParameterObject  on a registration object of multiple parameter maps

---

Core/Main/itkElastixRegistrationMethod.hxx

When `ElastixRegistrationMethod::GenerateData()` does a sequence of multiple registrations, only the first one should use the parameter maps from the InitialTransformParameterObject. _Right?_  😃 
Follow-up to pull request https://github.com/SuperElastix/elastix/pull/856 commit 48c64583c8514eac7fa9ad46848be9d100ac80c9 "Add `SetInitialTransformParameterObject` to `ElastixRegistrationMethod`"

BUG: Only use InitialTransformParameterObject during first registration

---

Components/Registrations/MultiMetricMultiResolutionRegistration/elxMultiMetricMultiResolutionRegistration.hxx
Components/Registrations/MultiResolutionRegistration/elxMultiResolutionRegistration.hxx
Components/Registrations/MultiResolutionRegistrationWithFeatures/elxMultiResolutionRegistrationWithFeatures.hxx
Components/elxGenericPyramidHelper.h
Core/ComponentBaseClasses/elxFixedImagePyramidBase.hxx
Core/ComponentBaseClasses/elxMovingImagePyramidBase.hxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

Following commit f84ac0d1094ebdb13e456b1b8cf1f6f9bfcd0a38 "ENH: First checkin of a generic pyramid...", February 2, 2012.
Addressed issue https://github.com/SuperElastix/elastix/issues/858 MovingImagePyramidBase, FixedImagePyramidBase have different defaults for "NumberOfResolutions"

Set NumberOfResolutions = 3 by default, throw exception if NumberOfResolutions is 0

---

Core/Main/GTesting/elxCoreMainGTestUtilities.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx
Core/Main/elxParameterObject.cxx
Core/Main/elxParameterObject.h
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.hxx
dox/externalproject/ElastixTranslationExample.cxx

For your information @kaspermarstal  😃

Deprecate ParameterObject member functions Get/SetParameterMap in favor of Get/SetParameterMaps

---

CMakeLists.txt
dox/externalproject/CMakeLists.txt

Following ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3969 commit https://github.com/InsightSoftwareConsortium/ITK/commit/513507e4c70172d5431563f89dc77c6bae1ad5b1 "ENH: Upgrade ITK from C++14 to C++17"
Follow-up to pull request https://github.com/SuperElastix/elastix/pull/513 commit d98d9c0eeb2e826e7733541ebd4edeac3fa86ec1 "ENH: Upgrade elastix from C++11 to C++14".

ENH: Upgrade elastix from C++14 to C++17

---

Core/CMakeLists.txt
Core/Main/elxLibUtilities.cxx
Core/Main/elxLibUtilities.h
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.hxx

Basically reverting commit faf20af8f0c950038031571709794edef54a5dfe "ENH: Allow ElastixFilter and TransformixFilter users to manually specify internal pixel types. Previously these was automatically deduced from instantiated template parameters" by Kasper Marstal (@kaspermarstal), September 4, 2016.
Discussed "in person" with Marius Staring, this afternoon. With the current design, the internal pixel types _must be_ the same as the pixel types of the `ElastixRegistrationMethod<TFixedImage, TMovingImage>` and the `TransformixFilter<TMovingImage>` template arguments anyway. 
Also the subject of this discussion:
- https://github.com/SuperElastix/elastix/discussions/872

Deduce internal pixel types from template parameters of interface

---

Core/Main/GTesting/elxCoreMainGTestUtilities.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

Tests that for a "do nothing" registration, the output after registration.SetInitialTransformParameterObject(transformParameterObject) is equal to the transformix output after the corresponding transformix.SetTransformParameterObject(transformixParameterObject).

ENH: Add SetInitialTransformParameterObject vs Transformix unit test

---

Core/ComponentBaseClasses/elxTransformBase.hxx

When there are two or more "TransformConfigurations", the sequence of transforms is entirely specified by those configurations, and not by transform parameter files. The "InitialTransformParametersFileName" parameter should then be ignored.
Aims to fix a test failure that occurred when running itkElastixRegistrationMethodTest from https://github.com/InsightSoftwareConsortium/ITKElastix/blob/v0.16.0/test/itkElastixRegistrationMethodTest.cxx at the current revision of the elastix main branch.
The bug appears introduced with pull request https://github.com/SuperElastix/elastix/pull/837 commit 1d75664d7d2bcac9ff9c80b11281a9bce6d86212 "ENH: Find previous configuration without interpreting filename as index" (merged on March 17, 2023).

BUG: Ignore "InitialTransformParametersFileName" when configurations > 1

---

Core/Main/GTesting/elxCoreMainGTestUtilities.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx
Core/Main/elxForEachSupportedImageType.h
Core/Main/elxLibUtilities.cxx
Core/Main/elxLibUtilities.h
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.hxx

Both ElastixRegistrationMethod and TransformixFilter now convert their input images to the internal pixel type, specified by elastix/transformix parameters, "FixedInternalImagePixelType" and "MovingInternalImagePixelType" (which are "float" by default).
The conversion is performed internally by `itk::CastImageFilter`. It is only performed when the pixel type of an input image is actually different from the specified internal pixel type.
The converted images are cached in memory, to avoid repeating the very same (potentially expensive) image conversion multiple times.
GoogleTest unit tests are included.
Related to issue #322 "TransformixFilter does not process non-float pixel type images"

ENH: Convert the input images to the user-specified internal pixel type

---

Core/Main/itkTransformixFilter.h
Core/Main/itkTransformixFilter.hxx

The template parameter of `TransformixFilter` is not _just_ the type of the moving image (the input image). Conceptually, it is also the type of the fixed image. Moreover, it is the type of the output image as well.
----
Note that template parameter of `TransformixFilter` was originally named `TInputImage`. It was renamed to "TMovingImage" by commit d5aa28e408fb26fb7a8c4c95c2f6332373b60e2d "ENH: Rename TransformixFilter's template parameter from TInputImage to TMovingImage to clarify mathematical definition and transformation direction", by Kasper (@kaspermarstal), 24 August 2016.

STYLE: Rename TransformixFilter template parameter TMovingImage "TImage"

---

Common/Transforms/itkAdvancedCombinationTransform.hxx

Used modern C++ range-based `for` loops to iterate over the data of `jsh`. Reduced dynamic memory usage by removing `jsh1`.

PERF: Fill `jsh` (JacobianOfSpatialJacobian) in-place and remove `jsh1`

---

Common/Transforms/itkAdvancedCombinationTransform.hxx

Used modern C++ range-based `for` loops to iterate over the matrices of `jsj`, in both `GetJacobianOfSpatialJacobianUseComposition` overloads. Reduced dynamic memory usage by removing `jsj1` in those two cases.
Follow-up to pull request https://github.com/SuperElastix/elastix/pull/890 commit b9ea3a8e65a3e015a5a0f06acfb5bd22fad8dacc
---
This commit appears to make the registration part of [itkElastixRegistrationMethodTest](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/a7150930fb27f0d2c56bbb466db12431eb180850/test/itkElastixRegistrationMethodTest.cxx) ~5% faster, going from ~33 seconds to 32-31 seconds on my PC. Timeouts of itkElastixRegistrationMethodTest at the CI of ITKElastix are a showstopper right now.
Update: I just tested the very same registration with elastix 5.1.0 …

PERF: Fill `jsj` (JacobianOfSpatialJacobian) in-place and remove `jsj1`

---

Common/Transforms/itkAdvancedBSplineDeformableTransformBase.hxx
Common/itkMultiResolutionImageRegistrationMethod2.hxx
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.hxx

Avoided redundant `size()` or `Size()` calls.

STYLE: Add local variables for "number of parameters" to `if` statements

---

Core/Main/elxParameterObject.cxx
Core/Main/elxParameterObject.h

Deprecated the old ReadParameterFile and WriteParameterFile overloads that support multiple files.
Follow-up to:
- pull request https://github.com/SuperElastix/elastix/pull/848 commit 38b615226da9eb1f19b76bfb22a3b80362365540 "Add GetParameterMaps and SetParameterMaps to ParameterObject"
- pull request https://github.com/SuperElastix/elastix/pull/862 commit 0afcc3b242c8377b382381d97cef1bc9e18ec5d8 "Deprecate Get/SetParameterMap in favor of Get/SetParameterMaps"
----
For your information, @kaspermarstal

STYLE: Add ReadParameterFiles and WriteParameterFiles to ParameterObject

---

Common/GTesting/elxConversionGTest.cxx
Common/GTesting/elxTransformIOGTest.cxx
Common/OpenCL/ITKimprovements/itkOpenCLKernel.h
Components/elxGenericPyramidHelper.h
Core/Install/elxConversion.cxx
Core/Install/elxConversion.h
Core/Main/GTesting/elxCoreMainGTestUtilities.h
Testing/itkCompareCompositeTransformsTest.cxx

Following ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3987 commit https://github.com/InsightSoftwareConsortium/ITK/commit/1a914b71bd0e15a4ec687631924c2026b78726fb (merged to the ITK master branch on April 4, 2023).

STYLE: Use C++17 `_v` variable templates from `std` library type traits

---

Core/Main/itkElastixRegistrationMethod.hxx

ElastixRegistrationMethod should not set "NoInitialTransform" as parameter value of `InitialTransformParametersFileName`. The value "NoInitialTransform" might cause confusion, as the registration might still have an initial transform parameter file, specified by `SetInitialTransformParameterFileName`.
----
For the record, ElastixFilter (the predecessor of ElastixRegistrationMethod) started setting the value "NoInitialTransform" in the registration parameter map with pull request #50 commit 6a7f91641081d9b4a1d7f888695347bfdee93575,  "ENH: Explicitly ignore InitialTransformParametersFileName set via parameter maps in ElastixFilter", merged on March 20, 2018:
https://github.com/SuperElastix/elastix/blob/6a7f91641081d9b4a1d7f888695347bfdee93575/Core/Main/elxElastixFilter.hxx#L218-L222
FYI …

BUG: ElastixRegistrationMethod shouldn't put "NoInitialTransform" in map

---

Core/Main/itkElastixRegistrationMethod.hxx

Let ElastixRegistrationMethod write the transform maps from its InitialTransformParameterObject to the output directory.

ENH: ElastixRegistrationMethod writes initial transform parameter files

---

Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Main/itkElastixRegistrationMethod.hxx

Follow-up to pull request https://github.com/SuperElastix/elastix/pull/909 commit 9e64269bb40f9275015d557263acf1f382436087 "ENH: ElastixRegistrationMethod writes initial transform parameter files"
Requested by Marius Staring (@mstaring).
---
Main part of the explanation:
https://github.com/SuperElastix/elastix/blob/b09c835adc321dbe067a679468b734de6c8f68f8/Core/Main/itkElastixRegistrationMethod.hxx#L197-L200

DOC: Explain ElastixRegistrationMethod use "-tp" for initial transforms

---

Components/Transforms/BSplineDeformableTransformWithDiffusion/elxBSplineTransformWithDiffusion.hxx
Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxElastixTemplate.hxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx
Core/Main/itkElastixRegistrationMethod.hxx
Testing/itkTransformixFilterTest.cxx

Follow-up to pull request #903 Remove the letter 's' from "InitialTransformParametersFileName", commit 2170592cbd018cce65698d404cae281f40c28d39

Remove the letter 's' from `ParametersFile`

---

Core/Kernel/elxlog.h

Aims to address a note from GCC 13 saying:
> note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
Reported by Matt McCormick (@thewtex), issue https://github.com/SuperElastix/elastix/issues/916 "GCC 13 cstdint include".
Explicitly specified its `std` namespace, as `<cstdint>` may not add this typedef to the global namespace.

COMP: Add `#include <cstdint>` to elxlog.h, for `std::uint8_t`

---

Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/ComponentBaseClasses/elxTransformBase.h
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxElastixTemplate.hxx

Triggered by questions from Matt McCormick (@thewtex).
The name of the variable "retdc" probably means something like return value of direction cosines estimation.

 Remove `retdc` variable from ElastixTemplate, replace bitwise with logical _and_ (`&&`) on other retdc variables

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Common/ImageSamplers/itkImageToVectorContainerFilter.hxx
Common/Transforms/itkAdvancedImageMomentsCalculator.hxx
Common/itkComputeDisplacementDistribution.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx

To address:
```
In file included from /work/wasi-build/_deps/elx-src/Common/ImageSamplers/itkImageToVectorContainerFilter.h:197:
/work/wasi-build/_deps/elx-src/Common/ImageSamplers/itkImageToVectorContainerFilter.hxx:284:46: error: expected unqualified-id
return itk::ITK_THREAD_RETURN_DEFAULT_VALUE;
```

COMP: ITK_THREAD_RETURN_DEFAULT_VALUE with WASI toolchain

---

Core/Main/itkTransformixFilter.hxx

Slightly simplified the conversion of a ITK transform to an elastix/transformix transform parameter map.

STYLE: TransformixFilter::GenerateData call Conversion::ToVectorOfString

---

Common/Transforms/itkAdvancedCombinationTransform.hxx

Simplified implementation of `AdvancedCombinationTransform::GetNumberOfTransforms()` by moving variable declarations inside the `if` conditions, and by returning directly when the number is estimated.

STYLE: Let CombinationTransform GetNumberOfTransforms() return directly

---

Core/Main/elxParameterObject.cxx

For numeric parameter values, `ParameterObject::WriteParameterFile` did an unnecessary conversion from string to `float` and back, before writing the value to file, which potentially introduced rounding errors, as well as overly verbose string representations of floating point numbers. These are avoided now, by internally using the lossless `Conversion::ParameterMapToString` helper function.
----
The original code printed a whole number with unnecessary trailing decimals, for example:
(NumberOfParameters 2.000000)

ENH: `WriteParameterFile` write floating points without rounding errors

---

Common/Transforms/elxTransformIO.cxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

itk::ObjectFactoryBase::CreateInstance appears to return an object whose reference count is 2, while the object returned by ConvertItkTransformBaseToSingleItkTransform should have reference count 1.
Related to commit https://github.com/InsightSoftwareConsortium/ITK/commit/8e3c544ae5b331577f3b7c923886d1de77d5fd8e "BUG: The ability to override classes with factories was not working", Bill Lorensen, November 8, 2007.
----
@thewtex @tbirdso Do I understand correctly that after a successful `instance = itk::ObjectFactoryBase::CreateInstance(instanceName.c_str())` call, `instance` has a reference count of `2` (as returned by `instance->GetReferenceCount()`), while it should have reference count = `1`?
Do you agree that the following `while` loop is recommended after doing such a …

BUG: Fix reference count in ConvertItkTransformBaseToSingleItkTransform

---

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx

Supporting using an ITK transform object as initial transformation of a registration.
Added itkElastixRegistrationMethod GoogleTest unit tests.
Each of the member functions SetInitialTransform, SetInitialTransformParameterFileName, and SetInitialTransformParameterObject now resets the initial transform.

ENH: Add `ElastixRegistrationMethod::SetInitialTransform`

---

Components/Transforms/WeightedCombinationTransform/elxWeightedCombinationTransform.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Kernel/elxMainBase.cxx

Simplified the code, by skipping the declaration of pointers to components when `GetCreator` has already returned `nullptr`.

STYLE: Skip pointer declarations when `GetCreator` returns null

---

Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx

In general, the use of a smart pointer as return type allows extending the lifetime of the returned object beyond the function call. But as these two `ElastixRegistrationMethod` member functions both just return a pointer to a transform object that is "owned" by the `ElastixRegistrationMethod` object, the caller of `GetNthTransform` or `GetCombinationTransform` does not need to extend the lifetime of the returned transform object. This returned transform object will stay alive while the `ElastixRegistrationMethod` object is there, even when the return type is a raw pointer.
This adjustment was already proposed by Matt McCormick (@thewtex).
----
Aims to (at least partially) supersede the following pull request: 
- #914 
This little pull request is there just to ensure that these changes to …

STYLE: Let GetNthTransform, GetCombinationTransform return a raw pointer

---

Common/GTesting/elxConversionGTest.cxx
Components/Transforms/ExternalTransform/CMakeLists.txt
Components/Transforms/ExternalTransform/elxAdvancedTransformAdapter.h
Components/Transforms/ExternalTransform/elxExternalTransform.cxx
Components/Transforms/ExternalTransform/elxExternalTransform.h
Components/Transforms/ExternalTransform/elxExternalTransform.hxx
Core/Install/elxConversion.cxx
Core/Install/elxConversion.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx

Adds a component that allows specifying an ITK transform by its address in memory. The transform is then _not_ converted to the corresponding elastix AdvancedTransform. Instead, it is only "adapted", meaning that its `TransformPoint` is still called directly, when using the transform. This component is only meant to be used with the elastix/transformix library, not with the elastix/transformix executable. It only serves as input transform, so it is meant not to be adjusted during registration.
Adds a `SetExternalInitialTransform` member function to `ElastixRegistrationMethod`, allowing to specify any ITK transform (for example an `itk::DisplacementFieldTransform`) as initial transform. Aims to address the following issue:
- #874

Add "ExternalTransform" component and `ElastixRegistrationMethod::SetExternalInitialTransform`

---

Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkTransformixFilter.h

Avoided use of dependent types (having to use `typename`). Also consistently did initialization by `{}`.
----
Note that some old GCC compilers (before GCC 9.2) produced "error: invalid use of incomplete type" when using `{}` initialization for a SmartPointer to an incomplete type. But nowadays it should be just fine to initialize any SmartPointer by `{}`. Related to an ITK pull request:
- https://github.com/InsightSoftwareConsortium/ITK/pull/3927

STYLE: Explicitly use SmartPointer for data members in ITK interface

---

Common/GTesting/elxConversionGTest.cxx
Common/Transforms/elxTransformIO.h
Components/Transforms/ExternalTransform/elxAdvancedTransformAdapter.h
Components/Transforms/ExternalTransform/elxExternalTransform.h
Components/Transforms/ExternalTransform/elxExternalTransform.hxx
Core/Install/elxConversion.cxx
Core/Install/elxConversion.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx

When `ConvertToItkTransform` has converted the CombinationTransform produced by a registration that used an external initial transform, the result should be an `itk::CompositeTransform` that has a pointer to the initial transform as its "back transform".
Follow-up on a comment by Dženan Zukić (@dzenanz) at https://github.com/InsightSoftwareConsortium/ITKElastix/pull/241#issuecomment-1682550470

`ElastixRegistrationMethod.ConvertToItkTransform` support external initial transforms 

---

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/itkElastixRegistrationMethod.h

Added GetInitialTransform() and GetExternalInitialTransform() to ElastixRegistrationMethod, and tested that these two properties are mutually exclusive.

ENH: Add GetInitialTransform() and GetExternalInitialTransform()

---

Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx

Following C++ Core Guidelines, April 13, 2023, "Prefer scoped objects, don’t heap-allocate unnecessarily", https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r5-prefer-scoped-objects-dont-heap-allocate-unnecessarily

STYLE: Place Threader::SetSingleMethod argument `temp` on the stack

---

Common/ImageSamplers/itkImageRandomCoordinateSampler.hxx
Common/ImageSamplers/itkImageRandomSamplerBase.hxx
Common/ImageSamplers/itkImageRandomSamplerSparseMask.hxx
Common/Transforms/itkGridScheduleComputer.hxx
Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.hxx

`clear()` appears slightly clearer.

Replace `resize(0)` with `clear()`, do not `clear()` data members in default-constructors

---

Common/ImageSamplers/itkImageFullSampler.hxx
Common/ImageSamplers/itkImageGridSampler.hxx
Common/ImageSamplers/itkImageRandomCoordinateSampler.hxx
Common/ImageSamplers/itkImageRandomSamplerSparseMask.hxx
Common/ImageSamplers/itkImageSample.h

Did speed up `ImageFullSampler`, `ImageGridSampler`, and `ImageRandomSamplerSparseMask` by doing the `push_back`'s of samples to a local `std::vector` of samples (instead of directly to the sample container), and then eventually swapping the vector "into" the sample container.
When using `ImageFullSampler` on a 4096 x 4096 input image, a `sampler.Update()` call originally took more than 0.38 seconds, but it went down to almost 0.20 seconds with this commit, as observed using Visual C++ 2019 (Release configuration).
This pull request also includes various coding style improvements of the implementation of the samplers.

Speed up `ImageFullSampler`, `ImageGridSampler`, and `ImageRandomSamplerSparseMask`, using a local `sampleVector` variable

---

Common/Transforms/elxTransformIO.cxx
Common/Transforms/elxTransformIO.h
Core/Main/itkElastixRegistrationMethod.hxx

Aims to avoid an ITKElastix compile error reported by Dženan Zukić (@dzenanz), saying:
> _deps/elx-src/Core/Main/itkElastixRegistrationMethod.hxx:43:10: fatal error: 'itkTransformFileWriter.h' file not found

COMP: Replace include <itkTransformFileWriter.h> with "elxTransformIO.h"

---

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx

ElastixRegistrationMethod member functions `GetNumberOfTransforms`, `GetNthTransform`, and `GetCombinationTransform` did always just return zero or null, erroneously, when the pixel type of the input images (specified by `TFixedImage` and `TMovingImage`) would be different from the internal pixel type (specified by "FixedInternalImagePixelType" and "MovingInternalImagePixelType", `float` by default). The code incorrectly assumed that the objects stored in the ElastixBase `TransformContainer` are always of type `elx::TransformBase<ElastixTemplate<TFixedImage, TMovingImage>>`.
This commit just assumes that the objects stored in `TransformContainer` are of type `AdvancedCombinationTransform<double, FixedImageDimension>`.
The commit aims to fix issue …

BUG: Fix ElastixRegistrationMethod GetNumberOfTransforms GetNthTransform

---

Common/GTesting/elxGTestUtilities.h
Core/Main/GTesting/CMakeLists.txt
Core/Main/GTesting/ParameterObjectGTest.cxx
Core/Main/elxParameterObject.cxx

With this commit `ParameterObject::WriteParameterFiles` writes _each_ maps to a file, including the first one. Aims to address issue https://github.com/SuperElastix/elastix/issues/904 "ParameterObject::WriteParameterFiles does not write the first map!"
A GoogleTest unit test is added, testing that each of the files specified by the `parameterFileNameVector` parameter is indeed written to disk.

BUG: `ParameterObject::WriteParameterFiles` should write all maps

---

Common/GTesting/itkImageRandomSamplerGTest.cxx
Common/ImageSamplers/itkImageRandomSampler.h
Common/ImageSamplers/itkImageRandomSampler.hxx
Common/ImageSamplers/itkImageRandomSamplerBase.h
Common/ImageSamplers/itkImageRandomSamplerBase.hxx

Internally calling `multiThreader->SingleMethodExecute()`, instead of overriding `ThreadedGenerateData`.
When 10'000 random samples are retrieved, a significant performance improvement is observed by enabling `UseMultiThread`: from ~1.2 millisecond (single-threaded) to ~0.9 millisecond (multi-threaded). When 100'000 random samples are retrieved, even from ~7 to ~3 millisecond: Tested on a Windows 10 PC (6 cores, 12 logical processors), VS2019 Release build.

ENH: ImageRandomSampler `UseMultiThread` now using ITK's ThreadPool

---

Components/ImageSamplers/Grid/elxGridSampler.hxx
Components/ImageSamplers/MultInputRandomCoordinate/elxMultiInputRandomCoordinateSampler.hxx
Components/ImageSamplers/Random/elxRandomSampler.hxx
Components/ImageSamplers/RandomCoordinate/elxRandomCoordinateSampler.hxx
Components/ImageSamplers/RandomSparseMask/elxRandomSamplerSparseMask.hxx

Follow-up to pull request https://github.com/SuperElastix/elastix/pull/830 commit bfc2ee8498d558b982f008e847dd36220bef0b68 "ENH: Add local `const Configuration &` variables to Optimizers"

ENH: Add local `const Configuration &` variables to ImageSamplers

---

Common/GTesting/itkImageRandomCoordinateSamplerGTest.cxx
Common/GTesting/itkImageRandomSamplerGTest.cxx
Common/GTesting/itkImageRandomSamplerSparseMaskGTest.cxx
Common/ImageSamplers/itkImageRandomSamplerSparseMask.h
Common/ImageSamplers/itkImageRandomSamplerSparseMask.hxx

ImageRandomSamplerSparseMask now forwards `UseMultiThread` to its internal FullSampler, _and_ uses its own ThreaderCallback, instead of the old `ThreadedGenerateData` mechanism.
Follow-up to:
- pull request #973
- pull request #978
Also added GoogleTest unit tests.

Improve ImageRandomSamplerSparseMask `UseMultiThread` support, add GTest unit tests

---

Testing/CI/Azure/ci.yml

Looking at https://github.com/actions/runner-images/tree/562b6b9e90dfd8d81b8b174a0f095be92f18f09c/images/windows it appears that windows-2019 still has Python 3.7.9, which is no longer supported by SimpleITK, while windows-2022 has Python 3.9.13 "out of the box".
Follow-up to:
- pull request https://github.com/SuperElastix/elastix/pull/985 commit 2c44c331f168a5a11f3c4d4335ee867a261e1064 "COMP: Upgrade GitHub Actions CI to ubuntu-22.04, windows-2022, macos-12"
- pull request https://github.com/SuperElastix/elastix/pull/985 commit dd65ed43a16067eaa67073baf8f4d3dbd1f642ca "COMP: Upgrade GitHub Actions to Python 3.8"

COMP: Upgrade Azure Pipelines CI from windows-2019 to windows-2022

---

Common/ImageSamplers/itkImageRandomSampler.hxx

ImageRandomSampler::GenerateData() accidentally did set the seed of the global MersenneTwisterRandomVariateGenerator, while there was no reason to. Doing so causes differences between multi-threaded and single-threaded sampling output.
----
- The bug appears to be introduced by myself, with pull request #973 commit ca9e9ecdf5a1bf7fca2df887feaf5c87365c5b81
https://github.com/SuperElastix/elastix/blob/ca9e9ecdf5a1bf7fca2df887feaf5c87365c5b81/Common/ImageSamplers/itkImageRandomSampler.hxx#L62-L63

BUG: ImageRandomSampler (UseMultiThread) should not GetNextSeed()

---

Common/ImageSamplers/itkImageSamplerBase.h
Core/ComponentBaseClasses/elxImageSamplerBase.h
Core/ComponentBaseClasses/elxImageSamplerBase.hxx

Replaced the "-mts" command-line option with a new elastix parameter, `UseMultiThreadingForSamplers` ("true" by default).

Replace "-mts" command-line option with `UseMultiThreadingForSamplers` parameter (default "true")

---

Common/ImageSamplers/itkImageRandomSamplerBase.hxx

This "dummy jump" on a local `MersenneTwisterRandomVariateGenerator` variable appears unnecessary, even though it has been there already from the initial version of ImageRandomSamplerBase, November 14, 2013:
https://github.com/SuperElastix/elastix/blob/2fc2c495837f64416263fa7c5d1e2bc4e3e061fa/src/Common/ImageSamplers/itkImageRandomSamplerBase.txx#L66

STYLE: Remove dummy jump ImageRandomSamplerBase GenerateRandomNumberList

---

Common/ImageSamplers/itkImageGridSampler.hxx

Reserving the right number of samples beforehand appears to possibly make ImageGridSampler twice as fast. When having a 4096x4096 grid (no mask), it was observed that the duration of an ImageGridSampler::Update() went from 0.45 second (before this commit) to almost 0.20 second  (after this commit), using Visual C++ 2019, Release configuration.
This pull request also proposes to use std::accumulate to calculate `numberOfSamplesOnGrid`.
----
Note that originally `numberOfSamplesOnGrid` was just calculated without being used. From here, commit 6e0e6f88163dfce901d72bbcb57fb1a388186ac3, July 17, 2006, "implemented grid and full sampler":
https://github.com/SuperElastix/elastix/blob/6e0e6f88163dfce901d72bbcb57fb1a388186ac3/src/Common/ImageSamplers/itkImageGridSampler.txx#L37

PERF: `ImageGridSampler` twice as fast, doing `sampleVector.reserve(numberOfSamplesOnGrid)`

---

Common/ImageSamplers/itkImageGridSampler.h
Common/ImageSamplers/itkImageGridSampler.hxx

Made the "ugly" loops over the grid within `ImageGridSampler::GenerateData()` slightly more beautiful, by adding two private helper functions:
ImageGridSampler::GetGridSizeValue
ImageGridSampler::JumpToNextGridPosition

STYLE: Add helper functions to ImageGridSampler to loop over the grid

---

Common/ImageSamplers/itkImageFullSampler.hxx
Common/ImageSamplers/itkImageGridSampler.hxx
Common/ImageSamplers/itkImageSamplerBase.hxx
Common/ImageSamplers/itkImageToVectorContainerFilter.hxx
Common/ImageSamplers/itkMultiInputImageRandomCoordinateSampler.hxx

Follow-up to commit 0ef6d0dd6346f80961754fdab2162a9d0021b38d "STYLE: `Deref` sampler input and output at the start of GenerateData()"

STYLE: `Deref` input and output pointer everywhere in "ImageSamplers"

---

Common/ImageSamplers/itkImageSamplerBase.h
Common/ImageSamplers/itkImageSamplerBase.hxx

Bug introduced with pull request #1006 commit 81e5fe8d8ae1784179c720662584a6a33997dd70 "STYLE: Rename `SplitRequestedRegion` to "SplitRegion", make it `static`", merged 9 December 2023 (my fault).
Fortunately the bug seems to rarely cause any problem, as it occurs only when the input region has less than 2 pixels.

BUG: Make sure `splitRegion = inputRegion` if SplitRegion cannot split, and some ImageSamplerBase style fixes 

---

Common/GTesting/itkImageGridSamplerGTest.cxx
Common/ImageSamplers/itkImageGridSampler.h
Common/ImageSamplers/itkImageGridSampler.hxx

Initial benchmark (4096x4096 image, 2x2 grid spacing, no mask) suggests a performance improvement by a factor of ~2 (VS2019 Release build, 6 cores, 12 logical processors, 48 work units).
Benchmark code:
```cpp
using PixelType = int;
enum
{
// Or in 3D:
//    ImageSizeValue = 200,
//    Dimension = 3U
ImageSizeValue = 4096U,
Dimension = 2U
};
using ImageType = itk::Image<PixelType, Dimension>;
using SamplerType = itk::ImageGridSampler<ImageType>;
constexpr auto imageSize = ImageType::SizeType::Filled(ImageSizeValue);
const auto     image = CreateImage<PixelType>(imageSize);
const auto generateSamples = [image](const bool useMultiThread) {
elx::DefaultConstruct<SamplerType> sampler{};
sampler.SetUseMultiThread(useMultiThread);
sampler.SetSampleGridSpacing(itk::MakeFilled<SamplerType::SampleG …
```

PERF: Make ImageGridSampler multi-threaded

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/ImageSamplers/itkImageGridSampler.hxx
Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/elxCorrespondingPointsEuclideanDistanceMetric.hxx
Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.hxx
Core/ComponentBaseClasses/elxOptimizerBase.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/elxProgressCommand.cxx

According to https://github.com/InsightSoftwareConsortium/ITK/blob/66ab5b14c476d057ed46a4daba05b710681160e6/Modules/Core/Common/include/itkMath.h#L127 the `TReturn` template argument of `Math::Round` must be an integer type.
Anticipating the following ITK pull request:
- https://github.com/InsightSoftwareConsortium/ITK/pull/4409

Adjust or replace `itk::Math::Round<TReturn>` calls, whenever `TReturn` is a floating point type

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/CostFunctions/itkSingleValuedPointSetToPointSetMetric.h
Common/ImageSamplers/itkImageGridSampler.h
Common/ImageSamplers/itkImageGridSampler.hxx
Common/ImageSamplers/itkImageSamplerBase.h
Common/Transforms/itkAdvancedImageMomentsCalculator.h
Common/itkComputeDisplacementDistribution.h
Common/itkComputeImageExtremaFilter.h
Common/itkComputeImageExtremaFilter.hxx
Common/itkComputeJacobianTerms.h
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.h
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/GradientDifference/itkGradientDifferenceImageToImageMetric2.hxx
Components/Metrics/NormalizedGradientCorrelation/itkNormalizedGradientCorrelationImageToImageMetric.hxx
Components/Metrics/PatternIntensity/itkPatternIntensityImageToImageMetric.hxx
Components/Transforms/AdvancedAffineTransform/itkCenteredTransformInitializer2.h

Made `GenerateData()` around 2x as fast, when having a mask.

PERF: ImageGridSampler replace IsInsideInWorldSpace calls

---

Common/GTesting/itkComputeImageExtremaFilterGTest.cxx
Common/elxImageDomain.h
Common/itkComputeImageExtremaFilter.hxx

Fixes issue https://github.com/SuperElastix/elastix/issues/1023 "ComputeImageExtremaFilter SameGeometry should include Index, Spacing, and Direction"
Tested that changes of Spacing or Direction of the mask may indeed affect the results of ComputeImageExtremaFilter.

BUG: ComputeImageExtremaFilter SameGeometry include Spacing, Direction

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/itkComputeImageExtremaFilter.h
Common/itkComputeImageExtremaFilter.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx

Three style improvements related to ComputeFixedImageExtrema.
@mstaring @stefanklein Note that ComputeFixedImageExtrema did not use its `m_ImageRegion` property internally, even though both AdvancedImageToImageMetric and AdvancedMeanSquaresImageToImageMetric did call `computeFixedImageExtrema->SetImageRegion`. This pull request proposes to just remove this property.
Also addressed the following issue:
- #1025

Remove m_ImageRegion and SameGeometry() from ComputeFixedImageExtrema

---

Common/ImageSamplers/itkImageFullSampler.hxx

It is inefficient to do the same `mask->UpdateSource()` call in multiple threads. Moreover, doing so might lead to race conditions.
----
For the record, this bug appears introduced with commit 2fc2c495837f64416263fa7c5d1e2bc4e3e061fa "ENH: HUGE merge of the performance branch", November 14, 2013:
https://github.com/SuperElastix/elastix/blob/2fc2c495837f64416263fa7c5d1e2bc4e3e061fa/src/Common/ImageSamplers/itkImageFullSampler.txx#L197-L200

BUG: ImageFullSampler do `mask->UpdateSource()` single-threaded

---

Common/ImageSamplers/itkImageFullSampler.hxx

Note that `catch (...)` is unnecessary in these cases, because `std::vector::reserve` may only throw an exception that is derived from `std::exception`.

STYLE: Simplify try-catch on std::vector::reserve in ImageFullSampler

---

Common/ImageSamplers/itkImageFullSampler.hxx
Common/ImageSamplers/itkImageRandomCoordinateSampler.hxx
Common/ImageSamplers/itkImageRandomSampler.hxx
Common/ImageSamplers/itkImageRandomSamplerSparseMask.hxx
Common/ImageSamplers/itkMultiInputImageRandomCoordinateSampler.hxx

Consistently used a raw pointer to the mask of its superclass (base class), in all samplers.
In these cases a smart pointer (`MaskType::ConstPointer`) is not necessary, as there is no risk for the mask to be deleted while it is being used by the sampler.

STYLE: Do `const MaskType * const mask = this->Superclass::GetMask()`

---

Common/ImageSamplers/itkImageFullSampler.h
Common/ImageSamplers/itkImageFullSampler.hxx
Common/Transforms/itkAdvancedRigid3DTransform.h
Common/Transforms/itkAdvancedRigid3DTransform.hxx
Common/Transforms/itkAdvancedVersorRigid3DTransform.h
Common/Transforms/itkAdvancedVersorRigid3DTransform.hxx
Common/itkMultiResolutionGaussianSmoothingPyramidImageFilter.h
Common/itkMultiResolutionGaussianSmoothingPyramidImageFilter.hxx
Testing/itkTestOutputWindow.cxx
Testing/itkTestOutputWindow.h

These overrides were empty anyway! Found by Notepad++ `{\r\n  Superclass::PrintSelf(os, indent);\r\n}`.
Replaced the declarations of those overrides by `using Superclass::PrintSelf`.

STYLE: Remove `PrintSelf` overrides from classes without data members

---

Common/ImageSamplers/itkImageGridSampler.h
Common/ImageSamplers/itkImageGridSampler.hxx

Shared more code between multi-threaded and single-threaded implementations of ImageGridSampler.

Add private static `ImageGridSampler::GenerateDataForWorkUnit` member function, reducing duplicate code

---

Common/ImageSamplers/itkImageGridSampler.hxx

Small code cleanup of itkImageGridSampler.hxx. The clear() calls in SingleThreadedGenerateData and MultiThreadedGenerateData were redundant, as GenerateData() does so.

STYLE: Remove samples.clear() and return ITK_THREAD_RETURN_DEFAULT_VALUE

---

Common/ImageSamplers/itkImageRandomSamplerSparseMask.hxx

Addressed the following issue:
- #1035 
Fixes #1035

Remove unreachable error from `ImageRandomSamplerSparseMask`, extend error message on missing mask 

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkMultiInputImageToImageMetricBase.h
Common/CostFunctions/itkMultiInputImageToImageMetricBase.hxx
Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.h
Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.hxx
Components/Transforms/AdvancedAffineTransform/itkCenteredTransformInitializer2.h

Increases const-correctness. Ensures that the right overload is called, when AdvancedImageToImageMetric calls `Superclass::SetFixedImageMask(arg)` or `Superclass::SetMovingImageMask(arg)`.
Related to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4414 commit https://github.com/InsightSoftwareConsortium/ITK/commit/813ddb3d52955d0e0017ea9690e0afab45047c81 "STYLE: Remove itkSetObjectMacro if itkSetConstObjectMacro is also there" (merged to ITK's master branch on January 22, 2024)

STYLE: Add const to masks Get/SetFixedImageMask, Get/SetMovingImageMask

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/GTesting/itkComputeImageExtremaFilterGTest.cxx
Common/itkComputeImageExtremaFilter.h
Common/itkComputeImageExtremaFilter.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx

No longer computed the mean, sigma, variance, sum, or sum of squares. Removed m_ThreadSum, m_SumOfSquares, and m_Count. Removed inheritance from StatisticsImageFilter (which computed the mean, sigma, variance, sum, and sum of squares for images without a mask).
ComputeImageExtremaFilter is only being used in elastix by AdvancedImageToImageMetric and AdvancedMeanSquaresImageToImageMetric, and both of them only need to have the minimum and the maximum from ComputeImageExtremaFilter.
A performance improvement of ~8 percent was observed on a 8192x8192 image with mask. Without a mask, the computation appears even more than six times as fast as before.

ComputeImageExtremaFilter: Remove `UseMask` property and let it only compute min and max 

---

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.h
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.h
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.h
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.h
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx

Values of built-in types are usually preferably passed "by value".

STYLE: Do not use const-references for "real" values

---

Common/itkComputeDisplacementDistribution.hxx
Common/itkComputeJacobianTerms.hxx
Common/itkComputePreconditionerUsingDisplacementDistribution.hxx

Reduced the amount of boilerplate code, and possibly gained some performance improvement, in ComputeJacobianTerms, ComputeDisplacementDistribution, ComputePreconditionerUsingDisplacementDistribution.

STYLE: Use range-based `for` to iterate over samples "Common/itkCompute"

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/itkGenericMultiResolutionPyramidImageFilter.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx

Now using `0`, `0.0`, or `{}` initializers instead, whatever is appropriate.

Remove local "zero" variables

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.h
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.h
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.h
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.h
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.h
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx

Also added `const` to local `metric` variable in `AdvancedImageToImageMetric::GetValueAndDerivativeThreaderCallback(void *)`.
Eases preserving thread-safety.

STYLE: Add const to `ThreadedGetValueAndDerivative(ThreadIdType)`

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h

May improve the run-time performance.
Following C++ Core Guidelines, February 15, 2024, "Don’t make a function `virtual` without reason", https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-virtual

STYLE: Declare 8 AdvancedImageToImageMetric member functions non-virtual

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.h
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.h
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx

Also added `const` to local `metric` variable in `AdvancedImageToImageMetric::GetValueThreaderCallback(void *)`.
- Follow-up to pull request https://github.com/SuperElastix/elastix/pull/1059 commit d44f13e69cc3fef678df740835a5f762cd66f422
----
@mstaring @stefanklein I noticed that there are only two `ThreadedGetValue` overrides: only from the AdvancedMeanSquares and SumSquaredTissueVolumeDifference metrics. (`ThreadedGetValueAndDerivative` has three more overrides, from AdvancedKappaStatistic and AdvancedNormalizedCorrelation metrics, as well as by TransformBendingEnergyPenaltyTerm). Should the other metric classes also get a `ThreadedGetValue` override? Or is `ThreadedGetValue` no longer necessary?
Update: it looks like `ThreadedGetValue` is never actually called in any of the tests. So …

STYLE: Add const to `ThreadedGetValue(ThreadIdType)`

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx
Common/Transforms/itkAdvancedTransform.h
Common/Transforms/itkAdvancedTransform.hxx
Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx
Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx

Various EvaluateTransformJacobianInnerProduct member functions appear very similar. This refactoring aims to help analyzing and understandingthe metrics. 
There are 17 metrics derived from AdvancedImageToImageMetric:
- CostFunctions/ImageToImageMetricWithFeatures
- CostFunctions/MultiInputImageToImageMetricBase
- CostFunctions/ParzenWindowHistogramImageToImageMetric
- CostFunctions/TransformPenaltyTerm
- AdvancedKappaStatisticImageToImageMetric
- AdvancedMeanSquaresImageToImageMetric
- AdvancedNormalizedCorrelationImageToImageMetric
- GradientDifferenceImageToImageMetric2/GradientDifferenceImageToImageMetric
- NormalizedGradientCorrelationImageToImageMetric
- PatternIntensityImageToImageMetric
- PCAMetric2
- PCAMetric
- PCAMetric_F_multithreaded/PCAMetric
- …

Refactor EvaluateJacobianWithImageGradientProduct and EvaluateTransformJacobianInnerProduct

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/GTesting/elxConversionGTest.cxx
Common/GTesting/elxTransformIOGTest.cxx
Common/GTesting/itkAdvancedImageToImageMetricGTest.cxx
Common/GTesting/itkAdvancedMeanSquaresImageToImageMetricGTest.cxx
Common/GTesting/itkComputeImageExtremaFilterGTest.cxx
Common/GTesting/itkImageFullSamplerGTest.cxx
Common/GTesting/itkImageGridSamplerGTest.cxx
Common/GTesting/itkImageRandomSamplerSparseMaskGTest.cxx
Common/Transforms/itkAdvancedCombinationTransform.h
Common/elxSupportedImageDimensions.h
Core/Install/elxPrepareImageTypeSupport.h
Core/Main/GTesting/ElastixLibGTest.cxx
Core/Main/GTesting/elxCoreMainGTestUtilities.cxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx

- Replaced `constexpr static` with `static constexpr`, following ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3144 by Lee Newberg (@leengit). In accordance with blog entry [`static constexpr unsigned long` is C++’s “lovely little old French whittling knife”](https://quuxplusone.github.io/blog/2021/04/03/static-constexpr-whittling-knife/), Arthur O’Dwyer, 2021-04-03.
- Replaced local `enum` constants with `static constexpr`
- Added `static` to `constexpr ` local variables in GTest source files, following a suggestion by ["C++ Weekly With Jason Turner"](https://www.youtube.com/@cppweekly) episode 312 - [Stop Using `constexpr` (And Use This Instead!)](https://www.youtube.com/watch?v=4pKtPWcl1Go). Excluded the local variable `pixelTypeNames` from …

Use `static constexpr` for local constants

---

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx

st_NumberOfPixelsCounted is properly reset by the InitializeThreadingParameters() member functions of AdvancedImageToImageMetric, AdvancedKappaStatisticImageToImageMetric, and AdvancedNormalizedCorrelationImageToImageMetric. So it isn't necessary to _also_ reset this "thread variable" in the "AfterThreaded" member functions of the metrics.

STYLE: Don't reset st_NumberOfPixelsCounted in Metric "AfterThreaded"

---

Common/Transforms/itkBSplineInterpolationWeightFunction2.h
Common/Transforms/itkBSplineInterpolationWeightFunction2.hxx
Common/Transforms/itkCyclicGridScheduleComputer.h
Common/Transforms/itkCyclicGridScheduleComputer.hxx
Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/itkCorrespondingPointsEuclideanDistancePointMetric.h
Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/itkCorrespondingPointsEuclideanDistancePointMetric.hxx

When a constructor is defaulted within a hxx file, it might as well be defaulted directly with its first declaration, in the corresponding h file.

STYLE: Move definitions of defaulted constructors into class definitions

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/GTesting/itkAdvancedImageToImageMetricGTest.cxx

Following C++ Core Guidelines, February 15, 2024: "Avoid `protected` data", https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-protected

STYLE: Declare InterpolatorPointer member variables of metric `private`

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx

- Replaced `this->m_...`  with `Superclass::m_...` whenever it accesses a data member of its base class
- Simply removed `this->`  whenever it accesses one of its own data members
Aims to improve code readability.

Remove `this->m_...`  from `AdvancedImageToImageMetric`

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx

The metrics (currently) only use ITK's `GradientImageFilter` when the interpolator is a NearestNeighbor interpolator.

STYLE: Adjust `if` condition on when to use ITK's GradientImageFilter

---

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Common/ImageSamplers/itkImageRandomCoordinateSampler.hxx
Common/ImageSamplers/itkImageRandomSamplerSparseMask.hxx
Common/Transforms/elxTransformIO.cxx
Common/Transforms/itkAdvancedImageMomentsCalculator.hxx
Common/Transforms/itkStackTransform.h
Common/itkComputeDisplacementDistribution.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/MissingStructurePenalty/vnl_adjugate_fixed.h
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.hxx
Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.hxx
Core/ComponentBaseClasses/elxResampleInterpolatorBase.hxx
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/Main/itkElastixRegistrationMethod.hxx
Core/Main/itkTransformixFilter.hxx
Core/Main/transformix.cxx
Testing/itkAccumulateDerivativesParallellizationTest.cxx
Testing/itkAdvanceOneStepParallellizationTest.cxx

Aims to prevent errors like:
> Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx:309:3: error: 'assert' was not declared in this scope
At https://my.cdash.org/viewBuildError.php?buildid=2537950 (Build Name: SuperElastix/elastix-ubuntu-22.04-WIP-back-to-ITK-v530-9a39f9931e9207e164c410a92c71e09f76002ee4)

COMP: Add missing `#include <cassert>` directives

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkMultiInputImageToImageMetricBase.hxx
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Common/CostFunctions/itkTransformPenaltyTerm.hxx
Common/GTesting/itkAdvancedImageToImageMetricGTest.cxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/DisplacementMagnitudePenalty/itkDisplacementMagnitudePenaltyTerm.hxx
Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/PatternIntensity/itkPatternIntensityImageToImageMetric.hxx
Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx

Made it clearer when AdvancedImageToImageMetric accesses its own data members, and when those data members are accessed by a derived metric class.

Remove `this->` from data access AdvancedImageToImageMetric, replace `this->` with `Superclass::` on data access by derived classes

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/GTesting/itkAdvancedImageToImageMetricGTest.cxx

The protected AdvancedImageToImageMetric data members m_GetValuePerThreadVariables and m_GetValuePerThreadVariablesSize appear unused.

STYLE: Remove `AdvancedImageToImageMetric::m_GetValuePerThreadVariables`

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/Transforms/itkAdvancedImageMomentsCalculator.hxx
Common/itkComputeDisplacementDistribution.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx
Testing/itkAccumulateDerivativesParallellizationTest.cxx

These member variables were already declared `mutable`, so there appears no need at all for those `const_cast<void *>(static_cast<const void *>())` casts.
Following C++ Core Guidelines, [Avoid casts](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-casts)

Remove const_cast and static_cast from m_ThreaderMetricParameters and m_ThreaderParameters 

---

Common/itkRecursiveBSplineInterpolationWeightFunction.h

`RecursiveBSplineInterpolationWeightFunction::NumberOfWeights` was never used. Its value `(SplineOrder + 1) * SpaceDimension` was different from both `BSplineInterpolationWeightFunctionBase::NumberOfWeights` _and_ `RecursiveBSplineInterpolationWeightFunction::m_NumberOfWeights` (both equivalent to `pow(SplineOrder + 1, SpaceDimension)`), which appeared somewhat confusing.

STYLE: Remove `NumberOfWeights` from RecursiveBSpline WeightFunction

---

Common/Transforms/itkBSplineSecondOrderDerivativeKernelFunction2.h

Removed the name of the unused second parameter of `BSplineSecondOrderDerivativeKernelFunction2::Evaluate(const Dispatch<2> &, const double u, double * weights)`
Found by warnings from Clang and GCC, "unused parameter [-Wunused-parameter]".

COMP: Unused parameter `u` BSplineSecondOrderDerivativeKernelFunction2

---

Testing/Dashboard/elxCommonCDash.cmake

Both maximum numbers appear to be `50` by default, causing messages at https://my.cdash.org/index.php?project=elastix saying:
> The maximum number of reported warnings or errors has been reached!!!

COMP: Increase maximum number of reported warnings and errors on CDash

---

Common/Transforms/itkAdvancedBSplineDeformableTransform.h
Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Common/Transforms/itkBSplineInterpolationDerivativeWeightFunction.hxx
Common/Transforms/itkBSplineInterpolationSecondOrderDerivativeWeightFunction.hxx
Common/Transforms/itkBSplineInterpolationWeightFunction2.hxx
Common/Transforms/itkBSplineInterpolationWeightFunctionBase.h
Common/Transforms/itkBSplineInterpolationWeightFunctionBase.hxx
Common/Transforms/itkCyclicBSplineDeformableTransform.hxx
Common/Transforms/itkRecursiveBSplineTransform.hxx
Common/itkRecursiveBSplineInterpolationWeightFunction.h
Common/itkRecursiveBSplineInterpolationWeightFunction.hxx
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.h
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.hxx
Testing/itkBSplineInterpolationDerivativeWeightFunctionTest.cxx
Testing/itkBSplineInterpolationSODerivativeWeightFunctionTest.cxx
Testing/itkBSplineInterpolationWeightFunctionTest.cxx
Testing/itkBSplineTransformPointPerformanceTest.cxx

Replaced run-time evaluation of number of weights and support size with compile-time evaluation of those values. Might improve the run-time performance of bspline transformations and interpolations. Just marked as style improvement, because the changes are not benchmarked (yet).

Replace `GetNumberOfWeights()`, `GetSupportSize()`, and `m_SupportSize` with compile-time equivalents (STYLE/PERF)

---

Components/Metrics/AdvancedNormalizedCorrelation/elxAdvancedNormalizedCorrelationMetric.h
Components/Metrics/AdvancedNormalizedCorrelation/elxAdvancedNormalizedCorrelationMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.h
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx

Let the AdvancedNormalizedCorrelation metric always just act as if the SubtractMean parameter has value "true".
Discussed with Marius Staring (@mstaring  and Stefan Klein (@stefanklein).

STYLE: AdvancedNormalizedCorrelation drop support for SubtractMean=false

---

Components/Registrations/MultiResolutionRegistrationWithFeatures/elxMultiResolutionRegistrationWithFeatures.hxx

It appears unnecessary to place the interpolators created by GetAndSetFixedImageInterpolators() in a local `std::vector`, before passing each of them to SetFixedImageInterpolator.
This commit also prevents a warning, saying:
> warning: declaration of 'using FixedImageInterpolatorType = ...' shadows a member of 'elastix::MultiResolutionRegistrationWithFeatures' [-Wshadow]

STYLE: Simplify GetAndSetFixedImageInterpolators(), avoiding `-Wshadow`

---

Common/ImageSamplers/itkImageSamplerBase.h
Common/ImageSamplers/itkImageSamplerBase.hxx
Common/ImageSamplers/itkVectorContainerSource.h
Common/ImageSamplers/itkVectorContainerSource.hxx
Common/itkMultiResolutionImageRegistrationMethod2.h
Common/itkMultiResolutionImageRegistrationMethod2.hxx

Fixed the parameter type of the `MakeOutput` member functions of ImageSamplerBase, VectorContainerSource, and MultiResolutionImageRegistrationMethod2, to ensure that they properly override ITK's `ProcessObject::MakeOutput(DataObjectPointerArraySizeType)`. Following ITK commit https://github.com/InsightSoftwareConsortium/ITK/commit/b066b3663548acbc200b6781a5f4a56a5737add0 "COMP: Fix VisualStudio warning int possible loss of data.",  Matt McCormick, 2011-11-17, by using `DataObjectPointerArraySizeType`.

STYLE: Let signature of `MakeOutput` member functions match with ITK

---

Common/ImageSamplers/itkImageSamplerBase.hxx
Common/ImageSamplers/itkVectorContainerSource.hxx
Common/itkMultiResolutionImageRegistrationMethod2.hxx

Analogue to ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4654
Following C++ Core Guidelines, February 15, 2024, "Don’t call virtual functions in constructors and destructors", https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-ctor-virtual

STYLE: Remove `this->MakeOutput(0)` calls from constructors

---

Components/Optimizers/ConjugateGradientFRPR/elxConjugateGradientFRPR.h
Components/Optimizers/ConjugateGradientFRPR/elxConjugateGradientFRPR.hxx

`elx::ConjugateGradientFRPR` member functions GetValueAndDerivative and LineOptimize did originally override the corresponding virtual member functions of ITK's FRPROptimizer. This property was broken by a change in the signature of those ITK member functions: ITK commit https://github.com/InsightSoftwareConsortium/ITK/commit/a088a95fca4e0f94ef661cdc43a6bec26ad687a9, "PERF: Changed to pass by reference for faster performance", 2008-04-23
This commit restores those "overrides", by adjusting the signature of the `elx::ConjugateGradientFRPR` member functions, in accordance with those ITK member functions.
Bug found by macos-12/clang compiler warnings, like:
> warning: 'elastix::ConjugateGradientFRPR::GetValueAndDerivative' hides overloaded virtual function [-Woverloaded-virtual]
Note: These …

BUG: Let `elx::ConjugateGradientFRPR` override ITK's FRPROptimizer

---

Components/Registrations/MultiMetricMultiResolutionRegistration/itkMultiMetricMultiResolutionImageRegistrationMethod.h
Components/Registrations/MultiResolutionRegistrationWithFeatures/itkMultiInputMultiResolutionImageRegistrationMethodBase.h

Aims to fix warnings like (macos-12/clang):
> warning: 'itk::MultiMetricMultiResolutionImageRegistrationMethod::GetFixedImagePyramid' hides overloaded virtual function [-Woverloaded-virtual]

STYLE: Add const overloads to MultiResolution Get member functions

---

Common/ImageSamplers/itkImageSamplerBase.hxx
Common/itkParabolicErodeDilateImageFilter.h
Common/itkParabolicErodeDilateImageFilter.hxx
Core/Main/GTesting/ElastixLibGTest.cxx

Adjusted `ParabolicErodeDilateImageFilter::SplitRequestedRegion` to ensure that its signature matches `ImageSource::SplitRequestedRegion` (again). Following ITK commit https://github.com/InsightSoftwareConsortium/ITK/commit/c70141073652a8c4fef98495405aea0ac03abd3a, June 14, 2011, which modified the signature of `ImageSource::SplitRequestedRegion`, by replacing signed with unsigned integers.
Similar to pull request https://github.com/SuperElastix/elastix/pull/1118 commit 34bdc3ba92ff5a9854b7b6e9b4b4459766b192d5 "BUG: Let `elx::ConjugateGradientFRPR` override ITK's FRPROptimizer"
Note: This commit changes the behavior (restoring the originally intended behavior), because `ParabolicErodeDilateImageFilter::SplitRequestedRegion` does avoid the current dimension (`m_CurrentDimension`), when …

Let elastix `ParabolicErodeDilateImageFilter::SplitRequestedRegion` override ITK's ImageSource 

---

Components/Optimizers/ConjugateGradientFRPR/elxConjugateGradientFRPR.h
Components/Optimizers/ConjugateGradientFRPR/elxConjugateGradientFRPR.hxx

There was a breaking change in the API of `itk::PowellOptimizer` and `itk::FRPROptimizer`, with ITK commit https://github.com/InsightSoftwareConsortium/ITK/commit/a7b0a734cf79ac82e70a61321b41ccfee4d5feec "ENH: Eliminates variable construct/destruct", Stephen R. Aylward, April 23, 2008: It added overloads of the virtual member functions, `itk::PowellOptimizer::LineBracket`, `itk::PowellOptimizer::BracketedLineOptimize`, and `itk::FRPROptimizer::LineOptimize`, which have an extra parameter, `ParametersType & tempCoord`. The old virtual member functions were then rewritten in terms of the corresponding new overloads.
As a consequence, it does not make sense anymore for `elastix::ConjugateGradientFRPR` to override the old virtual member functions of ITK. With this commit, it overrides the new …

BUG: Fix ConjugateGradientFRPR overrides PowellOptimizer, FRPROptimizer

---

CMakeLists.txt
Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkMultiInputImageToImageMetricBase.h
Common/ImageSamplers/itkImageSamplerBase.h
Common/ImageSamplers/itkVectorContainerSource.h
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Common/Transforms/itkAdvancedCombinationTransform.h
Common/Transforms/itkAdvancedIdentityTransform.h
Common/Transforms/itkAdvancedMatrixOffsetTransformBase.h
Common/Transforms/itkAdvancedTranslationTransform.h
Common/Transforms/itkCyclicBSplineDeformableTransform.h
Common/Transforms/itkStackTransform.h
Common/itkMultiResolutionImageRegistrationMethod2.h
Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.h
Components/Transforms/DeformationFieldTransform/itkDeformationFieldInterpolatingTransform.h
Components/Transforms/ExternalTransform/elxAdvancedTransformAdapter.h
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.h
Components/Transforms/SplineKernelTransform/itkKernelTransform2.h
Components/Transforms/WeightedCombinationTransform/itkWeightedCombinationTransform.h

Addressed those warnings, mostly from macos-12/clang.
Note that these warnings do sometimes help to find actual (potential) bugs, like:
- pull request #1120
- pull request #1118
- pull request #1123
Follow-up to:
-  pull request #1115

Enable and address `-woverloaded-virtual` warnings from GCC or clang

---

Common/Transforms/itkAdvancedRigid2DTransform.h
Common/Transforms/itkAdvancedRigid2DTransform.hxx
Common/Transforms/itkAdvancedSimilarity2DTransform.hxx
Common/Transforms/itkAdvancedSimilarity3DTransform.hxx
Common/Transforms/itkAdvancedVersorRigid3DTransform.h
Common/Transforms/itkAdvancedVersorRigid3DTransform.hxx

Removed the unused "output space dimension" parameter from the constructors of Similarity transform base classes, AdvancedRigid2DTransform and AdvancedVersorRigid3DTransform.
Fixed GCC warnings, like:
> warning: unused parameter 'outputSpaceDim' [-Wunused-parameter]

COMP: Remove unused parameter "spaceDim" from Similarity constructors

---

Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/brute.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_fix_rad_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_pr_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_search.cpp
Components/Metrics/KNNGraphAlphaMutualInformation/KNN/ann_1.1/src/kd_split.cpp

Addressed -Wunused-parameter warnings from GCC.

COMP: Remove the names of unused parameters from KNN/ANN library

---

Components/Metrics/StatisticalShapePenalty/itkStatisticalShapePointPenalty.h
Components/Metrics/StatisticalShapePenalty/itkStatisticalShapePointPenalty.hxx

Removed the unused `centerrotated` parameter from the private member function StatisticalShapePointPenalty::CalculateDerivative
CalculateDerivative already had an unused `centerrotated` parameter with the initial commit 0d330fbb1926ce7e03449d9892ece72ce9401768, Floris Berendsen, 13 May 2013 "ENH: -Add the StatisticalShapePenalty metric module"
Fixed GCC -Wunused-parameter warnings.

COMP: Remove unused parameter from StatisticalShapePointPenalty

---

Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.h
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx

SumSquaredTissueVolumeDifferenceImageToImageMetric::EvaluateInverseSpatialJacobian is a protected non-virtual member function that was unused, and caused warnings, saying:
> warning: unused parameter 'spatialJacobianDeterminant' [-Wunused-parameter]
The member function was already unused with the initial commit of SumSquaredTissueVolumeDifferenceImageToImageMetric: commit c68b557b070a55d2849f2ecf90ddb9d62111d754, Geoffrey Hugo, 15 Dec 2016, "ADD: New metric SumSquaredTissueVolumeDifferenceMetric, a mass-preserving similarity term".

COMP: Remove EvaluateInverseSpatialJacobian from SumSquaredTissue metric

---

Common/itkComputePreconditionerUsingDisplacementDistribution.h
Common/itkComputePreconditionerUsingDisplacementDistribution.hxx

This ComputePreconditionerUsingDisplacementDistribution member function is protected, it is never overridden and never called. And it just throws an exception.
It caused warnings from GCC, like:
> warning: unused parameter 'mu' [-Wunused-parameter]
The member function was introduced with commit 70829754af29b92cb34be5997cda8216eaf6be8c "ENH: merging performance into develop branch", 7 Mar 2019.
----
Just checked: ITK does not have a function named "ComputePreconditionerUsingDisplacementDistribution" either.

COMP: Remove unused function ComputeDistributionTermsUsingSearchDir

---

Components/Metrics/StatisticalShapePenalty/elxStatisticalShapePenalty.h
Components/Metrics/StatisticalShapePenalty/elxStatisticalShapePenalty.hxx

Fixed GCC warning -Wunused-parameter.
ReadShape was introduced with commit 0d330fbb1926ce7e03449d9892ece72ce9401768, Floris Berendsen, 13 May 2013, "-ENH: -Add the StatisticalShapePenalty metric module." With this initial commit, the parameter was already unused.

COMP: Remove unused parameter `image` StatisticalShapePenalty::ReadShape

---

Common/itkComputePreconditionerUsingDisplacementDistribution.h
Common/itkComputePreconditionerUsingDisplacementDistribution.hxx
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx

Fixed GCC warning -Wunused-parameter.
ComputeJacobiTypePreconditioner was introduced with commit 70829754af29b92cb34be5997cda8216eaf6be8c "ENH: merging performance into develop branch", 7 Mar 2019. With that initial commit, the `mu` parameter of this member function was already unused.
Also removed the `virtual` keyword from the  member function declaration. This member function did not have any override anyway. Following C++ Core Guidelines, May 11, 2024 "Don’t make a function `virtual` without reason", http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-virtual

COMP: Remove unused parameter `mu` from ComputeJacobiTypePreconditioner

---

Common/itkParabolicErodeDilateImageFilter.hxx
Core/Install/elxConversion.h

Fixed by casting the left side of the `==` to the largest available integer type of the same "signedness" as the right side.

Fix MSVC /W4 warnings, "warning C4389: '==': signed/unsigned mismatch"

---

Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx

Fixes MSVC /W4 warnings, saying:
> warning C4100: 'inputPixelTypeHolder': unreferenced formal parameter
Note that `[[maybe_unused]]` cannot be used in these case, because of a compiler bug in MSVC 2022, which would produce:
> error C2187: syntax error: 'attribute specifier' was unexpected here
This error occurs with an `auto` parameter of a lambda, when the capture list `[]` is empty.

COMP: Add `(void)` casts to `inputPixelTypeHolder` parameters of GTests

---

Common/Transforms/itkAdvancedEuler3DTransform.hxx
Common/Transforms/itkAdvancedRigid2DTransform.hxx
Common/Transforms/itkAdvancedSimilarity2DTransform.hxx
Common/Transforms/itkAdvancedSimilarity3DTransform.hxx
Components/Transforms/AffineDTITransform/itkAffineDTI2DTransform.hxx
Components/Transforms/AffineDTITransform/itkAffineDTI3DTransform.hxx

`ParametersDimension` is always specified at compile time by the transform type itself.
This commit might improve run-time performance.

STYLE: Replace `if (ParametersDimension ...)` clauses with static_assert

---

Common/OpenCL/Filters/itkGPUResampleImageFilter.hxx
Common/OpenCL/ITKimprovements/itkOpenCLKernelToImageBridge.hxx
Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx
Common/Transforms/itkRecursiveBSplineTransformImplementation.h
Components/FixedImagePyramids/OpenCLFixedGenericPyramid/elxOpenCLFixedGenericPyramid.hxx
Components/Metrics/DistancePreservingRigidityPenalty/itkDistancePreservingRigidityPenaltyTerm.hxx
Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx
Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx
Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx
Components/MovingImagePyramids/OpenCLMovingGenericPyramid/elxOpenCLMovingGenericPyramid.hxx
Components/Transforms/AdvancedAffineTransform/elxAdvancedAffineTransform.hxx
Components/Transforms/AdvancedAffineTransform/itkCenteredTransformInitializer2.hxx
Components/Transforms/AffineDTITransform/elxAffineDTITransform.hxx
Components/Transforms/EulerTransform/elxEulerTransform.hxx
Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx
Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.hxx
Testing/itkAdvancedLinearInterpolatorTest.cxx
Testing/itkGPUResampleImageFilterTest.cxx
Testing/itkMevisDicomTiffImageIOTest.cxx

Ensures that the `if` is evaluated at compile-time. Might (slightly) improve compile-time or run-time performance.
Cases found by the regular expression ` if \(\w*Dimension `.

STYLE: Add constexpr to `if (Dimension ...)` statements

---

Components/Metrics/PCAMetric/itkPCAMetric.h
Components/Metrics/PCAMetric/itkPCAMetric.hxx

Note that "itkPCAMetric.h" and "itkPCAMetric.hxx" appear superseded by "itkPCAMetric_F_multithreaded.h" and "itkPCAMetric_F_multithreaded.hxx", respectively.

Fix warnings from "itkPCAMetric.h" and "itkPCAMetric.hxx"

---

Common/itkComputeDisplacementDistribution.hxx

The unused local `jacjjacj` variable appears to be introduced with commit e9de4b1281a07d2fdbaa96db865f3c7aaaf4e5d2 "ENH: manual syncing with the performance branch", 25 May 2016.
In other cases, such a variable is (post-)initialized by `vnl_fastops::ABt(jacjjacj, jacj, jacj)`, but in this case, it was left uninitialized.

STYLE: Remove unused jacjjacj variable from ComputeUsingSearchDirection

---

Common/itkComputeJacobianTerms.hxx

This particular `samplenr` variable was only used as argument for commented-out `progressObserver->UpdateAndPrintProgress` calls.
Those `progressObserver->UpdateAndPrintProgress` calls were already commented-out with commit e9de4b1281a07d2fdbaa96db865f3c7aaaf4e5d2 (May 25, 2016): https://github.com/SuperElastix/elastix/blob/e9de4b1281a07d2fdbaa96db865f3c7aaaf4e5d2/src/Common/itkComputeJacobianTerms.hxx#L235-L236
Follow-up to pull request https://github.com/SuperElastix/elastix/pull/1111 "COMP: Fix `-Wshadow` warnings on local `samplenr` variable"

STYLE: Remove `samplenr` which was used in commented-out code in Compute

---

Common/GTesting/elxTransformIOGTest.cxx
Common/Transforms/itkAdvancedEuler3DTransform.h
Common/Transforms/itkAdvancedEuler3DTransform.hxx

Following ITK commit https://github.com/InsightSoftwareConsortium/ITK/commit/47c24916609afbd078f2fc51d81962a62be08f7a "BUG: Interpretation of the Euler angles ZYX or ZXY was not exported.", Ziv Yaniv (@zivy), May 9, 2016.
Implementation of `GetFixedParameters`, `SetFixedParameters`, and `SetComputeZYX` mostly copied from "itkEuler3DTransform.h" and "itkEuler3DTransform.hxx", in  https://github.com/InsightSoftwareConsortium/ITK/tree/v5.4.0/Modules/Core/Transform/include
GoogleTest `TransformedPointSameAsITKEuler3D` extended to test ComputeZYX = true. `DefaultElastixFixedParametersAreZeroOrEmpty` test adjusted to allow fixedParameters.size() unequal to NDimension. `CopyDefaultEulerTransformElastix3DFixedParametersToCorrespondingItkTransform` test removed, as 3D EulerTransform is now fully …

BUG: Add ComputeZYX to FixedParameters of AdvancedEuler3DTransform

---

Common/GTesting/elxTransformIOGTest.cxx
Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx

Supports specifying parameter `(ComputeZYX "true")`, when the transform is "EulerStackTransform" and the image stack is 4D (meaning that the images are 3D).
Triggered by a question from Laurens Beljaards.

ENH: Add support ComputeZYX parameter to EulerStackTransform (for 3D)

---

CMakeLists.txt
CONTRIBUTING.md
Common/itkComputeDisplacementDistribution.h
Common/itkGenericMultiResolutionPyramidImageFilter.h
Components/Optimizers/AdaGrad/elxAdaGrad.h
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.h
Core/Kernel/elxElastixBase.cxx
Core/Main/elastix.cxx
Core/Main/transformix.cxx
Dockerfile
README.md
Testing/PythonTests/transformix_test.py
dox/README.txt
dox/createWebsite
dox/externalproject/ElastixTranslationExample.cxx

Our new web site is https://elastix.dev/
With a big THANK YOU to our colleague Michèle Huijberts (@mwjhhuijberts)!

DOC: Replace "elastix.lumc.nl" with "elastix.dev"

---

Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx

It appears preferable to properly zero-fill those objects during their construction.

Replace vnl `fill(RealType{})` calls with use of zero-filling constructors.

---

Testing/CI/Azure/ci.yml

Addressing errors at dev.azure.com saying:
> ##[error]This is a scheduled macOS-11 brownout. The macOS-11 environment is deprecated and will be removed on June 28th, 2024.

COMP: Upgrade Azure Pipelines CI yml file from macOS-11 to macOS-12

---

Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.h

Initialized `SumOfPairwiseCorrelationCoefficientsMetric::TransformIsStackTransform` to false. Otherwise it would always be true.
Other metrics (PCAMetric, PCAMetric2, VarianceOverLastDimension) have a similar TransformIsStackTransform property, but those are initialized to false, during the construction of those metrics.
- Addresses issue https://github.com/SuperElastix/elastix/issues/1159 "SumOfPairwiseCorrelationCoefficientsMetric m_TransformIsStackTransform always true?!?"

BUG: SumOfPairwiseCorrelationCoefficientsMetric TransformIsStack `false`

---

Components/Metrics/PCAMetric/elxPCAMetric.hxx
Components/Metrics/PCAMetric2/elxPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/elxSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/VarianceOverLastDimension/elxVarianceOverLastDimensionMetric.hxx

Aims to improve code readability of those `BeforeEachResolution()` member functions

Metrics: Remove local `testPtr4` variables from `BeforeEachResolution()` member functions, rename `testPtr1`, `testPtr2`, and `testPtr3` 

---

Components/Metrics/PCAMetric/elxPCAMetric.hxx
Components/Metrics/PCAMetric2/elxPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/elxSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/VarianceOverLastDimension/elxVarianceOverLastDimensionMetric.hxx

Whenever BeforeEachResolution() detects that there is _no_ stack transform as current transform, let it set TransformIsStackTransform = false, just like it sets TransformIsStackTransform = true when the current transform _is_ a stack transform.
----
- @stefanklein Do you agree that this would be a useful commit? Or would it be unnecessary? (TransformIsStackTransform is now already initialized to false during the construction of all four metrics, with pull request #1163. So I wonder if it's useful to then reset this property with each BeforeEachResolution() call.)

BUG: Do `SetTransformIsStackTransform(false)` in BeforeEachResolution()

---

Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx

The prefix `this->` is not necessary when a class accesses its own private data.
- Follow-up to pull request https://github.com/SuperElastix/elastix/pull/1154 commit bc62b722869119cdfe4a0e87313d112ffaf7d0c1

STYLE: Remove `this->` when Metrics itk*.hxx access their own data data

---

Common/Transforms/itkCyclicBSplineDeformableTransform.hxx
Common/itkNDImageTemplate.hxx
Common/itkParabolicErodeDilateImageFilter.hxx
Components/Interpolators/RayCastInterpolator/elxRayCastInterpolator.hxx
Components/Metrics/GradientDifference/elxGradientDifferenceMetric.hxx
Components/Metrics/NormalizedGradientCorrelation/elxNormalizedGradientCorrelationMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/PatternIntensity/elxPatternIntensityMetric.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx
Components/ResampleInterpolators/RayCastResampleInterpolator/elxRayCastResampleInterpolator.hxx

It appears unnecessary to estimate the image dimensionality at run-time, as it is usually already known at compile-time. This pull request might yield some performance improvement.

Replace `itk::ImageBase<Dimension>::GetImageDimension()` calls

---

Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/itkCorrespondingPointsEuclideanDistancePointMetric.hxx
Components/Metrics/DisplacementMagnitudePenalty/itkDisplacementMagnitudePenaltyTerm.hxx
Components/Metrics/DistancePreservingRigidityPenalty/itkDistancePreservingRigidityPenaltyTerm.hxx
Components/Metrics/GradientDifference/itkGradientDifferenceImageToImageMetric2.hxx
Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx
Components/Metrics/MissingStructurePenalty/itkMissingStructurePenalty.hxx
Components/Metrics/NormalizedGradientCorrelation/itkNormalizedGradientCorrelationImageToImageMetric.hxx
Components/Metrics/NormalizedMutualInformation/itkParzenWindowNormalizedMutualInformationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/PatternIntensity/itkPatternIntensityImageToImageMetric.hxx
Components/Metrics/PolydataDummyPenalty/itkPolydataDummyPenalty.hxx
Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx
Components/Metrics/StatisticalShapePenalty/itkStatisticalShapePointPenalty.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx
Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx
Components/Registrations/MultiMetricMultiResolutionRegistration/itkCombinationImageToImageMetric.hxx

Avoided allocation of an expensive temporary `DerivativeType` object, and reused the existing data buffer of `derivative` (if already had the right size).
----
May improve the run-time performance of many (if not all) metric classes.

PERF: Replace `derivative = DerivativeType(`n`)` with `derivative.set_size(`n`)`

---

Components/Metrics/PCAMetric/elxPCAMetric.hxx
Components/Metrics/PCAMetric2/elxPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/elxSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/VarianceOverLastDimension/elxVarianceOverLastDimensionMetric.hxx

The GridSize is only relevant when the transform is _not_ a stack transform!
----
@stefanklein This looks strange to me: each of those three metrics _fill_ their GridSize with numberOfSubTransforms. So for 3D, the grid size would then become numberOfSubTransforms x numberOfSubTransforms x numberOfSubTransforms. But they do so, specifically when the transform is a stack transform. And they do so from the very first commit, by Wyke (@whuizinga) 764490d5e37de792fea4340fc11850bfd067318d, Nov 24, 2015. Looking at elxPCAMetric.hxx: 
https://github.com/SuperElastix/elastix/blob/764490d5e37de792fea4340fc11850bfd067318d/src/Components/Metrics/PCAMetric/elxPCAMetric.hxx#L115-L132
But they only seem to _use_ their GridSize (or at least `m_GridSize[lastDim]`) when the transform is _not_ a stack …

STYLE: Do not set GridSize when TransformIsStackTransform, in Metrics

---

Components/Metrics/PCAMetric/elxPCAMetric.h
Components/Metrics/PCAMetric/elxPCAMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric.h
Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.h
Components/Metrics/PCAMetric/itkPCAMetric_F_multithreaded.hxx
Components/Metrics/PCAMetric2/elxPCAMetric2.h
Components/Metrics/PCAMetric2/elxPCAMetric2.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.h
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/elxSumOfPairwiseCorrelationCoefficientsMetric.h
Components/Metrics/SumOfPairwiseCorrelationsMetric/elxSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.h
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/VarianceOverLastDimension/elxVarianceOverLastDimensionMetric.h
Components/Metrics/VarianceOverLastDimension/elxVarianceOverLastDimensionMetric.hxx
Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.h
Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx

Sets its default "true". (For the affected elastix metrics (`PCAMetric`, `PCAMetric2`, `SumOfPairwiseCorrelationCoefficients`, `VarianceOverLastDimension`), the SubtractMean parameter originally had "false" as default.)
The term "UseZeroAverageDisplacementConstraint" is more specific than "SubtractMean", so it appears preferably. Discussed with Marius  (@mstaring) and Stefan (@stefanklein).
Added a warning about this change to the `Initialize()` member functions of the affected elastix metrics.
If "SubtractMean" is specified, now using its value as default for "UseZeroAverageDisplacementConstraint", for backward compatibility.
----
- This pull request supersedes pull request #1104

ENH: Replace "SubtractMean" with "UseZeroAverageDisplacementConstraint"

---

Common/ImageSamplers/itkImageRandomSamplerSparseMask.hxx
Common/itkComputeDisplacementDistribution.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx

Avoided unnecessary memory relocations.

Let SampleRandom, ImageRandomSamplerSparseMask, ComputeDisplacementDistribution call `std::vector::reserve`

---

Common/itkParabolicErodeDilateImageFilter.hxx

Declaring `ProgressReporter` on the stack (instead of on the heap) may benefit run-time performance. But moreover, it fixes a memory leak.
- Corresponds with pull request https://github.com/richardbeare/parabolicMorphology/pull/11 "BUG: Fix memory leaks by moving `progress` from the heap to the stack"

BUG: Fix ParabolicErodeDilateImageFilter progress memory leak, use stack

---

Common/itkComputeJacobianTerms.hxx

- Now that pull request https://github.com/vxl/vxl/pull/926 commit https://github.com/vxl/vxl/commit/653919faf49eaa257d2357e570f7cfa8fb738f0b "PERF: Speed up `vnl_sparse_matrix::operator()`" is merged, it appears no longer useful to maintain our own `getCovariance` alternative.
This reverts pull request https://github.com/SuperElastix/elastix/pull/959 commit 3979978aaf712c3c78cacdf64eb451aff6eb553d "PERF: Speed up ComputeJacobianTerms access to `vnl_sparse_matrix`"

STYLE: Rely on `vnl_sparse_matrix::operator()` again

---

Components/Metrics/PCAMetric/elxPCAMetric.h
Components/Metrics/PCAMetric/elxPCAMetric.hxx
Components/Metrics/PCAMetric2/elxPCAMetric2.h
Components/Metrics/PCAMetric2/elxPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/elxSumOfPairwiseCorrelationCoefficientsMetric.h
Components/Metrics/SumOfPairwiseCorrelationsMetric/elxSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/VarianceOverLastDimension/elxVarianceOverLastDimensionMetric.hxx

Instead of setting them in `BeforeEachResolution()`. These properties always have the same value for each resolution of a registration.
Discussed with Marius (@mstaring) and Stefan (@stefanklein).

STYLE: Set GridSize, TransformIsStackTransform in `BeforeRegistration()`

---

Common/itkParabolicErodeDilateImageFilter.hxx

ParabolicErodeDilateImageFilter should not compute the number of rows for _all_ dimensions, only just for its `m_CurrentDimension`.

STYLE: ParabolicMorphology compute numberOfRows only for one dimension

---

Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx

Removed `#include <omp.h>` from components that do not use OpenMP

STYLE: Remove unnecessary `#include <omp.h>` directives

---

CMakeLists.txt
Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/GTesting/elxElastixMainGTest.cxx
Common/GTesting/itkAdvancedImageToImageMetricGTest.cxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/elxAdvancedMeanSquaresMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.h
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.h
Components/Optimizers/StandardGradientDescent/itkGradientDescentOptimizer2.cxx
Components/Optimizers/StandardGradientDescent/itkGradientDescentOptimizer2.h
Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx
Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.h
Testing/itkAccumulateDerivativesParallellizationTest.cxx
Testing/itkAdvanceOneStepParallellizationTest.cxx
dox/externalproject/CMakeLists.txt

Removed unreachable `if` clauses of the form `if (x && false)`, `else` clauses of `if (true)` or `if (x || true)`, and `#else` parts of `#if 1`.
Removed unused `#include <omp.h>` directives.
Removed unreachable code that was specifically for either a single-threaded or a multi-threaded implementation.
----
When reviewing the code, it may help to hide whitespace changes: https://github.com/SuperElastix/elastix/pull/1188/files?w=1

Remove OpenMP based code, ELASTIX_USE_OPENMP option and OpenMP compiler flags

---

Common/itkComputeDisplacementDistribution.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/itkStochasticVarianceReducedGradientDescentOptimizer.cxx
Components/Optimizers/FiniteDifferenceGradientDescent/itkFiniteDifferenceGradientDescentOptimizer.cxx
Components/Optimizers/RSGDEachParameterApart/itkRSGDEachParameterApartBaseOptimizer.cxx
Components/Optimizers/StandardGradientDescent/itkGradientDescentOptimizer2.cxx
Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx

Avoided allocation of a possibly expensive temporary `DerivativeType` object, and reused the existing data buffer of the existing `DerivativeType` object (if already had the right size).
- Follow-up to pull request #1175 commit c5a04519f34feb13c4af8fa06979a1d48cfc4e87 "PERF: Replace derivative = DerivativeType(n) with derivative.set_size(n)"

PERF: Replace `x = DerivativeType(n)` with `x.set_size(n)`

---

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Components/Metrics/DistancePreservingRigidityPenalty/itkDistancePreservingRigidityPenaltyTerm.hxx

No need to explicitly construct an `ImageRegion` object, when its `Index` would just be zero anyway.
Two style commits.

Just pass the image size to `SetRegions` calls, no need to construct an `ImageRegion` object 

---

Core/Kernel/elxMainBase.cxx

It appears that `SetGlobalMaximumNumberOfThreads` may not affect the size of ITK's ThreadPool. The ThreadPool only uses "GlobalDefaultNumberOfThreads".
- Related to ITK issue https://github.com/InsightSoftwareConsortium/ITK/issues/4773 "GlobalDefaultNumberOfThreads should not be greater than GlobalMaximumNumberOfThreads"
----
@Svdvoort This should at least partially address the multi-threading issues you reported

BUG: Call `SetGlobalDefaultNumberOfThreads` when processing "-threads"

---

dox/doxygen/MainPage.dox.in

Allows to just place the next manual at one location (at github.com/SuperElastix/elastix/releases/download).
Discussed with Marius (@mstaring) and Stefan (@stefanklein), by mail.

DOC: Replace relative link to manual in elastix website with GitHub link

---

Core/Kernel/elxElastixBase.cxx
Core/Kernel/elxElastixBase.h
Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixMain.h
Core/Kernel/elxElastixTemplate.h
Core/Kernel/elxElastixTemplate.hxx
Core/Kernel/elxTransformixMain.cxx
Core/Main/elastix.cxx
Core/Main/elastixlib.cxx
Core/Main/itkElastixRegistrationMethod.hxx

A few style improvements to improve readability of the code related to the flat representation of the direction of the fixed image.

Append "Flat" to "OriginalFixedImage/fixedImageOriginal" Direction identifiers, replace some `this->`

---

Core/Kernel/elxElastixBase.cxx

The UseDirectionCosines parameter now has default value "true", which is the recommended value already.
Suggested by Stefan Klein (@stefanklein) at today's weekly internal sprint.
- Addresses issue #1207

STYLE: Remove warning when UseDirectionCosines is unspecified

---

Common/Transforms/itkAdvancedRigid3DTransform.h

Replaced "column-major order" with "row-major order", which is the correct term in this case.
Following ITK commit https://github.com/InsightSoftwareConsortium/ITK/commit/a2eccee89a115c5c198a41cb0648f3368fc21eae "STYLE: Fixed documentation about the parameters of AffineTransform and Rigid3DTransform. The first parameters are the matrix elements in row-major order an not column-major", Tom Vercauteren, 17 Jun 2009

DOC: Fix documentation about order of matrix elements Rigid3DTransform

---

Common/Transforms/itkAdvancedBSplineDeformableTransform.h
Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx

Using C-style arrays instead of `std::vector` might improve the run-time performance of `AdvancedBSplineDeformableTransform`.
Also made m_WeightsFunction const, and did clean-up the default-constructor of AdvancedBSplineDeformableTransform.

Declare AdvancedBSplineDeformableTransform data members as C-style array, remove `this->`

---

Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h

Removed `m_Offset` and used modern C++ `Type{ ... }` type conversions.

Simplify offset estimations for `AdvancedBSplineDeformableTransform::SetGridRegion`

---

README.md

Discussed with Marius Staring and Stefan Klein, at our weekly internal elastix sprint meeting.

DOC: Add references to Zenodo to README, for software DOIs

---

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Common/Transforms/itkBSplineInterpolationWeightFunctionBase.hxx
Common/Transforms/itkTransformToDeterminantOfSpatialJacobianSource.hxx
Common/Transforms/itkTransformToSpatialJacobianSource.hxx
Common/itkMultiOrderBSplineDecompositionImageFilter.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/DistancePreservingRigidityPenalty/itkDistancePreservingRigidityPenaltyTerm.hxx
Components/Metrics/NormalizedGradientCorrelation/itkNormalizedGradientCorrelationImageToImageMetric.hxx
Components/Metrics/PatternIntensity/itkPatternIntensityImageToImageMetric.hxx
Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.hxx
Testing/elxComputeOverlap.cxx
Testing/itkAdvancedLinearInterpolatorTest.cxx
Testing/itkMevisDicomTiffImageIOTest.cxx

It is unnecessary to call GoToBegin() on an ITK iterator when it has just been constructed, by `Iterator(image, region)`. Such a function call just takes compile-time and run-time.
- Supported by ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4815

Remove GoToBegin() calls after iterator construction, move iterator variable declarations into init-statement of `for`

---

Common/ImageSamplers/itkImageFullSampler.h
Common/ImageSamplers/itkImageGridSampler.h
Common/ImageSamplers/itkImageRandomCoordinateSampler.h
Common/ImageSamplers/itkImageRandomSampler.h
Common/ImageSamplers/itkImageRandomSamplerSparseMask.h

On GCC 12.2.2 (Debian):
/home/matt/src/elastix/Common/ImageSamplers/itkImageGridSampler.hxx: In instantiation of ‘static void itk::ImageGridSampler<TInputImage>::MultiThreadedGenerateData(itk::MultiThreaderBase&, itk::ThreadIdType, const TInputImage&, const MaskType*, const typename Superclass::InputImageRegionType&, const SampleGridSpacingType&, std::vector<typename itk::ImageSamplerBase<TInputImage>::ImageSampleType>&) [with TInputImage = itk::Image<short int, 4>; itk::ThreadIdType = unsigned int; MaskType = itk::ImageMaskSpatialObject<4, unsigned char>; typename Superclass::InputImageRegionType = itk::ImageRegion<4>; Superclass = itk::ImageSamplerBase<itk::Image<short int, 4> >; SampleGridSpacingType = itk::Offset<4>; typename itk::ImageSamplerBase<TInputImage>::ImageSampleType = …

COMP: Remove ITK_DISALLOW_COPY_AND_MOVE from UserData struct's

---

Common/ImageSamplers/itkImageRandomSamplerSparseMask.h

The line of comment appeared to cause a GitHub Actions CI failure from "test-clang-format / build (push)" (DoozyX/clang-format-lint-action) saying:
-    //ITK_DISALLOW_COPY_AND_MOVE(UserData);
+    // ITK_DISALLOW_COPY_AND_MOVE(UserData);
- Follow-up to pull request https://github.com/SuperElastix/elastix/pull/1202 commit 359148b82f8e07a734af86fd4c8c75e4d422d3ed

STYLE: Remove commented out `ITK_DISALLOW_COPY_AND_MOVE` call

---

Common/OpenCL/Filters/itkGPUShrinkImageFilter.hxx

Adjusted its `GPUGenerateData()` member function to call the faster `TransformPhysicalPointToIndex` overload.
Addresses MSVC compiler warnings saying:
itkGPUShrinkImageFilter.hxx(109,39): warning C4834: discarding return value of function with [[nodiscard]] attribute
Similar to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2873 commit https://github.com/InsightSoftwareConsortium/ITK/commit/eb6ac88c8209ff6cfb3f280bb25e8388f236e211 "Use the faster `TransformPhysicalPointToIndex` overload in filter", November 16, 2021.

PERF: itkGPUShrinkImageFilter use faster TransformPhysicalPointToIndex

---

Common/MevisDicomTiff/itkUseMevisDicomTiff.cxx

The definition of the enumerator `INSERT_AT_FRONT` has moved into an `enum class`, with pull request https://github.com/InsightSoftwareConsortium/ITK/pull/1061 commit https://github.com/InsightSoftwareConsortium/ITK/commit/4fe3b5de74c6114e907747758746b3c4ea4406ff "STYLE: Convert 'enum' to 'enum class' objects with print enum function", Hans Johnson and Mathew J. Seng, merged on August 23, 2019. As this ITK commit was included with ITK 5.1, the `ELASTIX_USE_MEVISDICOMTIFF` option would depend on ITK's legacy support, in order to make it compile with elastix 5.0.1, 5.1.0, or 5.2.0.

COMP: Make itkUseMevisDicomTiff.cxx compile with ITK >= 5.1

---

Common/Transforms/itkCyclicBSplineDeformableTransform.hxx
Core/Main/elxParameterObject.cxx
Core/Main/itkTransformixFilter.hxx

Addressed clang-tidy (LLVM 18.1.8) messages, saying
> use range-based for loop instead [modernize-loop-convert]

STYLE: Use modern C++ range-based `for` loops in Core/Main and Common

---

Components/Optimizers/ConjugateGradient/itkGenericConjugateGradientOptimizer.h
Components/Transforms/AdvancedAffineTransform/elxAdvancedAffineTransform.hxx
Components/Transforms/AffineDTITransform/elxAffineDTITransform.hxx
Components/Transforms/AffineLogStackTransform/elxAffineLogStackTransform.hxx
Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.hxx
Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx
Components/Transforms/EulerTransform/elxEulerTransform.hxx
Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx
Core/Main/elxParameterObject.cxx
Core/Main/itkTransformixFilter.hxx

Aims to resolve issue https://github.com/SuperElastix/elastix/issues/1224 "Missing semicolons causing compile issues with some compilers".
ITK has become stricter with respect to those semicolons from ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4706 commit https://github.com/InsightSoftwareConsortium/ITK/commit/55e23393e1d2c2e71d919d33459201fcee364655 "ENH: Default to allow ITK_MACROEND_NOOP_STATEMENT", Hans Johnson, June 4, 2024.

COMP: Add missing semicolons to ITK macro calls

---

Common/OpenCL/ITKimprovements/itkOpenCLVector.hxx
Core/Main/itkElastixRegistrationMethod.hxx

- Follow-up to pull request https://github.com/SuperElastix/elastix/pull/1227 commit 7b99c207a222fec33bf4aceaf47a949c0f341afb "COMP: Add missing semicolons to ITK macro calls"

COMP: Add missing semicolons to ElastixRegistrationMethod and OpenCL

---

Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.hxx

Ensured that "-fp" has priority over "-ipp"

Improve elastix `SplineKernelTransform` handling "-ipp"/"-fp" landmark file parameter

---

Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/elxCorrespondingPointsEuclideanDistanceMetric.hxx
Components/Metrics/MissingStructurePenalty/elxMissingStructurePenalty.hxx
Components/Metrics/PolydataDummyPenalty/elxPolydataDummyPenalty.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Configuration/elxConfiguration.cxx
Core/Kernel/elxElastixBase.cxx

- Following pull request #799 commit 79e227907b4887453ce5af1460ae32131bdc2014 "ENH: Replace xout with log warn, error, info, to_stdout, to_log_file"

Remove `std::ostringstream{} << ` when logging a literal string or a command-line argument

---

Common/CostFunctions/itkSingleValuedPointSetToPointSetMetric.h
Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/itkCorrespondingPointsEuclideanDistancePointMetric.hxx

The use of `GetFixedPoints()` and `GetMovingPoints()`, which return a reference to the internal `std::vector` of the point set, may slightly improve the run-time performance.

Use GetFixedPoints, GetMovingPoints in CorrespondingPointsEuclideanDistanceMetric and other style improvements

---

Components/Metrics/StatisticalShapePenalty/itkStatisticalShapePointPenalty.hxx

May slightly improve the performance, by iterating over an `std::vector` of points, instead of an `itk::PointSet::PointsVectorContainer`.
- Follow-up to pull request #1233 commit 9bedfdc66ef566aa993613ab4877f75944d59b1c "STYLE: CorrespondingPointsEuclideanDistanceMetric GetFixed/MovingPoints"

STYLE: Use GetFixedPoints() in StatisticalShapePointPenalty

---

.github/workflows/clang_format_check.yml

Aims to fix errors at the CI, saying:
File "/run-clang-format.py", line 25, in <module>
from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
----
Upgraded clang-format-lint-action to its latest tag, https://github.com/DoozyX/clang-format-lint-action/releases/tag/v0.18.2 released on September 4, 2024.
Also upgraded actions/checkout to its latest tag, https://github.com/actions/checkout/releases/tag/v4.1.7 from June 12, 2024

COMP: Upgrade clang-format-lint-action to v0.18.2

---

Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/itkCorrespondingPointsEuclideanDistancePointMetric.hxx

Removed unnecessary conversion from `itk::Vector` to vnl_vector, when retrieving the norm (the magnitude) of a vector (movingPoint - mappedPoint), in `CorrespondingPointsEuclideanDistancePointMetric`.
Appears to make `GetValue` more that 7 times faster (from more than 0.07 sec. down to less than 0.009 sec. on 1 million 3D points), as observed on Visual C++ 2022.

PERF: EuclideanDistanceMetric get vector norm without GetVnlVector()

---

Core/Main/itkElastixRegistrationMethod.h

Added a constant for the common dimensionality of fixed and moving image. Assumed that `FixedImageDimension` and `MovingImageDimension` are always equal. Discussed with Marius (@mstaring), yesterday at the weekly internal elastix sprint.
@stefanklein I hope you agree! Otherwise please say so!

ENH: Add `ElastixRegistrationMethod::ImageDimension`

---

Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/elxCorrespondingPointsEuclideanDistanceMetric.h
Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/elxCorrespondingPointsEuclideanDistanceMetric.hxx

Refactored `CorrespondingPointsEuclideanDistanceMetric::BeforeRegistration()` and checked that both point sets are specified.

ENH: EuclideanDistanceMetric check that point sets are specified

---

Common/OpenCL/ITKimprovements/itkGPUImageDataManager.h
Common/OpenCL/ITKimprovements/itkGPUImageDataManager.hxx

This fixes a memory leak issue, #37.
The problem is a circular reference between `GPUImage` and `GPUImageDataManager` in the function [`GPUImage::AllocateGPU()`](https://github.com/SuperElastix/elastix/blob/368d71649c9052b47396b9eb7c0069fa7ea24b7f/Common/OpenCL/ITKimprovements/itkGPUImage.hxx#L80), which calls `m_DataManager->SetImagePointer(this);` using a smart pointer as argument.
The solution is given in the ITK library, [`itkGPUImageDataManager.h`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/GPUCommon/include/itkGPUImageDataManager.h), which makes `m_Image` a weak pointer.

PERF: Make `GPUImageDataManager->m_Image` a weak pointer

---

Common/OpenCL/ITKimprovements/itkOpenCLContext.cxx
Common/OpenCL/ITKimprovements/itkOpenCLDevice.cxx
Common/OpenCL/ITKimprovements/itkOpenCLDevice.h
Common/OpenCL/ITKimprovements/itkOpenCLEventList.cxx
Common/OpenCL/ITKimprovements/itkOpenCLKernelManager.cxx
Common/OpenCL/ITKimprovements/itkOpenCLPlatform.cxx
Common/OpenCL/ITKimprovements/itkOpenCLPlatform.h
Common/OpenCL/ITKimprovements/itkOpenCLProgram.cxx
Common/OpenCL/itkOpenCLSetup.cxx
Testing/itkGPUFactoriesTest.cxx
Testing/itkGPUResampleImageFilterTest.cxx
Testing/itkOpenCLContextTest.cxx
Testing/itkOpenCLDeviceTest.cxx
Testing/itkOpenCLPlatformTest.cxx

Addressed clang-tidy (LLVM 18.1.8) messages, saying
> use range-based for loop instead [modernize-loop-convert]
@dpshamonin Can you please have a look?

Use modern C++ range-based for loops in OpenCL/GPU based code

---

Common/OpenCL/ITKimprovements/itkOpenCLVector.hxx

- Fixed issue #1248 "itkOpenCLVector.hxx line 113, missing ;", submitted by Nick Lekkas (@NickLekkas-AIMedical)
- Follow-up to pull request https://github.com/SuperElastix/elastix/pull/1228 commit c41fdd6a4ceb460348e25b8bb0861a536c97dd5e "COMP: Add missing semicolons to ElastixRegistrationMethod and OpenCL"
Co-authored-by: NickLekkas-AIMedical

COMP: Add missing semicolon to macro call itkOpenCLVector.hxx line 113

---

Core/Main/elxParameterObject.cxx
Core/Main/elxParameterObject.h

Addressed LLVM 19.1.0 clang-tidy warnings, saying:
> warning: return type 'const ParameterObject::ParameterMapType' is 'const'-qualified at the top level, which may reduce code readability without improving const correctness [readability-const-return-type]

STYLE: Remove top level const from GetDefaultParameterMap return type

---

Common/Transforms/itkAdvancedCombinationTransform.hxx

- Used modern C++17 `if (initialization; condition)` notation
- Returned directly when ready, removing unnecessary local variables

STYLE: Clean up `AdvancedCombinationTransform::GetNthTransform`

---

Core/ComponentBaseClasses/elxTransformBase.hxx
Testing/PythonTests/transformix_test.py

When using transformix command-line option "-def" to transform the points of a VTK file, the output was always an ASCII file, having double-precision (64-bit) floating point numbers.
With this pull request, the format (ASCII or binary) and the floating point precision of the output file will correspond with the input file, instead.
- Inspired by pull request #943, @ChristophKirst, Aug 2, 2023.
---
When reviewing this pull request, it may be convenient to ignore whitespace changes: https://github.com/SuperElastix/elastix/pull/1253/files?w=1

Transform VTK files in accordance with their format and floating point precision

---

Common/OpenCL/itkGPUKernelManagerHelperFunctions.h
Components/Interpolators/RayCastInterpolator/elxRayCastInterpolator.hxx
Components/ResampleInterpolators/RayCastResampleInterpolator/elxRayCastResampleInterpolator.hxx
Components/Transforms/BSplineDeformableTransformWithDiffusion/itkDeformationFieldRegulizer.hxx
Components/Transforms/DeformationFieldTransform/itkDeformationFieldInterpolatingTransform.hxx
Components/Transforms/SplineKernelTransform/itkKernelTransform2.hxx

Replaced code of the form
Type var;
var.Fill(0);
and
Type var;
var.Fill(ElementType{});
with `Type var{};`
Using Notepad++, Replace in Files, doing:
Find what: ^( [ ]+)([^ ].* )(\w+);[\r\n]+\1\3\.Fill\(0\.?0?\);
Find what: ^( [ ]+)([^ ].* )(\w+);[\r\n]+\1\3\.Fill\(.*{}\);
Replace with: $1$2$3{};
[v] Match case
(*) Regular expression
- Following ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4897 commit https://github.com/InsightSoftwareConsortium/ITK/commit/47335501a5a16c6eb42538a829d4b49229284dd6

STYLE: Replace `Fill(0)` on local variables with `{}` initialization

---

Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx
Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.hxx
Components/Transforms/SplineKernelTransform/itkKernelTransform2.hxx

Using Notepad++, Replace in Files, doing:
Find what: ^( [ ]+)([^ ].* )(\w+);[\r\n]+\1\3\.Fill\(0[uU]\);
Find what: ^( [ ]+)([^ ].* )(\w+);[\r\n]+\1\3\.Fill\(0.0[fF]\);
Replace with: $1$2$3{};
[v] Match case
(*) Regular expression
- Follow-up to pull request https://github.com/SuperElastix/elastix/pull/1257 commit 0bece236791d1f0cc165b94de090add7ed45fece "STYLE: Replace `Fill(0)` on local variables with `{}` initialization"

STYLE: Replace `Fill(0U)` and `Fill(0.0f)` on local variables with `{}`

---

Common/CostFunctions/itkSingleValuedPointSetToPointSetMetric.h
Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/itkCorrespondingPointsEuclideanDistancePointMetric.h
Components/Metrics/MissingStructurePenalty/itkMissingStructurePenalty.h
Components/Metrics/PolydataDummyPenalty/itkPolydataDummyPenalty.h
Components/Metrics/PolydataDummyPenalty/itkPolydataDummyPenalty.hxx
Components/Metrics/StatisticalShapePenalty/itkStatisticalShapePointPenalty.h

Paving the way to extend PointSet support.

Remove unused `PointDataIterator` and `PointSetPixelType` typedefs

---

Components/Metrics/CorrespondingPointsEuclideanDistanceMetric/elxCorrespondingPointsEuclideanDistanceMetric.hxx
Core/Kernel/elxElastixBase.h
Core/Kernel/elxElastixMain.cxx
Core/Kernel/elxElastixMain.h
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/itkElastixRegistrationMethod.h
Core/Main/itkElastixRegistrationMethod.hxx

Currently trying it out in Python:
```python
Dimension = 2
ImageType = itk.Image[itk.UC, Dimension]
PointType = itk.Point[itk.D, Dimension]
PointContainerType = itk.VectorContainer[itk.ULL, PointType]
fixed_image = ImageType.New()
fixed_image.SetRegions(itk.Size[Dimension].Filled(8))
fixed_image.AllocateInitialized()
moving_image = ImageType.New()
moving_image.SetRegions(itk.Size[Dimension].Filled(8))
moving_image.AllocateInitialized()
fixed_point = PointType([0.0, 0.0])
fixed_points = PointContainerType.New()
fixed_points.InsertElement(0, fixed_point)
moving_point = PointType([1.0, -2.0])
moving_points = PointContainerType.New()
moving_points.InsertElement(0, moving_point)
parameter_object = itk.ParameterObject.New()
parameter_object.AddParameterMap(
{"ImageSampler": ("Full",), …
```

Add SetFixedPoints and SetMovingPoints to ElastixRegistrationMethod, for point-to-point EuclideanDistanceMetric 

---

Common/Transforms/itkTransformToDeterminantOfSpatialJacobianSource.hxx
Common/Transforms/itkTransformToSpatialJacobianSource.hxx
Common/itkComputePreconditionerUsingDisplacementDistribution.hxx
Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx
Testing/elxTransformParametersCompare.cxx
Testing/itkBSplineInterpolationDerivativeWeightFunctionTest.cxx
Testing/itkBSplineInterpolationSODerivativeWeightFunctionTest.cxx
Testing/itkBSplineInterpolationWeightFunctionTest.cxx
Testing/itkGPUResampleImageFilterTest.cxx

- Following ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4906

Replace `T var; var.Fill` with `auto var = T::Filled`, for both `Index` and `Size`

---

.github/workflows/ElastixGitHubActions.yml
Testing/CI/Azure/ci.yml

Addressed https://github.com/SuperElastix/elastix/actions/runs/12160720437/job/33913645243 saying:
> The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see https://github.com/actions/runner-images/issues/10721

COMP: Replace `macos-12`/`macOS-12` with `macos-13`/`macOS-13`, in *.yml

---

Common/itkComputeJacobianTerms.hxx

`vnl_sparse_matrix::get(r, c)` just returns zero when the entry isn't there, and it returns immediately when the row is empty.
The performance of `vnl_sparse_matrix::get` was improved by:
- https://github.com/vxl/vxl/pull/932 commit https://github.com/vxl/vxl/commit/b37c7a22cd0ae5d50fe940f58e2c8e0ebc6ccd24
A performance improvement may not be noticeable, but it won't harm.

Use `vnl_sparse_matrix::get` in `ComputeJacobianTerms::Compute()` 

---

Common/ParameterFileParser/itkParameterFileParser.cxx

The prefix `this->` is not necessary when a class just accesses its own private data.

STYLE: Remove `this->` when `ParameterFileParser` accesses its own data

---

Common/ParameterFileParser/itkParameterFileParser.cxx
Common/ParameterFileParser/itkParameterFileParser.h
Core/Configuration/elxConfiguration.cxx
Core/Configuration/elxConfiguration.h

Three style commits to clarify how `Configuration` uses `ParameterFileParser`.

Make `ReturnParameterFileAsString` static, remove `m_ParameterFileParser` from `Configuration`

---

Common/ParameterFileParser/itkParameterMapInterface.h
Core/Configuration/elxConfiguration.cxx
Core/Configuration/elxConfiguration.h

- Addresses issue #1284 
Example "elastix.log" file, with this pull request:
```
WARNING: The parameter "FixedInternalImagePixelType", requested at entry number 0, does not exist at all.
The default value "float" is used instead.
[...]
WARNING: The parameter "Resampler", requested at entry number 0, does not exist at all.
The default value "DefaultResampler" is used instead.
ELASTIX version: 5.2.0
Command line options from ElastixBase:
-out      B:/data/output/
-priority unspecified, so NORMAL process priority
-threads  unspecified, so all available threads are used
WARNING: The parameter "UseDirectionCosines", requested at entry number 0, does not exist at all.
The default value "true" is used instead.
WARNING: The option "UseDirectionCosines" was not found in your parameter file.
From …
```

Print the parameter map to log, when there is no parameter file

---

Common/ParameterFileParser/itkParameterFileParser.cxx
Common/ParameterFileParser/tomlplusplus/toml.hpp
Core/Main/GTesting/itkTransformixFilterGTest.cxx
NOTICE

Supported TOML as file format for input parameter files (including transform parameter files). For example:
FixedImageDimension = 3
MovingImageDimension = 3
FixedInternalImagePixelType = "float"
MovingInternalImagePixelType = "float"
Size = [115, 166, 131]
Using [the TOML++ library](https://github.com/marzer/tomlplusplus) from Mark Gillard (@marzer).

Support the TOML file format for input parameter files

---

Common/GTesting/elxConversionGTest.cxx
Core/ComponentBaseClasses/elxResampleInterpolatorBase.hxx
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx
Core/Configuration/elxConfiguration.cxx
Core/Install/elxConversion.cxx
Core/Install/elxConversion.h
Core/Kernel/elxElastixTemplate.hxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/elxParameterObject.cxx

Supports the parameter `OutputTransformParameterMapFileFormat"` in elastix registration parameter files. Allows specifying the file format of the output transform parameter files.
Possible values:
- `"txt"`: Use the legacy file format, "TransformParameters.*.txt" (the default)
- `"TOML"`: Use the TOML file format, "TransformParameters.*.toml"
- `""` (empty string): Use the default
----
- Complementary to pull request #1288

ENH: Support `OutputTransformParameterFileFormat` parameter for TOML

---

.pre-commit-config.yaml
CONTRIBUTING.md
pixi.lock
pixi.toml
tools/pre-commit-setup.bash

Add a new ./tools/pre-commit-setup.bash. After a developer clones
the repository, they should run this script. This script will download
pixi, install python via pixi, and install the python pre-commit package
and set up the Git pre-commit hooks. These hooks will run clang-format
and other checks on commit.

ENH: Add pre-commit and pixi configuration

---

Core/ComponentBaseClasses/elxTransformBase.hxx

The prefix `this->` is not necessary when a class or class template just accesses its own private data.

STYLE: Remove `this->` when `elx::TransformBase` accesses its own data

---

Components/Optimizers/AdaGrad/elxAdaGrad.hxx
Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Optimizers/AdaptiveStochasticLBFGS/elxAdaptiveStochasticLBFGS.hxx
Components/Optimizers/AdaptiveStochasticVarianceReducedGradient/elxAdaptiveStochasticVarianceReducedGradient.hxx
Components/Optimizers/CMAEvolutionStrategy/elxCMAEvolutionStrategy.hxx
Components/Optimizers/ConjugateGradient/elxConjugateGradient.hxx
Components/Optimizers/ConjugateGradientFRPR/elxConjugateGradientFRPR.hxx
Components/Optimizers/FiniteDifferenceGradientDescent/elxFiniteDifferenceGradientDescent.hxx
Components/Optimizers/FullSearch/elxFullSearchOptimizer.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx
Components/Optimizers/QuasiNewtonLBFGS/elxQuasiNewtonLBFGS.hxx
Components/Optimizers/RSGDEachParameterApart/elxRSGDEachParameterApart.hxx
Components/Optimizers/RegularStepGradientDescent/elxRegularStepGradientDescent.hxx
Components/Optimizers/SimultaneousPerturbation/elxSimultaneousPerturbation.hxx
Components/Optimizers/StandardGradientDescent/elxStandardGradientDescent.hxx

Replaced `break` statements in `switch` cases by `return` statements, directly returning the appropriate string, in Optimizers.
Using Notepad++, Replace in Files:
Find what: ^  ([ ]+)stopcondition = "(.+)";\r\n  \1break;\r\n
Replace with: $1return "$2";
(*) Regular expression

STYLE: Simplify creating string representation of stop conditions

---

Core/Kernel/elxElastixBase.cxx

Previously, the git revision info (SHA and revision date) were only available to users of the executable (by `elastix.exe --extended-version`, as well as in the "elastix.log" file).

ENH: Let ElastixBase print git revision info, also for library users

---

Common/GTesting/elxConversionGTest.cxx
Components/Metrics/RigidityPenalty/itkTransformRigidityPenaltyTerm.hxx

The result of `std::pow` appears platform dependent. 
Following ITK pull requests:
- https://github.com/InsightSoftwareConsortium/ITK/pull/5248
- https://github.com/InsightSoftwareConsortium/ITK/pull/5249

Replace various `std::pow` calls

---

Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx

Sync `EulerStackTransform::InitializeTransform()` with `AffineLogStackTransform::InitializeTransform()`.

STYLE: Calculate `centerOfRotationIndex` StackTransform in 64-bit double

---

Common/Transforms/itkAdvancedImageMomentsCalculator.h
Common/itkComputeDisplacementDistribution.h
Common/itkComputeDisplacementDistribution.hxx

`ComputeDisplacementDistribution::m_NumberOfPixelsCounted` was only used in its `AfterThreadedCompute` member function, so it could be replaced by a local variable.
`AdvancedImageMomentsCalculator::m_NumberOfPixelsCounted` was always just zero, and it was never used.

Remove unnecessary private `m_NumberOfPixelsCounted` data members

---

Common/CostFunctions/itkAdvancedImageToImageMetric.h
Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/DisplacementMagnitudePenalty/itkDisplacementMagnitudePenaltyTerm.hxx
Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx
Components/Metrics/VarianceOverLastDimension/itkVarianceOverLastDimensionImageMetric.hxx

The `found` parameter always had the value `Superclass::m_NumberOfPixelsCounted`, so it might as well be removed.
---
@mstaring Looking at the initial commit, it appears that `CheckNumberOfSamples` always had a `found` parameter that should be equal to `m_NumberOfPixelsCounted`. Or the other way around, `m_NumberOfPixelsCounted` should be equal to `found`:  https://github.com/SuperElastix/elastix/blob/f6d2f4b5f63b54b88f407ff84e4dc3ca48b73ecf/src/Common/CostFunctions/itkAdvancedImageToImageMetric.hxx#L730-L740
In practice they _are_ always equal, because `m_NumberOfPixelsCounted` is always passed as the argument for this parameter. For example, https://github.com/SuperElastix/elastix/blob/0dd663acc9e34e9c627d3bf61d246634854f36cc/src/Components/Metrics/AdvancedNormalizedCorrelation/itkAdvanc …

Remove parameters from `CheckNumberOfSamples`, let `AdvancedImageToImageMetric` directly access its own data

---

Components/Optimizers/AdaptiveStochasticGradientDescent/elxAdaptiveStochasticGradientDescent.hxx
Components/Optimizers/PreconditionedStochasticGradientDescent/elxPreconditionedStochasticGradientDescent.hxx

The local variable `sigma4factor` has been equal to `1.0` for more than 16 years. (Starting with commit a90c96af2cfd9d79cf2b154b74b8ca7be5818550, 16 Jan 2008).
----
@stefanklein Looks like you introduced this constant with 27f26bf48252bf888bbe1107b237b66de3f0fcb5 and then set it to `1.0` with the next commit (a90c96af2cfd9d79cf2b154b74b8ca7be5818550), on the very same day, 16 Jan 2008. Do you agree that it may be removed now?

STYLE: Remove `sigma4factor` from StochasticGradientDescent Optimizers

---

Components/Transforms/AffineLogStackTransform/elxAffineLogStackTransform.hxx
Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx

`centerOfRotationPoint` was not used in AffineLogStackTransform. `RDcenterOfRotationIndex` and `redDimCenterOfRotationIndex` were not used anywhere in elastix.
The unused variables `centerOfRotationPoint` and `RDcenterOfRotationIndex` appear introduced with commit 2607ad674891168a96d1214823b62fefe280718a "Added AffineLogTransform and AffineLogStackTransform", 14 Apr 2016.
The unused `redDimCenterOfRotationIndex` variable appears introduced with commit 4dda84b59d1753597641bc3ec72b69541c1d97eb, "Added EulerStackTransform to trunkpublic", 1 Mar 2017.
@stefanklein Is it OK to you if I just merge this as a code clean-up?

STYLE: Remove unused variables from InitializeTransform stack transforms

---

.github/workflows/ElastixGitHubActions.yml

Python 3.8 has reached end of life (according to https://devguide.python.org/versions).

COMP: Upgrade GitHub Actions to Python 3.9

---

Components/Transforms/AdvancedAffineTransform/elxAdvancedAffineTransform.hxx
Components/Transforms/AffineDTITransform/elxAffineDTITransform.hxx
Components/Transforms/AffineLogStackTransform/elxAffineLogStackTransform.hxx
Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.hxx
Components/Transforms/EulerStackTransform/elxEulerStackTransform.hxx
Components/Transforms/EulerTransform/elxEulerTransform.hxx
Components/Transforms/SimilarityTransform/elxSimilarityTransform.hxx
Core/Main/elxParameterObject.cxx

Compilation against ITK v6.0a3 requires these semicolons after the itkExceptionMacro.

COMP: Add missing semicolons

---

Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Common/ImageSamplers/itkImageRandomSamplerSparseMask.hxx
Common/ImageSamplers/itkVectorDataContainer.h
Common/ImageSamplers/itkVectorDataContainer.hxx
Common/Transforms/itkAdvancedImageMomentsCalculator.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/KNNGraphAlphaMutualInformation/itkKNNGraphAlphaMutualInformationImageToImageMetric.hxx
Components/Metrics/PCAMetric/itkPCAMetric.hxx
Components/Metrics/PCAMetric2/itkPCAMetric2.hxx
Components/Metrics/SumOfPairwiseCorrelationsMetric/itkSumOfPairwiseCorrelationCoefficientsMetric.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx
Core/ComponentBaseClasses/elxTransformBase.hxx

Reduced the use of `unsigned long`, which is platform dependent (either 32-bit or 64-bit).

Replace `VectorDataContainer::Size()` calls with `std::vector::size()`, use `size_t` 

---

Common/GTesting/itkImageFileCastWriterGTest.cxx
Common/itkImageFileCastWriter.h
Common/itkImageFileCastWriter.hxx
Core/ComponentBaseClasses/elxResamplerBase.h
Core/ComponentBaseClasses/elxResamplerBase.hxx
Core/Main/GTesting/ElastixLibGTest.cxx
Core/Main/GTesting/itkElastixRegistrationMethodGTest.cxx
Core/Main/GTesting/itkTransformixFilterGTest.cxx
Core/Main/elxPixelTypeToString.h

Supported any of the following values for the elastix/transformix parameter `ResultImagePixelType`:
"int8", "uint8", "int16", "uint16", "int32", "uint32", "int64", "uint64", "float32", "float64".
The number of bits of such a fixed width type is guaranteed to be the same on all supported platforms.
Note that this commit adds support for 64-bit integer types on Windows (which was not supported on Windows before, because its "long" is only 32 bits).

ENH: Fixed width types ("int8", "float64", etc) for ResultImagePixelType

---

Core/Main/GTesting/ParameterObjectGTest.cxx
Core/Main/elxParameterObject.cxx
Core/Main/elxParameterObject.h

Make it easy to determine whether a parameter has been set in a
ParameterObject.

ENH: HasParameter methods for ParameterObject

---

Common/itkImageFileCastWriter.hxx

It appears unnecessary to create a dummy MetaImageIO object, in `ImageFileCastWriter<TInputImage>::GetDefaultOutputComponentType()`.
Triggered by a question from Matt McCormick (@thewtex) at https://github.com/InsightSoftwareConsortium/ITKElastix/pull/344#issuecomment-3025151785:
> What is the preferred way to get the same behavior without instantiating itk::MetaImageIO?

STYLE: Avoid dummy in ImageFileCastWriter::GetDefaultOutputComponentType

---

Common/OpenCL/ITKimprovements/itkOpenCLVector.h
Common/OpenCL/ITKimprovements/itkOpenCLVector.hxx

`OpenCLVector::operator[]` does potentially alter the internal state of the object, so it's more const-correct to just provide a non-const overload of this operator.
Moreover, this overload caused compile errors from Xcode (16.4) / Clang (17.0.0), as Aidyn Ubingazhibov (@AidynAIMedical) reported at issue https://github.com/SuperElastix/elastix/issues/1250:
> no member named 'map' in 'OpenCLVector<T>'; did you mean 'Map'?
This suggests that this particular overload was never used anyway.

COMP: Remove const overload of `operator[]` from OpenCLVector

---

Common/Transforms/itkAdvancedBSplineDeformableTransformBase.h
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.hxx
Components/Transforms/MultiBSplineTransformWithNormal/itkMultiBSplineDeformableTransformWithNormal.h

It was only used in commented-out code.

STYLE: Remove `m_JacobianImage` from BSpline transforms

---

Common/CostFunctions/itkAdvancedImageToImageMetric.hxx
Common/CostFunctions/itkParzenWindowHistogramImageToImageMetric.hxx
Common/OpenCL/Kernels/GPUBSplineTransform.cl
Common/Transforms/itkAdvancedBSplineDeformableTransform.hxx
Common/Transforms/itkAdvancedBSplineDeformableTransformBase.hxx
Common/Transforms/itkAdvancedTransform.h
Common/Transforms/itkCyclicBSplineDeformableTransform.hxx
Components/Metrics/AdvancedKappaStatistic/itkAdvancedKappaStatisticImageToImageMetric.hxx
Components/Metrics/AdvancedMattesMutualInformation/itkParzenWindowMutualInformationImageToImageMetric.hxx
Components/Metrics/AdvancedMeanSquares/itkAdvancedMeanSquaresImageToImageMetric.hxx
Components/Metrics/AdvancedNormalizedCorrelation/itkAdvancedNormalizedCorrelationImageToImageMetric.hxx
Components/Metrics/BendingEnergyPenalty/itkTransformBendingEnergyPenaltyTerm.hxx
Components/Metrics/NormalizedMutualInformation/itkParzenWindowNormalizedMutualInformationImageToImageMetric.hxx
Components/Metrics/StatisticalShapePenalty/itkStatisticalShapePointPenalty.hxx
Components/Metrics/SumSquaredTissueVolumeDifferenceMetric/itkSumSquaredTissueVolumeDifferenceImageToImageMetric.hxx

Using regular expressions, replacing ` \(\*(\w+)\);` with ` *$1;`, and `([ \(])\(\*(\w+)\)([ \)])` with `$1*$2$3`.

STYLE: Remove unnecessary parentheses from `(*variable)`

---

Core/Main/GTesting/ParameterObjectGTest.cxx
Core/Main/elxParameterObject.cxx

Let users just use the transform name "bspline" (which was already preferred anyway).
Follow-up to commit 5d725fd33d585fe3be68d5619cacc1ee00510bf7, "STYLE: Rename nonrigid default parameter map to the more precise name of bspline", Kasper Marstal, 15 Feb 2016.
----
@mstaring @stefanklein Just for your information! (I think dropping the name "nonrigid" isn't controversial anymore, as Kasper already introduced the preferred name "bspline" more than 9 years ago.)

STYLE: Drop support ParameterObject::GetDefaultParameterMap("nonrigid")

---

Common/GTesting/CMakeLists.txt
Common/GTesting/itkGridScheduleComputerGTest.cxx
Common/Transforms/itkGridScheduleComputer.h
Common/Transforms/itkGridScheduleComputer.hxx
Components/Transforms/AdvancedBSplineTransform/elxAdvancedBSplineTransform.hxx
Components/Transforms/BSplineStackTransform/elxBSplineStackTransform.hxx
Components/Transforms/MultiBSplineTransformWithNormal/elxMultiBSplineTransformWithNormal.hxx
Components/Transforms/RecursiveBSplineTransform/elxRecursiveBSplineTransform.hxx

`GridScheduleComputer::SetDefaultSchedule` always had an upsampling factor of `2.0`, so it is not necessary to have it as a parameter or a data member (`m_UpsamplingFactor`) anymore.

Make default upsampling factor of GridScheduleComputer fixed (`2.0`)

---

Common/Transforms/itkGridScheduleComputer.hxx

`m_ImageDirection` was originally just zero-filled, in the default-constructor of `GridScheduleComputer`. By commit 18e1e8b0d16092fc353b14ccf64195fdcd9b0d70, Coert Metz, 28-06-2013. However `itk::Image` does not allow using a zero-filled direction. For example, the following code would cause an exception:
ImageType::DirectionType direction;
direction.Fill(0.0);
image->SetDirection(direction);
The exception would says something like:
> itkImageBase.hxx:139: in 'void itk::ImageBase::SetDirection(const itk::Matrix &)':
> ITK ERROR: Image: Bad direction, determinant is 0. Refusing to change direction from 1 0 0 1 to 0 0 0 0
Obviously, `itk::Image` _does_ allow using an identity matrix instead.

BUG: Initialize GridScheduleComputer ImageDirection as identity matrix
